README.md, lessons/basics.md, lessons/enum.md
Create `Enum` lesson and update `Basic`.
=> More lessons

README.md, lessons/basics.md, lessons/collections.md, lessons/control-structures.md, lessons/enum.md, lessons/pattern-matching.md
Add Pattern matching, control structures, and strings/binaries.  This closes #9.
=> Add three new lessons

README.md, lessons/plug.md, lessons/testing.md
=> Add Lessons on Testing and Plug

lessons/basics.md, lessons/collections.md, lessons/composition.md, lessons/control-structures.md, lessons/functions.md, lessons/mix.md, lessons/pattern-matching.md, lessons/plug.md, lessons/testing.md
As I was going through elixir-school I noticed a few grammar/spelling mistakes. I the project really useful, so I decided to do what I could to contribute and fixed those errors I could find. I also added a note that the booleans true and false are also atoms in the Basics lesson. Just as an FYI I suppose.
=> Mostly grammar/spelling error fixes.

README.md, lessons/advanced/concurrency.md
=> Processes, Agents, and Tasks

_assets/stylesheets/custom.css
=> allow sidebar content to scroll

_config.yml, _includes/head.html, _includes/sidebar.html, index.md, lessons/advanced/concurrency.md, lessons/advanced/erlang.md, lessons/advanced/escripts.md, lessons/advanced/otp-concurrency.md, lessons/advanced/otp-supervisors.md, lessons/basics/basics.md, lessons/basics/collections.md, lessons/basics/composition.md, lessons/basics/control-structures.md, lessons/basics/enum.md, lessons/basics/functions.md, lessons/basics/mix.md, lessons/basics/pattern-matching.md, lessons/basics/testing.md, lessons/specifics/ecto.md, lessons/specifics/plug.md
Here it is @erickgnavar, @ZuraGuerra, and @3100.  This pull request is first draft at implementing multiple language support on elixirschool.com.
To create a new language:
1. Create a folder for the 2 character language code (e.g. jp, en, es, etc)
1. Add `lessons/{basics,advanced,specifics}` folders inside it.
1. Move translated lessons over.
1. Add `lang: XX` to the lesson page meta data.
1. Add the language to _config.yml as part of `languages` and the `sections` translations.
=> Support multiple languages

README.md
Update README to include steps for contributing to the translation efforts.
cc @3100, @erickgnavar, @ZuraGuerra — is this clear enough?
=> Translation Steps

lessons/basics/enum.md
Hi! This PR is quite simple. Its goal is to fix up a small markdown formatting error:
> PS: Thank you very much for this tutorial! It's an awesome resource to learn Elixir!
=> Fix a small markdown error on basic/enum.md

lessons/advanced/metaprogramming.md
Howdy @3100 & @erickgnavar!  
This PR adds the meta programming lesson.  Would you mind looking it over any letting me know your thoughts?
Close #8
=> Add metaprogramming lesson

lessons/specifics/ets.md
Feedback welcome but I still include to add a few more sections.
=> Add ETS lesson

lessons/specifics/ets.md
=> Disable temporarily Liquid tag processing

_config.yml, cn/index.md, cn/lessons/basics/basics.md, cn/lessons/basics/collections.md, cn/lessons/basics/composition.md, cn/lessons/basics/control-structures.md, cn/lessons/basics/enum.md, cn/lessons/basics/functions.md, cn/lessons/basics/mix.md, cn/lessons/basics/pattern-matching.md, cn/lessons/basics/testing.md
This commit includes following changes:
+ add Chinese translation conf in _config.yml
+ translate index.md
+ translate all basics lessons
=> Translate basics into chinese.

lessons/basics/basics.md, lessons/basics/collections.md, lessons/basics/composition.md, lessons/basics/pattern-matching.md, lessons/specifics/eex.md
This PR includes a few things, comments and feedback welcomed:
- Elixir 1.2 updates
- Added section on `alias`, `import`, `require`, and `use`
- New EEx lesson
Closes #52, #53, #62.
/cc @3100, @milmazz, @pjhampton
=> Elixir 1.2 updates and EEx lesson

cn/lessons/advanced/concurrency.md, cn/lessons/advanced/erlang.md, cn/lessons/advanced/escripts.md, cn/lessons/advanced/metaprogramming.md, cn/lessons/advanced/otp-concurrency.md, cn/lessons/advanced/otp-supervisors.md
Hey, I finished the advanced section translation. 
Please review the commit, and feel free to merge.
=> Translate advanced section into Chinese.

es/lessons/specifics/ecto.md
This lesson is almost done, I just need to translate the following sections:
/cc @doomspork @erickgnavar
=> Spanish translation for Ecto lesson

README.md, _config.yml, index.md, lessons/specifics/ets.md
Going through the ETS lesson again and wanted to reword a few things.
=> Minor ETS changes

lessons/basics/sigils.md, lessons/basics/testing.md
As discussed in #50. Let me know if there is any issues and I will get on them.
=> Adding Sigils lesson.

lessons/advanced/concurrency.md, lessons/advanced/error-handling.md, lessons/advanced/escripts.md, lessons/advanced/metaprogramming.md, lessons/advanced/otp-concurrency.md, lessons/advanced/otp-supervisors.md
=> New Error Handling lesson

_config.yml, index.md, pt/index.md, pt/lessons/basics/basics.md
Added initial portuguese translation.
=> Added the basic section in portuguese

pt/lessons/basics/collections.md, pt/lessons/basics/enum.md
New sections in portuguese language
=> Added enum and collection sections in portuguese language

_config.yml, index.md, vi/index.md, vi/lessons/advanced/concurrency.md, vi/lessons/advanced/erlang.md, vi/lessons/advanced/error-handling.md, vi/lessons/advanced/escripts.md, vi/lessons/advanced/metaprogramming.md, vi/lessons/advanced/otp-concurrency.md, vi/lessons/advanced/otp-supervisors.md, vi/lessons/basics/basics.md, vi/lessons/basics/collections.md, vi/lessons/basics/composition.md, vi/lessons/basics/control-structures.md, vi/lessons/basics/documentation.md, vi/lessons/basics/enum.md, vi/lessons/basics/functions.md, vi/lessons/basics/mix.md, vi/lessons/basics/pattern-matching.md, vi/lessons/basics/sigils.md, vi/lessons/basics/testing.md, vi/lessons/specifics/ecto.md, vi/lessons/specifics/eex.md, vi/lessons/specifics/ets.md, vi/lessons/specifics/plug.md
Xin chào!
It will take few more weeks until Elixir Vietnam usergroup can translate all pages to Vietnamese. For the time being, I'd like to suggest to merge for whatever we have.
=> Vietnamese Translation

vi/lessons/basics/enum.md
Hi, I added a Vietnamese translation for basic lesson on Enum
=> Add Vietnamese translation for basic - Enum

vi/lessons/basics/collections.md
@joneslee85 Please help to review :smiley:
=> Vietnamese translation for Basics - Collections

vi/lessons/basics/enum.md
@joneslee85 @trexnix please help to review and improve
=> Improve vietnamese translation for enum docs

lessons/advanced/erlang.md, lessons/specifics/eex.md, lessons/specifics/ets.md, lessons/specifics/mnesia.md
Just leaving this Mnesia lesson here for peer review, proof reading etc.
Feel free to give me any comments, change requests etc!
Thanks! :smile_cat: 
References #50
=> Mnesia Lesson / Janitor Work

vi/lessons/advanced/erlang.md
@joneslee85 please help to review and improve. 
I will translate Advanced lessons to learn at the same time :smiley:
=> Add vietnamese translation for Advance - Erlang Interoperability

pt/lessons/basics/pattern-matching.md
=> Adding Pattern Matching in Portuguese(Brazil)

pt/lessons/basics/functions.md
=> Adding functions to Portuguese(Brazil)

pt/lessons/basics/control-structures.md
=> Adding Control Structures in Portuguese(Brazil)

pt/lessons/basics/basics.md, pt/lessons/basics/collections.md, pt/lessons/basics/enum.md
=> Updating basics, collections and enum for Portuguese(Brazil)

lessons/basics/composition.md, lessons/basics/documentation.md, lessons/basics/functions.md, lessons/basics/mix.md, lessons/basics/pipe-operator.md, lessons/basics/sigils.md, lessons/basics/testing.md
- Added Pipe Operator Lesson for Review
- Reordered basic lessons
=> Pipe Operator Lesson, Reordered Basic Lessons

cn/lessons/basics/composition.md, cn/lessons/basics/documentation.md, cn/lessons/basics/functions.md, cn/lessons/basics/mix.md, cn/lessons/basics/pipe-operator.md, cn/lessons/basics/sigils.md, cn/lessons/basics/testing.md, lessons/basics/testing.md, pt/lessons/basics/testing.md, vi/lessons/basics/composition.md, vi/lessons/basics/documentation.md, vi/lessons/basics/functions.md, vi/lessons/basics/mix.md, vi/lessons/basics/pipe-operator.md, vi/lessons/basics/sigils.md, vi/lessons/basics/testing.md
=> Reordered lessons / Removed Best Practices

pt/lessons/basics/composition.md, pt/lessons/basics/documentation.md, pt/lessons/basics/functions.md, pt/lessons/basics/mix.md, pt/lessons/basics/pipe-operator.md, pt/lessons/basics/sigils.md, pt/lessons/basics/testing.md
* Translating pipe-operator.md
* Updating order of basic lessons
=> Add pipe operator to Portuguese(Brazil)

lessons/specifics/mnesia.md
Minor update to prevent any possible confusion from any readers.
=> Changed erl func representation to ex style for consistency.

lessons/basics/mix.md
This just replaces 'loads' with 'load'.
=> Fix pluralization in the 'Interactive' section of 'Mix'.

ru/lessons/basics/enum.md
Hey @brain-geek! Super thanks for all your contributions! I really appreciate it :smile: make sure you remember to update the lang file next time so it doesn't interfere with the base language lessons.
cc @doomspork
=> Fixed lang issue with Russian Enum.

pt/lessons/specifics/ecto.md, pt/lessons/specifics/eex.md, pt/lessons/specifics/ets.md
ets.md page translated to Portugues.
@pragmaticivan review please
=> Translate specifics/ets.md page to Portuguese - issue #123

pt/lessons/advanced/erlang.md
=> Add Erlang interoperability to Portuguese (Brazil)

es/lessons/basics/basics.md, es/lessons/basics/pattern-matching.md
Add comparison section in basics lesson
Update pin section in pattern matching lesson
=> Add missing content

pt/lessons/advanced/error-handling.md
File error-handling - Translation complete
=> File error-handling.md - Translation  complete

jp/lessons/specifics/ets.md
I never thought my name would be used in a lesson. That's nice :japanese_ogre:
=> add jp translation of ETS.

pt/lessons/advanced/concurrency.md
Correcting errors generated for me about pull request!
=> Translation of the concurrency.md file

sk/lessons/basics/mix.md
Add slovak translation of Basics/Mix lesson.
=> Add slovak translation of Basics/Mix lesson.

lessons/advanced/umbrella-projects.md
Just delivering the Umbrella Projects lesson. Refs #50
=> Added Umbrella Projects Lesson.

lessons/advanced/umbrella-projects.md, pt/lessons/advanced/umbrella-projects.md
Anchors needs quotes. 
It fixes this page: https://elixirschool.com/pt/lessons/advanced/umbrella-projects/
=> Fix anchor

lessons/basics/sigils.md
=> Fixes typo in Sigils

es/lessons/basics/composition.md
Title's very straight :shipit:
=> Adds composition lesson translation to spanish

pt/lessons/basics/sigils.md
Minor fixes for portuguese translation.
=> Fixes portuguese sigils page typos and syntax mistakes

_config.yml
=> Added french language to website (#196).

fr/index.md, fr/lessons/basics/basics.md
=> French translation of basics/basics

fr/lessons/basics/control-structures.md
=> [fr] add control-structures

fr/lessons/basics/pattern-matching.md
=> [fr] add Pattern matching

fr/lessons/basics/enum.md
=> [fr] add Enum

fr/lessons/basics/pipe-operator.md
=> [Fr] add pipe operator

_config.yml, it/index.md
=> [it] add index page for IT translation (refers #197)

lessons/basics/collections.md
As recommended by @julienXX in #232
=> FIX: Removed redundant dict ref.

it/index.md, it/lessons/basics/basics.md, it/lessons/basics/collections.md, it/lessons/basics/composition.md, it/lessons/basics/control-structures.md, it/lessons/basics/enum.md, it/lessons/basics/functions.md, it/lessons/basics/mix.md, it/lessons/basics/pattern-matching.md, it/lessons/basics/pipe-operator.md
two more translations for #197 🎉
=> [it] add basics/*.md translations (refers #197)

_assets/stylesheets/custom.scss
I created this Pull Request because seems to be annoying the current version looks like we're using an `iframe`. You guys can check, it's just a suggestion.
=> Hide sidebar scrool

es/lessons/basics/basics.md
=> Translation fix (0x1F = 31)

es/lessons/basics/enum.md
Commented lines translated into Spanish
=> Commented lines translated enum.md

lessons/basics/control-structures.md
RFC @pjhampton & @pragmaticivan (and anyone else) — Added a section on `with` to the control structure lesson.
=> Add a section on `with`

lessons/basics/comprehensions.md
RFC @pragmaticivan, @pjhampton — Please __DO NOT MERGE__, need to figure out the order of this lesson in the basics section.
=> New list comprehensions lesson

_assets/stylesheets/app.scss, _assets/stylesheets/social.scss, _config.yml, _includes/head.html, _includes/social.html, _layouts/page.html
This adds social buttons with proper links from the Jekyll data.  This is a pure CSS implementation.
Here is an example of what it looks like:
This addresses https://github.com/doomspork/elixir-school/issues/199
=> Adds In Social Buttons

_config.yml
=> Change Chinese description in config file

fr/index.md, gr/index.md, it/index.md, my/index.md, pt/index.md
Let me get your thoughts @pragmaticivan 
This closes #270
=> Remove translated languages from all but English index

lessons/specifics/plug.md
I believe it should be "GET requests"?
=> Fix a wording in plug.md

cn/lessons/specifics/plug.md
@cizixs please review if you have time :smile:
=> [On #72] Translate plug.md into Chinese

pl/basics/collections.md
=> [PL] add translation of collection

pl/basic/enum.md
=> [PL] add translation of enum lesson

_config.yml, no/index.md
Added the necessary config setups and translated the frontpage index.md to norwegian.
=> Frontpage in Norwegian

pl/basics/pattern-matching.md
=> [PL] Translation of pattern matching lesson

lessons/basics/strings.md
Now 'strings' is last lesson in basics
=> Fix #317 Move String lesson to position 14

pl/lessons/basics/pipe-operator.md
=> [PL] translation of pipe operator

pl/lessons/basics/composition.md
=> [PL] Translation of composition lesson

es/lessons/specifics/ets.md, jp/lessons/specifics/ets.md, lessons/specifics/ets.md, pt/lessons/specifics/ets.md, vi/lessons/specifics/ets.md
These examples are super handy, thanks!
=> Fix a few typos in ETS examples

_config.yml, ko/index.md
@rijgndqw012 and some of my friends found a great documentation of Elixir programming language which wants to be translated into Korean(#201), and started translating to it. 
I'm glad to translate Elixir School in Korean! :rocket:
=> [KO] Added Korean translation and index page

pl/lessons/basics/mix.md
=> [PL] Translation of mix lesson

pl/lessons/basics/sigils.md
=> [PL] Translation of sigils lesson

pl/lessons/basics/documentation.md
=> [PL] Translation of documentation lesson

lessons/basics/mix-tasks.md
I could do with some early feedback here. I stole this idea from you @sivsushruth - maybe you could look over this pull request as well and offer some feedback?
=> New Mix Tasks Lesson (en)

ko/lessons/basics/collections.md
=> [KO] Translation of Collections lesson

fr/lessons/basics/mix.md
=> [FR] Add 'basics/mix' lesson translation

lessons/basics/composition.md
found in this blog: http://learningelixir.joekain.com/use-import-require-in-elixir/
=> detailed explanation of USE

no/lessons/basics/basics.md, no/lessons/basics/enum.md, no/lessons/basics/pattern-matching.md
Reviewed by @Sirsjr
Also added a missing punctuation in enum.md
=> [NO] Basics/patternmatching translated

no/lessons/basics/basics.md, no/lessons/basics/control-structures.md, no/lessons/basics/enum.md, no/lessons/basics/pattern-matching.md
=> [NO] Basics/control structures translated

fr/lessons/basics/sigils.md
In scope of issue #196.
@julienXX some more work for you, sorry :)
=> Add [FR] translation for basics/sigils 

pl/lessons/basics/testing.md
=> [PL] Translation of testing lesson

pl/lessons/basics/comprehensions.md
=> [PL] translation of comprehention

_config.yml, fr/lessons/basics/mix.md, fr/lessons/basics/sigils.md, ko/lessons/basics/collections.md, ko/lessons/basics/enum.md, lessons/basics/mix-tasks.md, no/lessons/basics/control-structures.md, no/lessons/basics/pattern-matching.md, pl/lessons/basics/comprehensions.md, pl/lessons/basics/testing.md
Added automatic TOC generation to the translations that were added during our work over it.
=> Apply the TOC generator to the remaining translations

no/lessons/basics/basics.md, no/lessons/basics/pipe-operator.md
=> [NO] Basic/pipeoperator translated

jp/lessons/basics/basics.md
=> [JP] Update translation in 'basics/basics' lesson

pl/lessons/advanced/erlang.md
=> [PL] Translation of erlang interop lesson

jp/lessons/basics/pattern-matching.md
Update description of pin operator
#49
=> [JP] Update translation in 'basics/pattern-matching'

jp/lessons/basics/collections.md
* Remove topics about dictionary(deprecated)
* Elixir 1.2 updates
=> [JP] Update translation in 'basics/collections'

pl/lessons/advanced/error-handling.md
=> [PL] translation of errors lesson

lessons/basics/documentation.md, vi/lessons/basics/documentation.md
I think this "out" was meant to say "our".
=> Correct word in documentation lesson

cn/lessons/advanced/escripts.md, jp/lessons/advanced/escripts.md, lessons/advanced/escripts.md, pt/lessons/advanced/escripts.md, ru/lessons/advanced/escripts.md, vi/lessons/advanced/escripts.md
Addresses issue [392](https://github.com/doomspork/elixir-school/issues/392)
=> ES-392 fix Fixes the bad output and removes complexity on advanced/escript lesson

ru/lessons/specifics/ecto.md
Described in #366.
@brain-geek, could you take a peek at this, please?
=> [RU] Update 'specifics/ecto' lesson translation

ru/lessons/basics/mix-tasks.md
@brain-geek, could you take a look at this once you have a moment?
=> [RU] Add 'basics/mix-tasks' lesson translation

jp/lessons/basics/sigils.md
I translated a short chapter, **Sigils** lesson into Japanese.
=> [JP] Translation of Sigils Lesson

cn/lessons/basics/functions.md, cn/lessons/basics/pipe-operator.md, es/lessons/basics/functions.md, es/lessons/basics/pipe-operator.md, fr/lessons/basics/pipe-operator.md, it/lessons/basics/functions.md, it/lessons/basics/pipe-operator.md, jp/lessons/basics/functions.md, jp/lessons/basics/pipe-operator.md, my/lessons/basics/functions.md, my/lessons/basics/pipe-operator.md, no/lessons/basics/pipe-operator.md, pl/lessons/basics/functions.md, pl/lessons/basics/pipe-operator.md, pt/lessons/basics/functions.md, pt/lessons/basics/pipe-operator.md, ru/lessons/basics/functions.md, ru/lessons/basics/pipe-operator.md, sk/lessons/basics/functions.md, sk/lessons/basics/pipe-operator.md, vi/lessons/basics/functions.md, vi/lessons/basics/pipe-operator.md
Applied the order swap from #424 to every language.
=> Swap the page order of `functions.md` and `pipe-operator.md`

id/lessons/basics/strings.md, pl/lessons/basics/strings.md
=> Update the `basics/strings` lesson translations

cn/lessons/specifics/plug.md, es/lessons/specifics/plug.md, id/lessons/specifics/plug.md, jp/lessons/specifics/plug.md, pl/lessons/specifics/plug.md, pt/lessons/specifics/plug.md, vi/lessons/specifics/plug.md
I have removed concation project references from all translations
=> removing concation project references

jp/lessons/basics/testing.md
This commit is mainly about #47
=> [JP] Update translation in testing lesson

jp/lessons/basics/modules.md
Any comments or suggestion are welcome!
- I am not sure the phrase '名前／アリティのペア' (the name/arity pairs) is understandable.
- '`use`' section's translation might be a bit stiff.
=> [JP] Update 'basics/modules' lesson

pl/lessons/specifics/ets.md
in scope of issue #202 
cc @kdebowski
=> [PL] Translation of ETS

pl/lessons/specifics/mnesia.md
In scope of issue #202 
cc @kdebowski
=> [PL] Translation of mnesia

no/lessons/basics/mix.md, no/lessons/basics/modules.md, no/lessons/basics/sigils.md
Needs to be reviewed before merging 😄
=> [NO] Translation of Sigils

_assets/stylesheets/social.scss, _includes/social.html
[VK](https://new.vk.com/) is [the biggest social network](https://en.wikipedia.org/wiki/VK_(social_networking)) in the CIS countries.
Along with adding the share button for it I also removed the repeating inline style and fixed the formatting in `social.scss`.
=> Add a share button for `vk.com`

ko/lessons/basics/comprehensions.md
#201 Any comments are welcome :sweat_smile:
=> [KO] Translation of Comprehensions Lesson

ko/lessons/basics/testing.md
related: #201
I applied some feedbacks from @dalgona.
You can compare the trasnlated text with the original text at devleoper/elixir-school#1
This PR is ready for review. :rocket:
=> [KO] Translation of Testing lesson

ko/lessons/basics/pipe-operator.md
#201 
Please refer to Dalgona/elixir-school#2 for side-by-side comparison and comments. :rocket:
=> [KO] Translation of Pipe Operator Lesson

ko/lessons/basics/functions.md
related to #201.
just pruned branches :)
=> [KO] Translation of Function lesson

ko/lessons/basics/documentation.md
related to #201 
just pruned branches :)
=> [KO] Translation of Documentation lesson

ko/lessons/basics/strings.md
related to #201 
just pruned branches :)
=> [KO] Translation of Strings lesson

ko/lessons/specifics/plug.md
Related to: #201 
@Dalgona @devleoper @rijgndqw012
Sadly, there is no lesson I could take on basic lesson...that's why I translate this.
Please review this when you have time, it's fine after basic lesson trslation done :)
=> [KO] Translation of Plug lesson

ko/lessons/specifics/ecto.md
Related to: #201
@Dalgona @devleoper @rijgndqw012
Please review this when you have time, it's fine after basic lesson translation done :)
=> [KO] Translation of Ecto lesson

ko/lessons/specifics/mnesia.md
Related to: #201
@Dalgona @devleoper @rijgndqw012
Please review this when you have time, it's fine after basic lesson translation done :)
=> [KO] Translation of Mnesia lesson

cn/lessons/specifics/ecto.md
=> [CN] Translate Ecto.md (#72)

lessons/basics/basics.md
This was quite confusing for me at first. Hopefully it clarifies things for others.
=> Add some more information about atoms

lessons/basics/collections.md
I took the text for the official [elixir getting-started guid](http://elixir-lang.org/getting-started/keywords-and-maps.html#maps), and simplified the example a bit.
=> Explain syntax for updating maps and access atom keys. Fix #402

ko/lessons/advanced/error-handling.md
related to #201 
Any feedback is welcome 😸 
@devleoper @Dalgona @riseshia
=> [KO] Translation of Error handling lesson

ko/lessons/advanced/otp-concurrency.md
related to #201 
Any feedback is welcome 😸 
@riseshia @devleoper @Dalgona
=> [KO] Translation of OTP concurrency lesson

cn/lessons/basics/basics.md
Apply updates mentioned in #480 in Chinese.
=> CN: update atom section in basic lesson.

cn/lessons/basics/collections.md
apply changes mentioned in #481 in Chinese.
=> CN: add section on updating and accessing maps with atoms.

ru/lessons/basics/collections.md
Russian translation for #481.
/cc @brain-geek
=> [RU] Update the `basics/collections` lesson

jp/lessons/advanced/metaprogramming.md
=> [JP] Add debugging section to metaprogramming lesson

jp/lessons/basics/basics.md
Apply #470 changes to Japanese translation
=> [JP] Update atom section in basic lesson

ko/lessons/advanced/escripts.md
For comparing original text to translated, refer to devleoper/elixir-school#2.
It might have some outdated content, I'm going to fix it.
Related: #201
=> [KO] Translation of Executables Lesson

ko/lessons/basics/collections.md
Related: #201 and #481
Korean Translation is not finished yet! Elixir changes day-by-day so does Elixir School. :laughing:
Even this pull request actually translated just a line, feel free to give a feedback.
@Dalgona @riseshia @malkoG
=> [KO] Translated updating/accessing maps section into Korean

fr/lessons/basics/pipe-operator.md, id/lessons/basics/pipe-operator.md, it/lessons/basics/pipe-operator.md, jp/lessons/basics/pipe-operator.md, ko/lessons/basics/pipe-operator.md, lessons/basics/pipe-operator.md, my/lessons/basics/pipe-operator.md, no/lessons/basics/pipe-operator.md, pl/lessons/basics/pipe-operator.md, pt/lessons/basics/pipe-operator.md, ru/lessons/basics/pipe-operator.md, sk/lessons/basics/pipe-operator.md, vi/lessons/basics/pipe-operator.md
Improved "Pipe operator" lesson example according to suggestion in #305 task.
=> Improved "Pipe operator" lesson

index.md
Related: https://github.com/doomspork/elixir-school/pull/510#issuecomment-233132558
=> Correct the link text in the main page

jp/lessons/basics/collections.md
Apply #452 changes to Japanese translation
=> [JP] Add description of special syntax of map

_config.yml, _includes/social.html
=> Translate the social media section

es/lessons/specifics/ets.md, id/lessons/specifics/ets.md, jp/lessons/specifics/ets.md, ko/lessons/specifics/ets.md, lessons/specifics/ets.md, pl/lessons/specifics/ets.md, pt/lessons/specifics/ets.md, ru/lessons/specifics/ets.md, vi/lessons/specifics/ets.md
I've fixed a small error in the DETS example which could cause confusion.
=> Fixed DETS example

bg/lessons/basics/functions.md, bg/lessons/basics/modules.md, bg/lessons/basics/pipe-operator.md
=> [BG] Apply the latest order and name changes

ru/lessons/basics/enum.md
@brain-geek, could you take a peek at this, please?
=> [RU] Update `Enum.chunk_by`

ru/lessons/specifics/mnesia.md
Could you review this, please, @brain-geek?
=> [RU] Add 'specifics/mnesia' lesson translation

bg/lessons/basics/mix.md, cn/lessons/basics/mix.md, es/lessons/basics/mix.md, fr/lessons/basics/mix.md, id/lessons/basics/mix.md, it/lessons/basics/mix.md, jp/lessons/basics/mix.md, ko/lessons/basics/mix.md, lessons/basics/mix.md, my/lessons/basics/mix.md, no/lessons/basics/mix.md, pl/lessons/basics/mix.md, pt/lessons/basics/mix.md, ru/lessons/basics/mix.md, sk/lessons/basics/mix.md, vi/lessons/basics/mix.md
phoenix_slim deps changed, Im just updating Mix Lesson to show new deps.
=> update phoenix_slim deps lesson 9: Mix

ru/lessons/specifics/plug.md
Hello, please check my `plug.md` translation and provide your comments, suggestions and corrections! Thanks!
=> [RU] plug.md translation

jp/lessons/basics/mix-tasks.md
#49 
I can't understand meaning of `shipping our application` enough so review is welcome.
=> [JP] Add custom Mix task lesson

jp/lessons/basics/enum.md
=> [JP] Update `Enum.chunk_by/2` in enum lesson

fr/lessons/basics/functions.md
@tchoutri / @julienXX — Can you check that this is satisfactory?
Thank you again for your help 👍
=> [FR] Functions

sk/lessons/basics/mix-tasks.md
I skipped the first example with Phoenix because I found it quite confusing for the reader, since we haven't been talking about Phoenix so far. Also IMO it doesn't add anything substantial to the rest of the lesson.
=> [sk] Add basics lesson Mix Tasks.

it/lessons/advanced/concurrency.md
Refers to #197. 
Hope there are some keen Italians around for double-checking this! 
@omissis @apeacox, perhaps? 😁
=> [IT] add translation for concurrency lesson

id/lessons/advanced/umbrella-projects.md, jp/lessons/advanced/umbrella-projects.md, lessons/advanced/umbrella-projects.md, pl/lessons/advanced/umbrella-projects.md, pt/lessons/advanced/umbrella-projects.md
`machine_learning_toolkit/app` misses one last letter in a dir name: `machine_learning_toolkit/apps`
=> [en] small fix in umbrella-projects.md / Child projects

GLOSSARY.md, ru/lessons/advanced/umbrella-projects.md
Hello, please check my translation and leave Your comments and suggestions. What do You think about  translation of `umbrella project` as `зонтичный проект`?
=> [RU] umbrella-projects.md translation, and GLOSSARY.md update

pl/lessons/basics/pipe-operator.md
=> Issue 574 fix pipe oper

jp/lessons/basics/pipe-operator.md
=> [JP] Fix best practices example in pipe operator lesson

sk/lessons/basics/collections.md
And translate term "linked lists".
=> [SK] Using proper term in 'collection' - cons operator #608

pl/lessons/basics/strings.md
=> [PL] update translation about codepoints and graphems (#598)

cn/lessons/basics/basics.md
=> fix some typos

ko/lessons/basics/pipe-operator.md
cc: @devleoper, @malkoG, @riseshia 
ref: #569, #574 
Any feedbacks are welcome! Thanks :rocket: :rocket:
=> [KO] Fix best practices example in Pipe Operator lesson

lessons/advanced/typespec.md, lessons/basics/typespec.md
@doomspork, @nscyclone please take a look.
=> Issue #338 spectypes

jp/lessons/specifics/eex.md
Added eex.md Japanese Translation.
=> Added eex.md Japanese Translation

_config.yml, index.md, uk/index.md, uk/lessons/basics/basics.md
Language code for Ukrainian is 'uk' according to the [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).
=> ua -> uk according to ISO 639-1

fr/lessons/basics/pipe-operator.md
These changes were provided by @julienXX in the corresponding [issue](https://github.com/doomspork/elixir-school/issues/574#issuecomment-236831932) but nobody proposed a PR with them yet.
=> [FR] Fix best practices example in the `basics/pipe-operator` lesson

es/lessons/basics/collections.md
=> [ES] Add example for handling of duplicates in list substraction

id/lessons/advanced/erlang.md, ko/lessons/advanced/erlang.md
just syntax error. No need to i18n review :p
=> [ko, id] Fix typo

lessons/advanced/typespec.md
=> [en] Fix link

no/lessons/basics/collections.md
Reference issues #608 and  #612
=> [NO] Updated with proper terminology and substraction of duplicate lists for basics/collections lesson

no/lessons/basics/pipe-operator.md
=> [NO] Updated the `pipe_operator` section for the basics/pipe-operator lesson

no/lessons/basics/enum.md
=> [NO] Updated the  `Enum.chunk_by` section for the basics/enum lesson

gr/lessons/advanced/umbrella-projects.md, id/lessons/advanced/umbrella-projects.md, jp/lessons/advanced/umbrella-projects.md, ko/lessons/advanced/umbrella-projects.md, lessons/advanced/umbrella-projects.md, pl/lessons/advanced/umbrella-projects.md, pt/lessons/advanced/umbrella-projects.md, ru/lessons/advanced/umbrella-projects.md
@pjhampton @doomspork 
Based on discussion here https://github.com/doomspork/elixir-school/pull/666
=> remove unnecessary --sup command

es/lessons/basics/collections.md, es/lessons/basics/control-structures.md, es/lessons/basics/enum.md, es/lessons/basics/functions.md, es/lessons/basics/mix.md, es/lessons/basics/modules.md, es/lessons/basics/pattern-matching.md, es/lessons/basics/pipe-operator.md, es/lessons/basics/testing.md
I'm just starting to learn Elixir and found your site, so I thought it would be good to help a little if I can :)
=> [es] Some fixes on spanish translation

jp/lessons/advanced/concurrency.md
=> [JP] Update message passing in concurrency section

lessons/basics/testing.md
Here's my first draft to address #593 . What do you think? Is it factually correct, too much, too little?
=> Extend paragraph on Mocking

bg/lessons/basics/enum.md, cn/lessons/basics/enum.md, es/lessons/basics/enum.md, fr/lessons/basics/enum.md, gr/lessons/basics/enum.md, id/lessons/basics/enum.md, it/lessons/basics/enum.md, jp/lessons/basics/enum.md, ko/lessons/basics/enum.md, lessons/basics/enum.md, my/lessons/basics/enum.md, no/lessons/basics/enum.md, pl/lessons/basics/enum.md, pt/lessons/basics/enum.md, ru/lessons/basics/enum.md, sk/lessons/basics/enum.md, vi/lessons/basics/enum.md
- Added an extra example with strings and accumulator to explain correct order that reducer works
=> Additional reduce string example with accumulator

pt/lessons/basics/comprehensions.md
Related to [#355](https://github.com/doomspork/elixir-school/issues/355)
This lesson is not in the issue's list of pages to translate, but it doesn't have a translation.
Feel free to give me your feedback @pragmaticivan and anyone who wants to revise this translation.
=> [pt] translation for comprehensions

_config.yml
This refers to issue [#453](https://github.com/doomspork/elixir-school/issues/453).
=> [pt] Translation for social media section

lessons/basics/basics.md, lessons/basics/documentation.md, lessons/basics/mix-tasks.md, lessons/basics/pipe-operator.md, lessons/basics/sigils.md, lessons/basics/testing.md
Recently I've discovered a `proselint` tool and wanted to try it out.
Here is the first batch of changes suggested by the tool. While minor, I think that these changes make text better.
If this PR goes OK - I'll create a few more with fixes for other lessons and a CI check for it.
=> Minor improvements for basic lessons

lessons/advanced/metaprogramming.md, lessons/advanced/typespec.md, lessons/advanced/umbrella-projects.md, lessons/specifics/ets.md, lessons/specifics/mnesia.md
As in the previous PR #709 , I'm using `proselint` to look through our english lessons and improve them.
Next step would be adding it as a CI check. :)
=> Proofread non-basic lessons

no/lessons/basics/enum.md
=> [NO] Updated the Enum lesson with elixir 1.4 changes

pt/lessons/advanced/otp-supervisors.md
=> [PT] Update translation for supervisors

pt/lessons/basics/basics.md
=> [PT] Update atom section in basic lesson

pt/lessons/basics/testing.md
=> [PT] Update section on mocking

lessons/advanced/otp-supervisors.md
The #658 issue got me an idea about improving the existing lesson.
While it's additional info, I guess that understanding this concept is important.
=> Add restart values to the supervisors lesson

pt/lessons/basics/basics.md
Updated Basics lesson translation.
=> [PT] Update Basics Translation

pt/lessons/basics/enum.md
Checklist for this update is in #701.
=> [PT] Update enum functionalities for Elixir 1.4 (#696).

lessons/specifics/mnesia.md, pl/lessons/specifics/mnesia.md
The nested unordered list in the last paragraph didn't look as expected.
=> Fix the markup in the latest changes of the `specifics/mnesia` lesson

pt/lessons/basics/collections.md
=> [PT] Update translation for maps syntax

_config.yml, de/index.md, de/lessons/advanced/concurrency.md, de/lessons/advanced/escripts.md, de/lessons/basics/basics.md, de/lessons/basics/collections.md, de/lessons/basics/comprehensions.md, de/lessons/basics/control-structures.md, de/lessons/basics/documentation.md, de/lessons/basics/enum.md, de/lessons/basics/functions.md, de/lessons/basics/mix-tasks.md, de/lessons/basics/mix.md, de/lessons/basics/modules.md, de/lessons/basics/pattern-matching.md, de/lessons/basics/pipe-operator.md, de/lessons/basics/sigils.md, de/lessons/basics/strings.md, de/lessons/basics/testing.md, index.md
Hey, 
as I already said on Twitter I started translating elixir-school into German :) Here are all basic tutorials and I already started to translate some of the advanced lessons. Expect to get another PR the next days when I'll translated the rest of it!
=> Basic support for German

cn/lessons/advanced/concurrency.md
=> [CN] Update message passing in Concurrency section

cn/lessons/basics/collections.md, cn/lessons/basics/functions.md
This commit solves #583 and #642 , plus update other collections content.
=> [Cn] Describe function name format

cn/lessons/basics/pipe-operator.md
This newly translated article also solves #574
=> [CN] translate pipe operator

cn/lessons/specifics/ecto.md
=> [CN] Add description to count function

de/lessons/basics/basics.md, de/lessons/basics/enum.md, de/lessons/basics/modules.md, de/lessons/basics/sigils.md
Updated to newest additions from upstream.
=> [DE] Update translation to upstream

lessons/advanced/behaviours.md
Started a new lesson on behaviours.  Still rather short so would like some feedback and ideas on additional content to include.
cc @brain-geek / @nscyclone / @pjhampton / @ybur-yug / et al
=> New lesson on behaviours

lessons/advanced/gen-stage.md
New GenStage lesson!  Big thanks to @ybur-yug for his help (sorry again for gutting a lot of the changes).  Next I'd like to get out a lesson covering Flow/GenFlow which should be relatively short since it's similar to Enum.
This lesson is what kicked off the conversation taking place in #768.  It'd be great to expand on what we have here and build something bigger with tests.
RFC @ybur-yug, @pjhampton, @brain-geek, @pragmaticivan, @nscyclone and anyone else 😀
=> New GenStage Lesson

pt/lessons/basics/strings.md
Related to [#355](https://github.com/doomspork/elixir-school/issues/355)
This lesson is not in the issue's list of pages to translate, but it doesn't have a translation.
Feel free to give me your feedback @pragmaticivan and anyone who wants to revise this translation.
=> [PT] Translation for Strings

pt/lessons/specifics/mnesia.md
=> [PT] Update Mnesia translation

cn/lessons/basics/testing.md
=> [CN] update testing lesson

cn/lessons/basics/strings.md
This commit translate `basics/strings` to Chinese, thus solving #598
=> [CN] translate basics string lesson

lessons/advanced/gen-stage.md
The wrong word was used. Fix't!
I don't know what's up w/ the diff, I only changed one word.
=> Onerous -> Onus

de/lessons/advanced/erlang.md, de/lessons/advanced/error-handling.md, de/lessons/advanced/metaprogramming.md, de/lessons/advanced/otp-concurrency.md, de/lessons/advanced/otp-supervisors.md, de/lessons/advanced/typespec.md, de/lessons/advanced/umbrella-projects.md, de/lessons/basics/basics.md, de/lessons/basics/enum.md, de/lessons/basics/modules.md, de/lessons/basics/sigils.md
Hey,
here are more lessons from the advanced sections. I haven't had a look at the new sections 'genStage' and 'behaviors'. PHEW, it's hard to keep up that pace! 😄
=> [DE] Advanced sections

pl/lessons/advanced/metaprogramming.md
Three typos in **polish** translation were corrected.
Hope it helps :-)
=> [PL] Three typos were corrected

pl/lessons/basics/collections.md
Word *kodyfikacja* was replaced with *modyfikacja*.
=> [PL] Collections - Typo in polish translation

pl/lessons/basics/comprehensions.md
Missing space between *list* and *(ang. list comprehensions)*
=> [PL] Comprehensions - Minor typo

lessons/basics/pattern-matching.md
=> Improve the explanation of pattern matching

pl/lessons/basics/control-structures.md
A few minor corrections in polish translation.
=> [PL] Control structures: Corrections

pl/lessons/basics/enum.md
My proposition is to replace ";" with "." and start new sentence.
=> [PL] Replacement of ";" with "."

pl/lessons/basics/collections.md, pl/lessons/basics/sigils.md
=> [PL] Minor typos in chapters: Collections and Sigils

fr/lessons/basics/pattern-matching.md
Hello !
This is the french translations for the original changes in #808.
Feedback welcome ;)
=> [FR] Improve the explanation of pattern matching

lessons/advanced/typespec.md
The link to modules (struct) is incorrect. Just wanted to fix that
=> fix modules link using relative link

pl/lessons/basics/sigils.md
=> [PL] Sigils: formatting issue

lessons/specifics/guardian.md
I'm opening new PR for this, as #431 is pointing to old version of branch.
I've rebased it and applied some feedback. My changes are added in separate commit.
Let's have some discussion and merge it soon! :)
=> Add guardian

_config.yml
Hi there,
This PR is to add the Italian translation for issue #834. Cheers! 🎉
=> Add libraries label in Italian

lessons/libraries/poolboy.md
The other branch had too much going on after merging upstream. I've created this clean branch instead.
=> Added lesson for PoolBoy

_config.yml
=> [JA, KO] Add libraries label

pl/lessons/specifics/ets.md
Only small typo (missed space)
=> [PL] fix for #785

lessons/libraries/poolboy.md
=> Minor changes to poolboy.md

_config.yml, bn/index.md
-- New Locale
-- Index File For BN locale
=> [BN]Added the first index.md for bn locale

de/lessons/specifics/eex.md
Hi!
I tried to translate the Lesson for Specifics/EEx to german.
Feedback welcome, still struggling a bit with technical terms in my mother tongue ^^
=> [DE] german translation for specifics/eex

README.md
As was noticed by @nscyclone, approach without explicit protocol does not work on Github.
=> Update license image URL

no/lessons/basics/documentation.md
Translation of basic/documentation in Norwegian.
=> [NO] translation of documentation

index.md
-- Added the BN locale link on the Main Index File of the Elixir School Page.
=> Added BN locale link

pt/lessons/basics/mix-tasks.md
Signed-off-by: capaci rafaelcp123@gmail.com
Related to #355.
=> [PT] added portuguese translation to mix-tasks section

lessons/advanced/gen-stage.md
I was reading through the GenStage lesson and thought I'd make some minor copy edits  if you wanted them. Thanks for the service!
=> copy edits for genstage

ru/lessons/basics/control-structures.md
Original changes are #882 , translation tracking is #893
=> [RU] Add else example for case operator

pt/lessons/basics/functions.md
small Orthographic correction in basics/functions.md
=> pt Orthographic correction

lessons/libraries/guardian.md
#911 Changes Javascript to JSON
Fixes typo.
=> Fixes name error and typo

pl/lessons/libraries/guardian.md
=> Fix full name of JWT

lessons/specifics/iex_helpers.md
There are a _ton_ of great built-in helpers for IEx. In my experience, most people dont dabble too far from `c`, `h`, and occasionally `r`. This dives into the usage of some of them in the form of a highlight reel, concentrating on the ones with the most utility in my day-to-day experience.
=> New Lesson: IEx Helpers

lessons/specifics/plug.md
Adds missing content, and reorganizes lesson into smaller, more-digestible chunks.
https://github.com/doomspork/elixir-school/issues/828
=> #828 Plug lesson fixes

lessons/specifics/debugging.md
I finally found a moment to proofread this and it looks like there were some things to be improved.
Requesting reviews from:
- @doomspork &mdash; to make sure that I didn't make any new grammar mistakes;
- @Koziolek &mdash; to make sure that I didn't distort the original sense.
=> Correct the `specifics/debugging` lesson

ko/lessons/basics/basics.md
These change apply #501 to the only untouched file.
=> [KO] Remove the `iex` line numbers

lessons/specifics/debugging.md
The TOC for the debugging lesson seems a little wonky, this should clean things up.
=> Cleanup Debugging TOC

pt/lessons/basics/strings.md
=> [PT-BR] Fixes UTF-8 encoding description

pl/lessons/advanced/otp-concurrency.md
=> Change word 

ko/lessons/advanced/otp-concurrency.md
=> [KO] Remove References to GenEvent

gr/lessons/advanced/protocols.md
=> greek translation advanced\protocols

_config.yml
=> [CN] add libraries label in config

lessons/specifics/plug.md
The tracking thread as below:
https://github.com/doomspork/elixir-school/issues/965
=> fix Plug Router.start/2 is undefined or private

jp/lessons/basics/enum.md
#534
I can't understand meaning of 'combining enum with documentation' enough. What do you mean?
=> [JP] Improve Enum basics section

ru/lessons/advanced/protocols.md
This PR adds Russian translation to Protocols. #956
=> [RU] Add translation for Protocols lesson

_config.yml, bn/lessons/basics/enum.md
@code-shoily and @masnun please review this Pull Request
=> BN Translation of Enum chapter

lessons/specifics/plug.md
Tiny typo fix I came across while reading through this section.
=> fix typo: exmaple -> example

bn/lessons/basics/mix.md, bn/lessons/basics/pattern-matching.md
The Mix Chapter completed in Bangla. Requesting @masnun and @prio101 for a quick check :)
=> The Mix Chapter - First Pass

no/lessons/basics/testing.md
=> [NO]: Add lesson on testing

no/lessons/basics/modules.md
Previous snippets were also translated. This is not necessary as the semantics and intuition of the code snippets is importanter.
=> [NO]: Correct to use default code snippets

bn/lessons/basics/pipe-operator.md
@masnun @prio101 guys do your magic, `Pipe Operator` is done. :)
Thanks in Advance.
=> [BN] Added translation for chapter `Pipe Operator`

bn/lessons/basics/modules.md
Please check for correctness @masnun @prio101
=> [BN] Translated the lesson on `Modules`

bn/lessons/basics/comprehensions.md
Added the chapter for List Comprehension. @masnun and @prio101 as usual, calling you out for a check :)
=> [BN] Added the chapter on List Comprehension

bn/lessons/basics/strings.md
@masnun and @prio101 did the String chapter. I think we'll need to get back to it later and enrich it more, feels incomplete when re-read.
=> [BN] Translated the lessons on String

no/lessons/basics/comprehensions.md
This is a Norwegian translation of the comprehensions chapter.
=> [NO] Translation of comprehensions

lessons/advanced/metaprogramming.md
Syntax highlighting of one source code was missing. Fixed.
=> Fixing missed syntax highlighting

bn/lessons/basics/iex_helpers.md
@masnun @prio101 please check :)
=> [BN] Translated the chapter on IEx Helpers

bn/lessons/basics/functions.md
@masnun @prio101 you know the drill. I am done translating today. Have fun!
=> [BN] Chapter Translated- Function

bn/lessons/basics/control-structures.md
As discussed in the IM, I've translated the lesson on `Control Structure`. Thanks @masnun it was refreshing to take a stab at `with` statement again.
Please check the translation out. You too @prio101 
Thanks :)
=> [BN] Translated the Control Structure lesson

bn/lessons/basics/documentation.md
I was fairly thorough on this one. But still @masnun @prio101  could give it a look?
=> [BN] Translation of the lesson on Documentation.

bn/lessons/basics/mix-tasks.md
@masnun @prio101 please take a look at this one. Thanks in advance.
=> [BN] Added translation for Mix Task

pt/lessons/basics/iex_helpers.md
Related to #355 
This lesson is not in the pt translation list, but there is no translation for that. So I took the responsibility to do it.
Please review it and give me feedback if there is something to fix.
=> [PT] Translation for IEx Helpers

ru/lessons/advanced/concurrency.md, ru/lessons/advanced/erlang.md, ru/lessons/advanced/error-handling.md, ru/lessons/advanced/escripts.md, ru/lessons/advanced/otp-concurrency.md, ru/lessons/advanced/otp-supervisors.md, ru/lessons/advanced/umbrella-projects.md, ru/lessons/basics/basics.md, ru/lessons/basics/collections.md, ru/lessons/basics/comprehensions.md, ru/lessons/basics/control-structures.md, ru/lessons/basics/documentation.md, ru/lessons/basics/functions.md, ru/lessons/basics/mix-tasks.md, ru/lessons/basics/mix.md, ru/lessons/basics/pattern-matching.md, ru/lessons/basics/pipe-operator.md, ru/lessons/basics/sigils.md, ru/lessons/basics/strings.md, ru/lessons/basics/testing.md, ru/lessons/libraries/guardian.md, ru/lessons/libraries/poolboy.md, ru/lessons/specifics/ecto.md, ru/lessons/specifics/eex.md, ru/lessons/specifics/ets.md, ru/lessons/specifics/mnesia.md
This PR bumps the version of up-to-date translations.
There also are some stale translations, going to mention those in #220.
=> [RU] Validate translation versions

_config.yml
=> greek version messages

es/lessons/basics/enum.md
=> Update `Enum.chunk_by` to es - Fix #529

ko/lessons/specifics/plug.md
The change is to fix incorrect and its explanation in Plug.Router section.
=> [KO] Fixed incorrect code and explanation.

pt/lessons/specifics/debugging.md
Issue https://github.com/doomspork/elixir-school/issues/355 
Translation of the Debugging page into Portuguese
Version in English [here](https://elixirschool.com/lessons/specifics/debugging/)
=> [PT] Translation for Debugging page

_config.yml
Update version messages as requested in #1025
=> [ES] Version messages related #1025

cn/lessons/basics/mix-tasks.md
Chinese translation for basics/mix-tasks
=> add mix-tasks translation for cn

lessons/specifics/plug.md
* Add more explanation for those not knowledgeable in OTP.
* Some touch-up for consistency
* Rename "Installation" section to "Prerequisites", which is more accurate.
* Add section for starting new project.
* More explanation about the roles and arguments of a Plug.
On my last PR for this lesson (https://github.com/doomspork/elixir-school/pull/861), I never opened an issue for translations. Should I open one now, or after this is merged?
=> Touchup of Plug tutorial

bg/lessons/basics/enum.md, bn/lessons/basics/enum.md, cn/lessons/basics/enum.md, de/lessons/basics/enum.md, es/lessons/basics/enum.md, fr/lessons/basics/enum.md, gr/lessons/basics/enum.md, id/lessons/basics/enum.md, it/lessons/basics/enum.md, jp/lessons/basics/enum.md, ko/lessons/basics/enum.md, lessons/basics/enum.md, my/lessons/basics/enum.md, no/lessons/basics/enum.md, pl/lessons/basics/enum.md, pt/lessons/basics/enum.md, ru/lessons/basics/enum.md, sk/lessons/basics/enum.md, vi/lessons/basics/enum.md
=> fix russian translation "does not" to "does"

es/lessons/basics/enum.md
Complete translation review and update for lessons/enum.md to spanish
=> es Feature/update enum lesson to v1.0.0

es/lessons/basics/basics.md
Update basics lesson spanish translation to v1.0.0 
cc @erickgnavar
=> [es] update basics lesson to v1.0.0

cn/lessons/specifics/ecto.md, es/lessons/specifics/ecto.md, gr/lessons/specifics/ecto.md, id/lessons/specifics/ecto.md, jp/lessons/specifics/ecto.md, ko/lessons/specifics/ecto.md, lessons/specifics/ecto.md, pl/lessons/specifics/ecto.md, pt/lessons/specifics/ecto.md, ru/lessons/specifics/ecto.md, vi/lessons/specifics/ecto.md
=> Fix typo in ecto.md

bg/lessons/basics/pattern-matching.md, bn/lessons/basics/pattern-matching.md, cn/lessons/basics/pattern-matching.md, cn/lessons/specifics/ets.md, de/lessons/basics/pattern-matching.md, es/lessons/basics/pattern-matching.md, es/lessons/specifics/ets.md, fr/lessons/basics/pattern-matching.md, gr/lessons/basics/pattern-matching.md, gr/lessons/specifics/ets.md, id/lessons/basics/pattern-matching.md, id/lessons/specifics/ets.md, it/lessons/basics/pattern-matching.md, jp/lessons/basics/pattern-matching.md, jp/lessons/specifics/ets.md, ko/lessons/basics/pattern-matching.md, ko/lessons/specifics/ets.md, lessons/basics/pattern-matching.md, lessons/specifics/ets.md, my/lessons/basics/pattern-matching.md, no/lessons/basics/pattern-matching.md, pl/lessons/basics/pattern-matching.md, pl/lessons/specifics/ets.md, pt/lessons/basics/pattern-matching.md, pt/lessons/specifics/ets.md, ru/lessons/basics/pattern-matching.md, ru/lessons/specifics/ets.md, sk/lessons/basics/pattern-matching.md, vi/lessons/basics/pattern-matching.md, vi/lessons/specifics/ets.md
In the same vein as https://github.com/doomspork/elixir-school/pull/1076
=> Use space around cons operator

_config.yml
Related #1025 
@Dalgona, @malkoG, @devleoper, @marocchino review please.
=> [KO] Add version_messages

ko/lessons/basics/enum.md
After #1088 
@devleoper Please check this XD
=> [KO] Remove useless backquote

lessons/basics/control-structures.md, pt/lessons/basics/basics.md
Do we need bump up? @doomspork
=> Fix markdown syntax

_config.yml
@Koziolek, could you please take a peek at this? Thanks in advance!
=> [PL] Version messages

ko/lessons/basics/collections.md
- Fixed to '갱신' from an incorrect word '경샌'
=> Fixed word

lessons/specifics/plug.md
* Fix error described in https://github.com/doomspork/elixir-school/issues/1043#issuecomment-295615390
* Update lesson for Elixir 1.4 (1.3 no longer supported)
* Clearer code formatting
* Improved program output
* Adds instructions to RouterTest, at end of lesson
Translations to be covered by existing issue #1043.
=> Fixes issue brought up in #1043

_assets/stylesheets/poole.css
<details> 
<summary>Before:</summary>
</details>
<details> 
<summary>After:</summary>
</details>
=> Improve word wrapping

en/lessons/basics/enum.md
=> [EN] Updating Enum.uniq/1 to Enum.uniq_by/2

pt/lessons/specifics/plug.md
This PR is for updating the Plug section for Portuguese according to the most recent version in English.
I've committed the updates for each section and there is the last one that does a general review on typos. After the PR review, I'll squash it to a single commit, to make easier the merge.
=> Updated [PT]/lessons/Specific/Plug.md ✍️💅

en/lessons/specifics/plug.md
This lost me an hour trying to debug. Hopefully this will save someone else the same problem.
=> Adjusting the localhost to 127.0.0.1

pt/lessons/basics/basics.md
The correct result for 0x1F on iex is 31
=> Fixing the incorrect result of 0x1F is 31

en/lessons/advanced/gen-stage.md
=> Adds clarification for Producer section in GenStage lesson

_data/locales/sk.yml
Update Slovak version messages. Related #1025
=> [SK] Update version messages 

en/lessons/basics/enum.md
Basic grammatical error fixed.
=> its --> it's in enum.md

_data/locales/sk.yml, sk/index.md, sk/lessons/basics/basics.md, sk/lessons/basics/collections.md, sk/lessons/basics/comprehensions.md, sk/lessons/basics/control-structures.md, sk/lessons/basics/documentation.md, sk/lessons/basics/enum.md, sk/lessons/basics/functions.md, sk/lessons/basics/iex-helpers.md, sk/lessons/basics/mix-tasks.md, sk/lessons/basics/mix.md, sk/lessons/basics/modules.md, sk/lessons/basics/pattern-matching.md, sk/lessons/basics/pipe-operator.md, sk/lessons/basics/sigils.md, sk/lessons/basics/strings.md, sk/lessons/basics/testing.md
Hi 👋 
I noticed the Slovak translations were outdated. So, I went through them, translated the changes in each one and bumped the version, so they are up to date. I also added translation of `iex-helpers.md` lesson, because it didn't exist 🙂
=> [SK] Update translations

cn/lessons/advanced/concurrency.md, de/lessons/advanced/concurrency.md, de/lessons/advanced/error-handling.md, en/lessons/advanced/concurrency.md, en/lessons/advanced/error-handling.md, es/lessons/advanced/concurrency.md, es/lessons/advanced/error-handling.md, gr/lessons/advanced/concurrency.md, gr/lessons/advanced/error-handling.md, id/lessons/advanced/concurrency.md, id/lessons/advanced/error-handling.md, it/lessons/advanced/concurrency.md, jp/lessons/advanced/concurrency.md, jp/lessons/advanced/error-handling.md, ko/lessons/advanced/concurrency.md, ko/lessons/advanced/error-handling.md, my/lessons/advanced/concurrency.md, pl/lessons/advanced/concurrency.md, pl/lessons/advanced/error-handling.md, pt/lessons/advanced/concurrency.md, pt/lessons/advanced/error-handling.md, ru/lessons/advanced/concurrency.md, ru/lessons/advanced/error-handling.md, vi/lessons/advanced/concurrency.md, vi/lessons/advanced/error-handling.md
Changed by commit: 
https://github.com/elixir-lang/elixir/commit/9ea814f3206721703ebf16977d08e176eb1e7556#diff-9e50910893ff9df17cdef7cc055397f4R248
=> Process exiting messages changed

_config.yml, ar/lessons/basics/basics.md, bg/lessons/basics/basics.md, bn/lessons/basics/basics.md, cn/lessons/basics/basics.md, de/lessons/basics/basics.md, en/lessons/basics/basics.md, es/lessons/basics/basics.md, fr/lessons/basics/basics.md, gr/lessons/basics/basics.md, id/lessons/basics/basics.md, it/lessons/basics/basics.md, jp/lessons/basics/basics.md, ko/lessons/basics/basics.md, my/lessons/basics/basics.md, no/lessons/basics/basics.md, pl/lessons/basics/basics.md, pt/lessons/basics/basics.md, ru/lessons/basics/basics.md, sk/lessons/basics/basics.md, th/lessons/basics/basics.md, tr/lessons/basics/basics.md, uk/lessons/basics/basics.md, vi/lessons/basics/basics.md
=> New Elixir and Erlang versions

bg/lessons/basics/functions.md, bn/lessons/basics/functions.md, cn/lessons/basics/functions.md, de/lessons/basics/functions.md, en/lessons/basics/functions.md, es/lessons/basics/functions.md, fr/lessons/basics/functions.md, gr/lessons/basics/functions.md, id/lessons/basics/functions.md, it/lessons/basics/functions.md, jp/lessons/basics/functions.md, ko/lessons/basics/functions.md, my/lessons/basics/functions.md, pl/lessons/basics/functions.md, pt/lessons/basics/functions.md, ru/lessons/basics/functions.md, sk/lessons/basics/functions.md, vi/lessons/basics/functions.md
https://github.com/elixir-lang/elixir/blob/144df88caedfae891e12fcd3595c61b64783fd12/lib/elixir/src/elixir_def.erl#L342
https://github.com/elixir-lang/elixir/blob/23517c5413f3830daaf69d859fe7418085b21268/lib/elixir/lib/exception.ex#L836
=> Update of error messages in basics/functions examples

bg/lessons/basics/mix.md, bn/lessons/basics/mix.md, cn/lessons/basics/mix.md, de/lessons/basics/mix.md, en/lessons/basics/mix.md, es/lessons/basics/mix.md, fr/lessons/basics/mix.md, gr/lessons/basics/mix.md, id/lessons/basics/mix.md, it/lessons/basics/mix.md, jp/lessons/basics/mix.md, ko/lessons/basics/mix.md, my/lessons/basics/mix.md, no/lessons/basics/mix.md, pl/lessons/basics/mix.md, pt/lessons/basics/mix.md, ru/lessons/basics/mix.md, sk/lessons/basics/mix.md, vi/lessons/basics/mix.md
=> Update mix.exs file snippet for newly created projects

pl/lessons/basics/testing.md
Update examples for testing for Polish translation.
=> [PL] Update mix generated test files

en/lessons/basics/testing.md
=> [EN] Setup test example update

th/lessons/basics/collections.md
Changes proposed in this pull request:
* Translate collections section into Thai
@iboss-ptk Would you mind help me review this PR, please?
=> [TH] Translate Collections

pt/lessons/advanced/gen-stage.md
Translated to Portuguese as requested in #355.
=> [PT] Translation of GenStage to Portuguese.

pt/lessons/advanced/behaviours.md
Translated to Portuguese as requested in #355.
@anderkonzen could you please review it?
=> [PT] Translation of Behaviours

th/lessons/basics/control-structures.md
Please review my translation 🇹🇭 
@iboss-ptk
=> [TH] Control Structures

th/lessons/specifics/mnesia.md
@iboss-ptk  @zkan, please review if you have time. 🙇
=> [TH] Mnesia

th/lessons/advanced/erlang.md
=> [TH] Erlang Interoperability

pt/lessons/advanced/error-handling.md
Fixing some Portuguese sentences
=> [PT] Improve Error Handling

sk/lessons/advanced/concurrency.md, sk/lessons/advanced/erlang.md, sk/lessons/advanced/error-handling.md, sk/lessons/advanced/escripts.md
Hi 👋,
I started translating the Slovak version of Advanced lessons. The first four lessons are finished and I will translate the rest of the lessons as soon as I am able to. 🙂
=> [SK] Translate advanced lessons

jp/lessons/specifics/plug.md
issue https://github.com/elixirschool/elixirschool/issues/1043
I'm trying to translate lesson Plug 1.1.0 into japanese.
=> [JP] translate plug 1.1.1 to jp

jp/lessons/basics/iex-helpers.md
issue https://github.com/elixirschool/elixirschool/issues/922
I'm working on japanese translation of IEx helpers lesson.
=> [JP] translate IEx helpers lesson into japanese

_data/locales/jp.yml
I added japanese translation of version messages :smile:
issue https://github.com/elixirschool/elixirschool/issues/1025
=> [JP] Add version_messages

jp/lessons/advanced/otp-concurrency.md
issue https://github.com/elixirschool/elixirschool/issues/947
I removed `GenEvent` references.
=> [JP] Remove references to GenEvent

ru/lessons/basics/basics.md, ru/lessons/basics/testing.md
Recently there were a couple of updates to original basic lessons, so this PR brings Russian translations up-to-date.
=> [RU] Actualize the `basics` section

pt/lessons/libraries/benchee.md
This commit adds the Portuguese version of Benchee lesson. See #1165.
=> [PT] Translate Benchee lesson to Portuguese

en/lessons/advanced/concurrency.md
=> Add enhancement in explanation for Process Linking in Concurrency lesson

en/lessons/libraries/bypass.md
It's about time I started to produce more content (amongst other activities) so here's my newest lesson!
**Note** — I haven't created the mentioned repo yet but I do have the code.  I'd love to hear thoughts on this approach.  For more involved lessons, should we have accompanying projects?
Would love to get thoughts and feedback!
cc @gemantzu, @ybur-yug, @nscyclone, @brain-geek, @pragmaticivan, and anyone else 😁
=> Add new Bypass lesson

en/lessons/advanced/concurrency.md
I decided not to bump the version numbers since there are no translations of the latest version yet.
=> Improve the section that clarifies the exits trapping

ko/lessons/basics/basics.md
- 1.1.0 -> 1.1.1 #1143
- 1.1.1 -> 1.1.2 #1184
cc @devleoper @doomspork
=> [KO] Update basics/basics 1.1.0 -> 1.1.2

jp/lessons/advanced/behaviours.md
I added Japanese translation for lesson of advanced/behaviours.
(refer to #1293 )
=> [JP] Translation of advanced/behaviours #1293

en/lessons/libraries/bypass.md, pt/lessons/libraries/bypass.md
This is the translation of Bypass lesson to Portuguese.
=> [PT] Translate Bypass lesson

pt/lessons/basics/control-structures.md
Update docs for control structures #1295
=> [PT] Update Control structures to version 1.1.1

pt/lessons/basics/mix.md
Update docs for mix #1295
I changed the order from two sessions to match the English docs
=> [PT] update mix translation to 1.0.1

bn/lessons/basics/strings.md, cn/lessons/advanced/erlang.md, cn/lessons/basics/strings.md, de/lessons/advanced/erlang.md, de/lessons/basics/strings.md, en/lessons/advanced/erlang.md, en/lessons/basics/strings.md, es/lessons/advanced/erlang.md, gr/lessons/advanced/erlang.md, gr/lessons/basics/strings.md, id/lessons/advanced/erlang.md, id/lessons/basics/strings.md, jp/lessons/advanced/erlang.md, jp/lessons/basics/strings.md, ko/lessons/advanced/erlang.md, ko/lessons/basics/strings.md, ms/lessons/advanced/erlang.md, no/lessons/basics/strings.md, pl/lessons/advanced/erlang.md, pl/lessons/basics/strings.md, pt/lessons/advanced/erlang.md, pt/lessons/basics/strings.md, ru/lessons/advanced/erlang.md, ru/lessons/basics/strings.md, sk/lessons/basics/strings.md, vi/lessons/advanced/erlang.md, vi/lessons/basics/strings.md
https://github.com/elixir-lang/elixir/blob/v1.5/CHANGELOG.md#exceptionblame
For Korean language, they need to update their translated error below updated error.
=> Update FunctionClaseError message

ko/lessons/basics/basics.md
Forgive me that I forgot to bump up version in #1296 T-T
@doomspork @devleoper
=> [KO] Bump up version of basics/basics

pt/lessons/specifics/eex.md
Update specifics for eex #1295
=> [PT] Update specifics eex to version 1.0.2

pt/lessons/basics/testing.md
Update basic for testing #1295
=> [PT] Update basic testing to version 1.1.1

pt/lessons/basics/modules.md
=> [PT] Update module to version 1.2.0

pt/lessons/basics/testing.md
Fixing loop redirect on https://elixirschool.com/pt/lessons/basics/testing/
=> [pt-BR] Fixing loop redirection of page testing in Portuguese

ko/lessons/advanced/metaprogramming.md
a014ce3e2ea74a8a7b612095a8f0f6c28325b908 was just code fommating
change was applied in bb90b45f2e0b38b52ad9b70cf8f5ea5f1185d65c
=> [KO] Update metaprogramming

pt/lessons/specifics/eex.md
This fixes the redirect loop in this lesson.
=> [PT] Remove redirect_from in EEx lesson

ko/lessons/advanced/concurrency.md
@elixirschool/korean review please.
=> [KO] Bump up advanced/concurrency to 1.1.0

pt/lessons/advanced/metaprogramming.md
=> [PT] Updates advanced metaprogramming to latest version

pt/lessons/advanced/escripts.md
=> [pt] update advanced -> escripts

ru/lessons/advanced/concurrency.md
Corresponding changes to the original lesson can be found in #1277 and #1287.
=> [RU] Improve the section that clarifies the exits trapping

_assets/javascripts/contributors.js, _includes/head.html, _includes/social.html
* links must have a `title`;
* images must have an `alt`;
* external links using `[target="_blank"]` must have `[rel="noopener"]` to deny access to `window.opener`;
* it is recommended not to limit viewport's `maximum-scale`.
<details>
<summary>Before:</summary>
</details>
<details>
<summary>After:</summary>
</details>
=> Improve accessibility

en/lessons/basics/enum.md
Hello folks 👋🏻,
This PR is the real work based on discussion from #1342.
Any thoughts?
Thanks! 🙏🏻
=> Add Enum.filter/2 lesson (#1342)

ja/lessons/basics/enum.md
Translate https://github.com/elixirschool/elixirschool/pull/1349
Follow up https://github.com/elixirschool/elixirschool/pull/1351
Please review this @elixirschool/japanese
=> Refine text & bump up version

pl/lessons/basics/pattern-matching.md
Hi All,
I've made small changes in `Operator dopasowania` section. I think these changes will improve readability.
Cheers,
Rafal
=> [PL] Pattern matching. Minor fixes in polish translation.

pl/lessons/basics/functions.md
Hi All,
Hope that below changes will improve readability:
1. replaced `nastepujacy` with `następujacy`
2. replaced `nie` with `nich`
Cheers,
Rafal
=> [PL] Two minor changes in functions.md file

pl/lessons/basics/modules.md
Hi All,
I separated two words `Pozwala` and `na` with the use of a white space :-)
Cheers,
Rafal
=> [PL] Typo in modules.md

pl/lessons/basics/sigils.md
Hi All,
I replaced `.` with `,` :)
Cheers,
Rafal
=> [PL] Minor typo in sigils.md

pl/lessons/basics/testing.md
Hi All,
I replaced „nasze” with „nasz”. 
Hope this helps :)
Cheers,
Rafal
=> [PL] Minor typo in polish translation

pt/lessons/specifics/mnesia.md
=> [pt] update specifics -> mnesia

pl/lessons/basics/strings.md
Hi All,
I committed two changes:
1. Replaced `bajty` with `bajtach`
2. Added a colon `,`
Cheers,
Rafal
=> [PL] Minor changes in strings.md

pt/lessons/advanced/escripts.md, pt/lessons/advanced/umbrella-projects.md
=> [pt] update umbrella projects 

tr/lessons/basics/comprehensions.md, tr/lessons/basics/documentation.md, tr/lessons/basics/functions.md, tr/lessons/basics/iex-helpers.md, tr/lessons/basics/mix.md, tr/lessons/basics/modules.md, tr/lessons/basics/pipe-operator.md, tr/lessons/basics/sigils.md
=> [TR] Turkish language translations.

tw/lessons/advanced/behaviours.md, tw/lessons/advanced/concurrency.md, tw/lessons/advanced/erlang.md, tw/lessons/advanced/error-handling.md, tw/lessons/advanced/escripts.md, tw/lessons/advanced/gen-stage.md, tw/lessons/advanced/metaprogramming.md, tw/lessons/advanced/otp-concurrency.md, tw/lessons/advanced/otp-supervisors.md, tw/lessons/advanced/protocols.md, tw/lessons/advanced/typespec.md, tw/lessons/advanced/umbrella-projects.md
@doomspork @cizixs 
This is Initial Traditional Chinese advanced lessons Translation from 1.erlang to 12.protocols.
Happy Tomb Sweeping Day 😄
=> [TW] Translate /advanced lessons from 1.erlang to 12.protocols

pt/lessons/advanced/concurrency.md
=> [PT] - Concurrency

es/lessons/basics/collections.md
This replaces #1084, bringing the lesson up to date.
/cc @elixirschool/spanish @edwinallenz
=> [ES] Update COLLECTIONS to 1.2.1

en/lessons/basics/pattern-matching.md
As discussed in https://github.com/elixirschool/elixirschool/issues/1368#issuecomment-383207814
=> [EN] Bump version for changes in #1367

en/lessons/basics/collections.md
=> [EN] Mention that O(n) means "linear time"

tr/lessons/advanced/behaviours.md, tr/lessons/basics/basics.md, tr/lessons/basics/comprehensions.md, tr/lessons/basics/documentation.md, tr/lessons/basics/enum.md, tr/lessons/basics/functions.md, tr/lessons/basics/iex-helpers.md, tr/lessons/basics/mix-tasks.md, tr/lessons/basics/mix.md, tr/lessons/basics/modules.md, tr/lessons/basics/pipe-operator.md, tr/lessons/basics/sigils.md, tr/lessons/basics/strings.md, tr/lessons/basics/testing.md
It does what #1398 tried to do.
/cc @yasinyaman
=> [tr] Remove redirect_from directive

es/lessons/basics/collections.md
The comment about linear time introduced in fecd806, was already included in v1.2.1
=> [es] Collections: bump to v1.2.2

_includes/share-icons.html
A small subset of changes from #1362 was reverted by recent updates. This PR returns them back.
=> Reintroduce improvements to the share buttons from #1362

_assets/stylesheets/main.scss
=> Improve code block styles

_config.yml, _data/contributors.yml, _data/interlang.yml, _data/locales/ar.yml, _data/locales/bg.yml, _data/locales/bn.yml, _data/locales/cn.yml, _data/locales/de.yml, _data/locales/en.yml, _data/locales/es.yml, _data/locales/fr.yml, _data/locales/gr.yml, _data/locales/id.yml, _data/locales/it.yml, _data/locales/ja.yml, _data/locales/ko.yml, _data/locales/ms.yml, _data/locales/no.yml, _data/locales/pl.yml, _data/locales/pt.yml, _data/locales/ru.yml, _data/locales/sk.yml, _data/locales/ta.yml, _data/locales/th.yml, _data/locales/tr.yml, _data/locales/tw.yml, _data/locales/uk.yml, _data/locales/vi.yml, _includes/section-sidebar-menu.html, contributors.html
Closes #1414 
This still needs some CSS lovin'
=> Create a page dedicated to contributors

_includes/report.html, _plugins/elixir_school/translation_report.rb
One might argue on the points given, please discuss.
=> percentage shown in translation report heading

en/lessons/specifics/debugging.md, ko/lessons/specifics/debugging.md, pt/lessons/specifics/debugging.md, ru/lessons/specifics/debugging.md
=> fix acronym

_data/locales/uk.yml
I've noticed there are some Ukrainian parts not currently updated. :)
Updating.
Hey, @doroshenkoss , could you review this? It would be awesome.
Thanks!
=> [UK] Translate global definitions

pt/index.md
Translate home section to portuguese
=> [PT] Translation: home

pt/lessons/libraries/poolboy.md
Update the portuguese translation of the lesson libraries/poolboy.
=> [PT] Translation: libraries/poolboy

pt/lessons/specifics/ecto.md
Translate section specifics/ecto to portuguese.
=> [PT] Translation: specifics/ecto

_includes/report.html, _plugins/elixir_school/translation_report.rb
=> Translate version severity captions in translation report

en/lessons/basics/functions.md
We have this issue from 2016 #798 which actually mentioned this part of content.
@doomspork Could you look through it as a native speaker? I think the wording is a bit off, but I can't word it the proper way. 
Thanks!
=> Add pattern matching ordering note/example

de/lessons/advanced/otp-concurrency.md, id/lessons/advanced/otp-concurrency.md, pt/lessons/advanced/otp-concurrency.md, vi/lessons/advanced/otp-concurrency.md, zh-hans/lessons/advanced/otp-concurrency.md
=> Remove GenEvent references

_posts/2018-07-17-configuration-demystified.md
A new blog post that seeks to clear up some confusion around configuration in Elixir.
Feedback — I want it!
=> A look at Elixir configuration

_assets/stylesheets/libs/_vars.scss
#1429 
Darken up the fg color for increasing the legibility
=> Increase fg font contrast (#1429)

_posts/2018-06-18-composing-queries-with-ecto, _posts/2018-07-25-ecto-query-composition
This is still in-progress but early feedback always welcome.
=> Dynamic query composition with Ecto

pt/lessons/basics/enum.md
This PR is for #1350, which PR is #1349.
=> [PT] Add filter/2 to Enum lesson

en/lessons/specifics/ecto.md
As mentioned in #1481, Ecto cast arity changes in recent releases. 
I updated the examples and the description of the process.
=> Update Ecto lesson with cast/3

en/lessons/basics/collections.md, en/lessons/basics/enum.md, en/lessons/basics/functions.md, en/lessons/basics/pattern-matching.md, pt/lessons/basics/collections.md, pt/lessons/basics/enum.md, pt/lessons/basics/functions.md, pt/lessons/basics/pattern-matching.md
Update some lessons translations and include some `[EN]` lessons gardening:
=> [PT] Update lesson translations

en/lessons/specifics/mnesia.md, zh-hans/lessons/specifics/mnesia.md
=> [zh-hans] Mnesia lesson translation

pt/lessons/basics/mix-tasks.md
Update basic/mix-tasks portuguese translation.
=> [PT] Translation: basic/mix-tasks

pt/lessons/basics/documentation.md
Update basics/documentation portuguese translation.
=> [PT] Translation: basics/documentation

pt/lessons/basics/modules.md
Update basics/modules portuguese translation.
=> [PT] Translation: basics/modules

pt/lessons/basics/sigils.md
Update basics/sigils portuguese translation.
=> [PT] Translation: basics/sigils

pt/lessons/advanced/concurrency.md
Update basics/concurrency portuguese translation.
=> [PT] Translation: basics/concurrency

pt/lessons/basics/sigils.md
The translation was updated on #1531 but I forgot to update the version number.
=> [PT] Translation: basics/sigils version

en/lessons/libraries/benchee.md
fixing minor spelling error of `measurement`
=> minor spelling fix

_assets/stylesheets/main.scss, _includes/function-getContributor, _includes/section-author.html, _includes/section-prevnext.html, _includes/section-related.html, _layouts/post.html
- added previous and next section to blog posts - this change should help with engagement
- added author section to blog posts - this change incentivizes authors to create articles for exposure (and backlinks)
=> Some additions to the blog

_assets/javascripts/js.cookie.js, _assets/javascripts/main.js, _assets/stylesheets/dark.scss, _assets/stylesheets/libs/_functions.scss, _assets/stylesheets/libs/_vars.scss, _assets/stylesheets/main.scss, _includes/_head.html, _includes/_sidebar.html, _layouts/default.html
- Dark theme that inverts most colors, and softens the rest.
- Toggle theme at bottom of sidebar.
- Theme will persist if back button is used.
- Does not require page refresh.
=> Dark theme

ru/lessons/basics/collections.md
Corresponding changes to the original lesson can be found [here](https://github.com/elixirschool/elixirschool/commit/edabc9f49333c7bf40a6122d1a668729c371c6de#diff-b3426fa1a5d5f33d135e807f7be06ac8).
=> [RU] Update `basics/collections` to 1.2.3

en/lessons/libraries/benchee.md
Actually, I'm not even sure whether this should bump version. Nothing changed content-wise, but removed obsolete whitespaces, reworded some parts.
=> Proofread Benchee lesson

_posts/2018-10-23-umbrellas-just-when-it-rains.md
Still an early draft but early feedback is best
=> New blog post on Umbrella applications

_data/contents.yml, en/lessons/basics/date-time.md
Hey guys, I've drafted the first version of the Date/Time lesson as was discussed in #1015 .
I definitely need some feedback on where to go to from here - there aren't many functions in the standard library, but this is a handy part of language, especially in context of learning.
=> Add Date/Time lesson

zh-hans/lessons/basics/date-time.md
To Reviewers: 
b826916 中包括了中英文的的 diff，可能更方便对照原文。
=> [zh-hans] Translate basics/date-time lesson

_assets/stylesheets/base/_typography.scss
=> [style] Make inline code padding smaller

tr/lessons/basics/collections.md
I laughed really hard while reading the translation, it's was like Google Translate :rofl:
=> [TR] Fix many typos & non add informations & wrong informations

pt/lessons/basics/date-time.md
Add basics/date-time translation.
=> [PT] add basics/date-time translation

_data/contributors.yml, _posts/2018-10-10-ecto-multi.md
As promised 😄 
I wasn't sure where to put the article, since this is a candidate for the new Ecto section (#1519) but I thought it will be awhile until all lessons are completed, so I added this as a post. Please let me know if that's okay.
Any ideas how to improve the content are also welcome; particularly the `excerpt` is bothering me a bit, it doesn't feel right (I've never been good at writing those), so ideas on this are also appreciated.
=> New post on Ecto.Multi

en/lessons/specifics/ecto.md, zh-hans/lessons/specifics/ecto.md
Sync the update introduced in d5ef30e47d0b120daa42441f35160a10c7ebcce7
=> [zh-hans] update ecto lesson

en/lessons/specifics/ecto.md
I noticed there's another plan to provide more detailed lessons for Ecto in https://github.com/elixirschool/elixirschool/issues/1519, but before we finish that, I think it's better to update the original ecto lesson so the reader can still follow along.
=> Update ecto lesson for Ecto 3

en/lessons/specifics/plug.md
=> update plug lesson for cowboy2 + plug_cowboy 2

ru/index.md
Hey @elixirschool/russian , could you take a look?
=> [RU] Bump index to 2.0.0

en/lessons/specifics/plug.md
- Use correct module name in title
- Fix formater
=> Small fixes to ErrorHandler PR

CONTRIBUTING.md
=> creating a new lesson contribution guide

_data/contents.yml, en/lessons/advanced/otp-distribution.md
=> OTP distribution lesson 

_posts/2018-11-29-jwt-auth-with-joken.md
for issue https://github.com/elixirschool/elixirschool/issues/1631
=> jwt auth with joken blog post

zh-hant/lessons/basics/collections.md, zh-hant/lessons/basics/strings.md, zh-hant/lessons/libraries/guardian.md
[Update]
basics/collections v1.2.4
basics/ strings v1.2.0
[Translate]
libraries/guardian
=> [zh-hant] Update basics/collections and strings & Translate libraries/guardian

en/lessons/specifics/plug.md
1. Make the code of `Example.Application` module consistent
2. Make the links clickable
3. Fix `Example.RouterTest` for the GET request change introduced in #1617
=> Small fixes for the plug lesson

en/lessons/basics/basics.md
Very small grammar and spacing fixes 😊
=> Small fix for english basics lesson

es/lessons/basics/date-time.md
I've also made a translation of the date-time chapter without noticing there was already one waiting. No hard feelings if this is closed right away, but I think this addresses the comments to the other PR.
=> [ES] Translated basics/date-time chapter

_data/contributors.yml, _posts/2018-12-12-til-capture-log-in-exunit-tests.md
=> TIL about capturing logs in ExUnit tests

_data/contributors.yml, _posts/2018-12-26-til-how-to-run-ecto-migrations-in-production.md
closes #1659 
- adds TIL post
- updates contributors file
cc @SophieDeBenedetto @doomspork
=> TIL how to run ecto migrations on production

ja/lessons/basics/functions.md
I translated basics/functions section. 
Please review this PR 😀 @elixirschool/japanese
This includes the following changes:
- [add parens to function call](https://github.com/elixirschool/elixirschool/commit/a6d86ef644743c69312b8a6c0fa1fd7106662cd5#diff-2d05009f52e8df830b94b85988411e79)
- [Add pattern matching ordering note/example](https://github.com/elixirschool/elixirschool/commit/c3a65c9ed6a23560fb3ac49b132249b0e8e78328#diff-2d05009f52e8df830b94b85988411e79)
- [Add section on functions and pattern matching.](https://github.com/elixirschool/elixirschool/commit/353e7b2622f6015383b63504b833299b21c57a12#diff-2d05009f52e8df830b94b85988411e79)
- [Newline all sentences](https://github.com/elixirschool/elixirschool/commit/8a8f948636d464505a47856cd05728504fe30d78#diff-2d05009f52e8df830b94b85988 …
=> [JA] Bump up basics/functions to 1.2.0

_data/contents.yml, en/lessons/ecto/querying.md
I'm thinking this lesson should be geared towards "querying basics" and then we can do a separate lesson on writing more complex queries, taking a closer look at joins etc. I definitely hesitated on how much detail to add here so would love some feedback on that in particular.
=> Ecto: querying basics

ja/lessons/ecto/basics.md
I translated ecto/basics section and bump up to 2.1.0.
Since the former Ecto page has been divided into individual pages, I'll translate the rest of Ecto pages later :D
=> [JA] Translate ecto/basics

_data/contents.yml, en/lessons/libraries/distillery.md
=> add distillery to lessons

en/lessons/libraries/distillery.md
Saw couple of errors on spelling. Doing it from cellphone but hopefully everything is correct
=> fix spelling errors on distillery lesson

en/lessons/basics/functions.md
Greeter4 is not defined in this lesson and results which are returned match results from Greeter2
=> Typo in module name

en/lessons/basics/mix.md
This is my output what mix creates right now
```
mix new example
* creating README.md
* creating .formatter.exs
* creating .gitignore
* creating mix.exs
* creating config
* creating config/config.exs
* creating lib
* creating lib/example.ex
* creating test
* creating test/test_helper.exs
* creating test/example_test.exs
Your Mix project was created successfully.
You can use "mix" to compile it, test it, and more:
cd example
mix test
Run "mix help" for more commands.
```
mix --version
Erlang/OTP 21 [erts-10.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Mix 1.8.0 (compiled with Erlang/OTP 21)
=> mix new creates 1 more extra file now

zh-hant/lessons/basics/functions.md
This PR is going to update basics/functions to version 1.2.0.
Major changes will be adding newline and Functions and Pattern Matching sections.
Happy New Year 2019 🎉
#1669 [zh-hant] update basics/functions
I close the issue by myself because I think no need to open an issue with updating.
=> [zh-hant] update basics/functions (#1669)

_posts/2019-01-25-building-apps-with-plug-router.md
The sample app can be found @ https://github.com/elixirschool/router_example
=> A tutorial for building web apps with Plug.Router

_posts/2019-02-06-til-send-after.md
I thought I'd put together a short TIL post on `Process.send_after/4`. I demonstrated this to some folks and they were unfamiliar with this feature.
=> TIL about `Process.send_after/4`

en/lessons/ecto/associations.md
Please review the following fixes 😀
- Fix the incorrect `Ecto/Basics` link
- Fix typo
=> Fix Ecto/Associations issues

it/index.md, it/lessons/basics/basics.md, it/lessons/basics/collections.md, it/lessons/basics/control-structures.md, it/lessons/basics/enum.md, it/lessons/basics/pattern-matching.md
lessons updated:
- index.md
and
- lessons/basics/basics.md
- lessons/basics/collections.md
- lessons/basics/control-structures.md
- lessons/basics/enum.md
- lessons/basics/pattern-matching.md
=> Italian translations for lessons in the basics section

_posts/2019-02-12-putting-a-plug-app-on-heroku.md
This is a WIP, definitely want to review and walk through the steps again to ensure it all works copy-paste etc. Just wanted to get discussion started!
=> Plug & Heroku Deployment Post

_posts/2019-02-12-putting-a-plug-app-on-heroku.md
Self-explanatory. Excerpt is ```Want to put your app in the real world? Today we do it with Heroku!```
=> Add excerpt to plug.router Heroku deployment post

_posts/2019-02-21-supervisor-strategies.md
This goes a bit more hands-on than the normal lesson with a simple demonstration.
I put a repo for the app that coincides [here](https://github.com/notactuallypagemcconnell/supervisor_example) and am happy to transfer it to the org or wherever is best if we accept this post.
Going to give it a readover and add some more notes.
[Here](https://www.youtube.com/watch?v=lUlvOf8tju8) is a youtube video that I did that goes over these in ~3 minutes, disregard my inability to pronounce words and typos etc but it might offer some good context for anyone reviewing.
=> New Blog Post: Supervisory Strategies

es/lessons/basics/basics.md
=> [es] Update basic lesson to v1.2.1

zh-hant/index.md, zh-hant/lessons/advanced/typespec.md, zh-hant/lessons/basics/basics.md, zh-hant/lessons/basics/collections.md, zh-hant/lessons/basics/documentation.md, zh-hant/lessons/basics/modules.md, zh-hant/lessons/ecto/basics.md, zh-hant/lessons/specifics/mnesia.md, zh-hant/lessons/specifics/plug.md
This PR is going to update all translation to reach latest version.
Newline to sentences and match EN Line Number will be major changes which includes following files.
- index.md
- basics/basics
- basics/collections
- basics/documentation
- basics/modules
- advanced/typespec
- specifics/mnesia
- specifics/plug
Retranslation, over 90% lines are difference.
- ecto/basics
Happy Chinese New Year and Greetings from Taipei & Seoul :tada:
=> [zh-hant] Update multiple lessons to latest Version

404.html, _assets/stylesheets/components/_errors.scss, _assets/stylesheets/main.scss, _plugins/elixir_school/generator.rb
=> Add 404 error page

es/lessons/basics/enum.md
=> [ES] Update enum to v1.4.0

en/lessons/libraries/distillery.md
I fixed typo and removed a redundant sentence.
Please review this PR!
=> Fix Distillery

en/lessons/libraries/stream-data.md
I think I'm _finally_ done with this article :tada: I'd welcome feedback.
=> Add StreamData lesson

_posts/2018-03-18-phoenix-live-view.md
=> fix html snippet formatting

_posts/2018-03-18-phoenix-live-view.md
=> Add a new line after the youtube video iframe of LiveView blog

es/lessons/basics/pipe-operator.md
Update the basic/pipe-operator.md document to latest version
=> [ES] Update the basic/pipe-operator.md document to v1.0.1

es/lessons/basics/functions.md
Update basic/functions.md document to latest version
=> [ES] Update the basic/functions.md document to v1.2.0

es/lessons/basics/sigils.md
Updated the `basic/sigils.md` document to latest version
=> [ES] Update the basic/sigils.md document to v1.0.2

es/lessons/basics/documentation.md
Updated the `basic/documentation.md` document to latest version
=> [ES] Update the basic/documentation.md document to v1.0.3

es/lessons/basics/testing.md
Updated the `basic/testing.md` document to latest version
=> [ES] Update the basic/testing.md document to v1.1.1

es/lessons/basics/modules.md
Updated the `basic/modules.md` document to latest version
=> [ES] Update the basic/modules.md document to v1.4.0

en/lessons/ecto/associations.md, pt/lessons/ecto/associations.md
=> Fix typo in ecto doc

en/lessons/ecto/basics.md
=> Add instruction to use iex -S mix command

_posts/2019-03-18-phoenix-live-view.md
=> Fix LiveView post 

zh-hant/lessons/basics/date-time.md, zh-hant/lessons/basics/mix-tasks.md, zh-hant/lessons/basics/sigils.md, zh-hant/lessons/ecto/basics.md, zh-hant/lessons/libraries/guardian.md
This PR is going to update all translations to reach latest version.
Newline to sentences and match EN Line Number will be major change which includes following files.
- basics/mix-tasks
- basics/sigils
- ecto/basics
- libraries/guardian
New Translation.
- basics/date-time
=> [zh-hant] Update lessons && Translate basics/date-time

_includes/share-icons.html
Do you think is it better to hide the counter?
=> Add GitHub star button

ja/lessons/basics/basics.md
Added translation for basics/basics.
=> [JA] Translate Basics/Basics

en/lessons/libraries/guardian.md
Small typo correction (missing #)
=> fix comment not commented out

_includes/_head.html
According to https://support.google.com/webmasters/answer/139066?hl=en
=> Add link rel canonical

.github/CODEOWNERS, _posts/2019-03-18-phoenix-live-view.md
See https://help.github.com/en/articles/about-code-owners
Inspired by [Ruby team](https://github.com/ruby/www.ruby-lang.org/blob/master/.github/CODEOWNERS) 💎
=> Add CODEOWNERS to enable auto assignment reviews

.github/CODEOWNERS
=> Fix Chinese teams in CODEOWNERS file

en/lessons/basics/mix.md
While the wording in the current version of Mix lesson is a thing of art, I believe we're missing some crucial details here.
=> Rephrase Mix lesson details, bump to 1.1.0

bn/lessons/basics/modules.md, de/lessons/basics/modules.md, en/lessons/basics/modules.md, es/lessons/basics/modules.md, fr/lessons/basics/modules.md, gr/lessons/basics/modules.md, id/lessons/basics/modules.md, it/lessons/basics/modules.md, ja/lessons/basics/modules.md, ko/lessons/basics/modules.md, ms/lessons/basics/modules.md, no/lessons/basics/modules.md, pl/lessons/basics/modules.md, pt/lessons/basics/modules.md, ru/lessons/basics/modules.md, sk/lessons/basics/modules.md, tr/lessons/basics/modules.md, uk/lessons/basics/modules.md, vi/lessons/basics/modules.md, zh-hans/lessons/basics/modules.md, zh-hant/lessons/basics/modules.md
the codes of creation of the structs were like comments
=> Fixing some commentaries that were meant to be code

zh-hans/lessons/advanced/otp-distribution.md
=> [zh-Hans]fix typo

en/lessons/basics/sigils.md
I think that using data which can not be changed is not clearly explain ideas of described rules. When we using a function for describing interpolation it is a good idea to use data that can be changed when that function was implemented. 
I offer a clearer explanation in the form of an improvement in the example used.
=> Provide more useful exampels

en/lessons/basics/sigils.md
Was reading this page, and I noticed a missing word :)
=> Missing word

ja/lessons/basics/modules.md
I translated `lessons/basics/modules` section!
=> [JA] Translate lessons/basics/modules

_data/contributors.yml
I'll continue translate japanese on this repository.
https://github.com/elixirschool/elixirschool/pull/1870
So, I'd like to add contributors on this repository.
=> add starfish719 to contributors

en/lessons/basics/mix.md, en/lessons/basics/modules.md, en/lessons/basics/pipe-operator.md, it/lessons/basics/mix.md, it/lessons/basics/modules.md, it/lessons/basics/pipe-operator.md
Lessons updated:
- basics/pipe-operator.md
- basics/modules.md
- basics/mix.md
=> [it] update translations of multiple basics lessons

_posts/2019-03-25-til-ecto-validations-and-constraints.md
[`validate_require/3`] should be [`validate_required/3`]
=> Just fixed a very small typo

ja/index.md
=> [JA] Translate home 2.0.0

zh-hant/lessons/advanced/otp-distribution.md
- Translate advanced/otp-distribution
=> [zh-hant] Translation of advanced/otp-distribution

zh-hant/lessons/ecto/changesets.md
=> [zh-hant] Translation of ecto/changesets

zh-hant/lessons/ecto/associations.md
=> [zh-hant] Translation of ecto/associations

_data/contents.yml, en/lessons/advanced/nerves.md
It's been a while after we discussed it in #1574 , but I finally managed to finish it!
Feel free to provide feedback, looking forward to merging this!
And if someone could test it out a few times - it would be great.
I also have a Git repo with the step-by-step project execution - where should I put it?
=> Add Nerves lesson

zh-hans/lessons/advanced/nerves.md
Appreciated for suggestions, thanks @zillou, @zhulinpinyu
=> [zh-hans] Translate nerves 1.0.0 

en/lessons/specifics/ets.md
=> Correct ETS lesson

ko/lessons/libraries/guardian.md
=> [ko] Update guardian.md

zh-hant/lessons/advanced/nerves.md
=> [zh-hant] Translate advanced/nerves

zh-hant/lessons/ecto/querying.md
=> [zh-hant] Translation of ecto/querying

en/lessons/ecto/basics.md
+ [x] fixes issue described in: https://github.com/elixirschool/elixirschool/issues/1908
=> Rename Example.Repo to Friends.Repo for clarity

ja/lessons/basics/enum.md
ref #1912 
cc @tsubasakat I realized that linking is better than worrying about words.
=> [JA] Add link to term ordering

en/lessons/specifics/plug.md
=> Capitalize C in Mix.config

en/lessons/ecto/basics.md
Example -> Friends
Maybe, this pullrequest fix wasn't enough
https://github.com/elixirschool/elixirschool/commit/6eee4a0b293bd5ef98d026efc8cc2bb9b5bbb975#diff-a3d9528d5c48b91d7a98fe56337f1bb8
=> [EN] basics 2.3.0

pt/lessons/basics/mix-tasks.md
=> [pt-BR] Hightlight elixir code in pt/basics/mix-tasks.md

pt/lessons/ecto/associations.md
=> [pt] Fixes in pt/lessons/ecto/associations.md

_posts/2019-08-23-til-ecto-select-merge.md
=> add "TIL How to Select Merge with Ecto.Query" post

en/index.md
_getting in involved_ read a bit weird.
=> Fix getting involved

es/index.md
I've updated/translated from the latest english version
=> [ES] Updates es/index.md to 2.0.0 version

en/lessons/basics/date-time.md
Some textual improvements for the Date and Time chapter.
=> Textual improvements

es/lessons/advanced/erlang.md
=> [es] Update erlang lesson to v1.0.1

zh-hans/lessons/basics/enum.md
=> [zh-hans] Sync basics/enum lession

es/lessons/advanced/error-handling.md
=> [es] Update error-handling lesson to v1.0.1

_posts/2019-09-15-releasing-an-umbrella-app-with-docker-and-mix-release.md
Super rough draft! One big question that I outlined below and i still need to write a conclusion.
=> Releasing an umbrella app with mix release, config and docker

zh-hant/lessons/basics/enum.md, zh-hant/lessons/ecto/basics.md
Update the following lessons:
- ecto/basics
- basics/enum
=> [zh-hant] Update ecto/basics And basics/enum

en/lessons/basics/testing.md
Small improvement for the line where doctests are introduced.
=> Improve doctest line

fr/lessons/basics/collections.md
=> ajout d'une note ligne 168

bg/lessons/basics/mix-tasks.md, bn/lessons/basics/mix-tasks.md, de/lessons/basics/mix-tasks.md, en/lessons/basics/mix-tasks.md, es/lessons/basics/mix-tasks.md, fr/lessons/basics/mix-tasks.md, gr/lessons/basics/mix-tasks.md, id/lessons/basics/mix-tasks.md, ja/lessons/basics/mix-tasks.md, ko/lessons/basics/mix-tasks.md, no/lessons/basics/mix-tasks.md, pl/lessons/basics/mix-tasks.md, pt/lessons/basics/mix-tasks.md, ru/lessons/basics/mix-tasks.md, sk/lessons/basics/mix-tasks.md, tr/lessons/basics/mix-tasks.md, vi/lessons/basics/mix-tasks.md, zh-hans/lessons/basics/mix-tasks.md, zh-hant/lessons/basics/mix-tasks.md
=> Update phoenix.new to phx.new

en/lessons/ecto/changesets.md
update ecto changesets lesson to use Friends.Person module from ecto basics lesson - issue #1756
=> update ecto changesets lesson to use Friends.Person module from ecto basics lesson

ru/lessons/basics/collections.md
Corresponding changes to the original lesson can be found [here](https://github.com/elixirschool/elixirschool/commit/97a28cfe).
=> [RU] Update `basics/collections` to 1.3.0

de/lessons/advanced/typespec.md
Corresponding changes to the original lesson can be found [here](https://github.com/elixirschool/elixirschool/commit/29fe49b0).
=> [DE] Update `advanced/typespec` to 1.0.3

ko/lessons/basics/documentation.md, pt/lessons/basics/documentation.md, ru/lessons/basics/documentation.md, sk/lessons/basics/documentation.md, tr/lessons/basics/documentation.md
Corresponding changes to the original lesson can be found [here](https://github.com/elixirschool/elixirschool/commit/5e192274).
=> Update `basics/documentation` from 1.0.2 to 1.0.3

es/lessons/libraries/poolboy.md
This pull request adds a translation to spanish for the Poolboy lesson in the Libraries section
=> [es] Translate Libraries > Poolboy section

feed.xml
=> Remove extra slash from links in feed.xml

pt/lessons/advanced/typespec.md
Corresponding changes to the original lesson can be found [here](https://github.com/elixirschool/elixirschool/commit/29fe49b0).
=> [PT] Update `advanced/typespec` to 1.0.3

ja/lessons/basics/date-time.md
I translated `lessons/basics/date-time` section.
- bump version
https://github.com/elixirschool/elixirschool/commit/482398d61a27cd3dd26d39a5e68c9222becf9ced#diff-0d7fe8c56d01e42d4fe8ca8b73965a58
https://github.com/elixirschool/elixirschool/commit/8fbad8ea88f4dc692491f3df15c2d95928730f3c#diff-0d7fe8c56d01e42d4fe8ca8b73965a58
=> [JA] Translate date-time 1.0.2

_data/contributors.yml, es/lessons/libraries/distillery.md
This pull request adds a translation to spanish for the Distillery lesson in the Libraries section.
Corrections are really welcome since I'm not sure about the translation of certain concepts or words.
eg. deploy/deployment => desplegar/despliegue
or release task => tarea de release
Thanks in advance!
=> [es] Translate Libraries > Distillery section

es/lessons/advanced/umbrella-projects.md
This pull request adds a translation to spanish for the Umbrella Projects lesson in the Advanced section.
=> [es] Translate Advanced > Umbrella Projects lesson

de/lessons/basics/enum.md
=> [de] Update

pt/lessons/libraries/distillery.md
Add portuguese translation for the Distillery lesson.
=> [pt] Translate distillery lesson

es/lessons/advanced/protocols.md
This pull request adds a translation to spanish for the Protocols lesson in the Advanced section
=> [es] Translate Advanced > Protocols lesson

pt/lessons/basics/collections.md
- Add newlines
- Add new content
=> [PT] Update basics/collections (to 1.3.0)

en/lessons/libraries/stream-data.md
- Newline all the sentences to ease translation
---
Split from #2022.
cc @brain-geek 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elixirschool/elixirschool/2037)
=> [en] Update libraries/stream-data.md to 1.1.0

_posts/2019-10-23-building-admissions.md
I'm not yet finished with this post but it's rather long so I want to solicit feedback sooner than later. Any and all suggestions are welcome!
The mermaid diagrams *will not* render for you unless you install this Chrome plugin: https://chrome.google.com/webstore/detail/github-%20-mermaid/goiiopgdnkogdbjmncgedmgpoajilohe?hl=en
When I finish the article I will convert them to images.
=> Blog post: How and why we built Admissions

_posts/2018-07-17-configuration-demystified.md, _posts/2018-07-25-ecto-query-composition.md, _posts/2018-10-10-ecto-multi.md, _posts/2018-10-23-umbrellas-just-when-it-rains.md, _posts/2018-11-29-jwt-auth-with-joken.md, _posts/2018-12-12-til-capture-log-in-exunit-tests.md, _posts/2018-12-17-til-umbrella-app-child-app-tests.md, _posts/2019-01-25-building-apps-with-plug-router.md
Just some small changes. I want to continue going through and adding tags to more posts. Then we can improve our main blog page 🎉
=> Add tags and fix layout option

de/lessons/advanced/otp-supervisors.md
German translation matches the English version, so I also changed the version at the top of the file.
=> [de] Update otp-supervisors.md

uk/index.md
* Rewrite the text to correspond to English version
=> [UK] Update uk/lessons/index.md to 2.0.0

it/lessons/basics/control-structures.md
Update the Italian translation for the `basics/control-structures.md` file.
=> [it] Update control-structures.md

it/lessons/basics/mix.md
Update the Italian translation for the `basics/mix.md` file.
=> [it] Update mix.md

it/lessons/basics/enum.md
Update the Italian translation for the `basics/enum.md` file.
=> [it] Update enum.md

it/lessons/basics/collections.md
Update the Italian translation for the `basics/collections.md` file.
=> [it] Update collections.md

es/lessons/ecto/basics.md, es/lessons/ecto/querying.md
- Adds translation for lesson ecto/querying
- Fixes title markdown levels on ecto/basics
Closes #2119
=> [ES] Adding translation for Ecto/Querying

.typo-ci.yml
This should finish the setup for TypoCI which closes #2124
=> Add TypoCI to the project

zh-hant/lessons/basics/collections.md, zh-hant/lessons/basics/date-time.md, zh-hant/lessons/basics/enum.md, zh-hant/lessons/basics/testing.md, zh-hant/lessons/ecto/associations.md, zh-hant/lessons/ecto/basics.md, zh-hant/lessons/ecto/changesets.md, zh-hant/lessons/ecto/querying.md
This PR is going to update all translations to reach the latest version.
=> [zh-hant] Update basics && ecto lessons

pl/lessons/advanced/typespec.md
Corresponding changes to the original lesson can be found [here](https://github.com/elixirschool/elixirschool/commit/29fe49b0).
=> [PL] Update `advanced/typespec` to 1.0.3

zh-hant/lessons/libraries/poolboy.md
=> [zh-hant] Translation of libraries/poolboy

es/lessons/basics/basics.md
A couple of translation mistakes.
=> [ES] Update basics.md

ja/lessons/ecto/associations.md
I translated `lessons/ecto/associations` section.
https://github.com/elixirschool/elixirschool/commit/c2d32990d8db73349680d9cf6c0bc19dc2534509#diff-0ee6e943a638c449fe5ee3b42446f270
https://github.com/elixirschool/elixirschool/commit/a9d93d22de0a310611d019a8ffcc5f9cda303db6#diff-0ee6e943a638c449fe5ee3b42446f270
=> [JA] Translate associations 1.2.1

en/lessons/advanced/escripts.md
Thank you for sharing good knowledge.
I found easy mistakes.
If it looks no problem I can fix other languages as well, please let me know.
Thanks :)
=> [EN](all) Fix wrong language settings of code block

zh-hant/lessons/libraries/bypass.md
=> [zh-hant] Translation of libraries/bypass

ja/lessons/ecto/basics.md
I translated `lessons/ecto/basics` section.
refs: https://github.com/elixirschool/elixirschool/pull/2061
=> [JA] Translate basics 2.4.0

zh-hans/lessons/ecto/basics.md
English RP: https://github.com/elixirschool/elixirschool/pull/2061
=> [zh-hans] Update ecto/basics to 2.4.0 to reflect the ecto 3 changes

vi/lessons/advanced/typespec.md
Corresponding changes to the original lesson can be found [here](https://github.com/elixirschool/elixirschool/commit/29fe49b0).
=> [VI] Update `advanced/typespec` to 1.0.3

ru/lessons/ecto/associations.md
1.2.0: c2d32990d8db73349680d9cf6c0bc19dc2534509
1.2.1: n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elixirschool/elixirschool/2148)
=> [RU] Update ecto/associations.md to 1.2.1

en/lessons/basics/collections.md
As I understand, right now the approach is to have newline before each new sentence. I've noticed such inconsistency in one of lessons.
Please correct me if I'm wrong. 😄
=> Add missing newlines to collections lesson

en/lessons/basics/date-time.md
=> Add timezone operations paragraph to DateTime lesson

pt/lessons/advanced/gen-stage.md
Removing duplicated word from this sentence: "Como veremos, consumidores são implementados de de maneira muito semelhante"
=> [PT] Fix duplicated word

en/lessons/basics/date-time.md, zh-hans/lessons/basics/date-time.md
En PR: https://github.com/elixirschool/elixirschool/pull/2149
=> [zh-hans] Update DateTime lesson about timezone

ja/lessons/ecto/querying.md
I translated `lessons/ecto/querying` section.
Please review! @elixirschool/japanese 
I fixed output of IEx.
refs:
https://github.com/elixirschool/elixirschool/pull/2163
https://github.com/elixirschool/elixirschool/pull/2073/files#diff-42858e1c36d5073e0f1f6c9b1b86d979
=> [JA] querying fixed output of IEx

en/lessons/ecto/querying.md
I translated `lessons/ecto/querying` section.
Please review! @elixirschool/english 
I fixed output of IEx.
refs:
#2071
https://github.com/elixirschool/elixirschool/pull/2073/files#diff-42858e1c36d5073e0f1f6c9b1b86d979
=> [EN] querying fixed output of IEx

ja/lessons/basics/testing.md
I translated `lessons/basics/testing` section.
ref: https://github.com/elixirschool/elixirschool/pull/1973
=> [JA] Translate testing 1.2.0

ja/lessons/basics/sigils.md
I translated `lessons/basics/sigils` section.
refs:
https://github.com/elixirschool/elixirschool/commit/e9a8cd54f5118f4537a2393ea6fbabb992bc6f94#diff-039e98fb56464f2cb7c1b0b79e16b97a
https://github.com/elixirschool/elixirschool/commit/13c37484f611b3274b7ff8809d78ea9da2a42eb6#diff-039e98fb56464f2cb7c1b0b79e16b97a
https://github.com/elixirschool/elixirschool/commit/8b91cff11e64644ce47d69a593e47fa7291d0628#diff-039e98fb56464f2cb7c1b0b79e16b97a
https://github.com/elixirschool/elixirschool/commit/67c26a6f8eee7f1c8251aff5b35f3b4f2eab6093#diff-039e98fb56464f2cb7c1b0b79e16b97a
=> [JA] Translate sigils 1.0.2

ja/lessons/advanced/escripts.md
I translated `lessons/advanced/escripts` section.
ref: https://github.com/elixirschool/elixirschool/pull/2137
=> [JA] Translate escripts 1.0.2

en/lessons/ecto/associations.md
=> Correct typo in associations.md

en/lessons/libraries/poolboy.md, es/lessons/libraries/poolboy.md, gr/lessons/libraries/poolboy.md, ja/lessons/libraries/poolboy.md, ko/lessons/libraries/poolboy.md, pt/lessons/libraries/poolboy.md, ru/lessons/libraries/poolboy.md, vi/lessons/libraries/poolboy.md, zh-hans/lessons/libraries/poolboy.md, zh-hant/lessons/libraries/poolboy.md
I went ahead and applied https://github.com/elixirschool/elixirschool/pull/2176 to all of the available lessons. I also changed the version from 1.1.3 to 1.2.0 since this was more than just a language specific tweak.
=> Update all Poolboy lessons to the latest

_config.yml
PR #2185 reminded me that we have not updated these values in some time and they should reflect the latest.
=> Update Elixir and ERTS versions

zh-hans/lessons/basics/sigils.md
=> [zh-hans] Update for Elixir 1.9.0 ~U sigil

pt/lessons/advanced/typespec.md
Fix typo and some mistakes in Brazilian Portuguese.
I decided to translate some words in Portuguese instead of staying in English for more sense and understanding and improve some phrases too.
=> [PT] Fix typo and some mistakes in Brazilian Portuguese on pt/lessons/advanced/typespec.md

ja/lessons/ecto/associations.md
I fixed sample code for "Belongs To/Has One".
=> [JA] Fix sample code for "Belongs To/Has One"

pt/lessons/advanced/typespec.md, pt/lessons/basics/documentation.md
fix some mistakes when translated it from English to Portuguese, some translations not good enough for understanding.
=> [PT] fix some mistakes on translated it from English to Portuguese

fr/lessons/basics/collections.md
Updating french text for basics/collections section.
Issue: https://github.com/elixirschool/elixirschool/issues/2202
=> Update french version of basics/collections

en/lessons/advanced/umbrella-projects.md
Looks like a littly typo here with the return of `Datasets.hello/0`. Could change the function to return `:world`, but I like the IO message more :)
=> match iex return to Datasets' function's return

_posts/2018-12-26-til-how-to-run-ecto-migrations-in-production.md
This PR fixes a broken link on the post about migrations in production.
=> Fix broken link

fr/lessons/basics/enum.md
Updating french text for basics/enum section.
Issue: https://github.com/elixirschool/elixirschool/issues/2207
=> Update french version of basics/enum

fr/lessons/basics/basics.md
Updating french text for basics/basics section.
Issue: https://github.com/elixirschool/elixirschool/issues/2200
=> Update french version of basics/basics

es/lessons/ecto/associations.md, es/lessons/ecto/querying.md, gr/lessons/ecto/basics.md, id/lessons/ecto/basics.md, ja/lessons/ecto/associations.md, ja/lessons/ecto/querying.md, ko/lessons/ecto/basics.md, pl/lessons/ecto/basics.md, pt/lessons/ecto/associations.md, pt/lessons/ecto/querying.md, ru/lessons/ecto/associations.md, ru/lessons/ecto/basics.md, ru/lessons/ecto/querying.md, vi/lessons/ecto/basics.md, zh-hans/lessons/ecto/associations.md, zh-hans/lessons/ecto/querying.md, zh-hant/lessons/ecto/associations.md, zh-hant/lessons/ecto/querying.md
Applies #2228 to all impacted lessons.
=> Apply Example -> Friends change to all lessons

en/lessons/ecto/querying.md
I was typing out %Ecto.Query<from m in Example.Movie> because I didn't get that I only needed to type out the first two statements here.
=> Adding ie> prompt

en/lessons/advanced/error-handling.md
Based on text from @holsky 
Fixes #799
=> Improve error handling lesson

en/lessons/basics/documentation.md
=> Improve moduledoc example

en/lessons/specifics/debugging.md
Hey guys, could you review this?
Closes #1643 
@elixirschool/english
=> Add IEx section to debugging lesson

en/lessons/ecto/querying.md
In previous lessons the character inserted is "Wade Watts" not "Video Game Guy", so these queries don't return any results.
=> Updating character selection

es/lessons/ecto/querying.md, ja/lessons/ecto/querying.md, pt/lessons/ecto/querying.md, ru/lessons/ecto/querying.md, zh-hans/lessons/ecto/querying.md, zh-hant/lessons/ecto/querying.md
Applies #2233 across all translations applicable. @tajchumber
=> Update lessons for consistency

pt/lessons/basics/mix.md
It fixes a mistyped word in 5th paragraph of the "Managing Dependencies" section.
=> [pt] Fix a mistyped word

pt/lessons/basics/testing.md
Gramática errada da palavra mensagens.
=> [pt] Update testing.md

pl/lessons/advanced/concurrency.md
This fixes a typo in a Concurrency lesson
=> [PL] Fixed a typo

zh-hant/lessons/basics/collections.md
* Align contents with new version
* Make sentence and terms with verbal usage and conventions
=> [zh-hant] Update Basic/Collections

zh-hant/lessons/libraries/benchee.md
- Translation of [libraries/benchee](https://elixirschool.com/en/lessons/libraries/benchee/)
=> [zh-hant] Translate libraries/benchee

_data/contributors.yml, ru/lessons/basics/iex-helpers.md
Iex-helpers article is translated to Russian
@brain-geek can you help to review?
=> [RU] Translate Iex-helpers 1.0.2

pt/lessons/ecto/associations.md
I don't know why the link not works correctly for the Basics of the elixir school so I put the link directly.
=> The link not work's it complains a 404 error.

en/lessons/specifics/debugging.md
Hopefully this correction is still accurate. The sentence was just too tough to get through, so I felt compelled to offer up this suggestion.
=> Helping sentence flow

pt/lessons/ecto/basics.md
I updated the iex output.
And was need to put the match for `person =  %Friends.Person{...}`
for after call the ´person.name` and others
=> Update the iex output

pt/lessons/basics/iex-helpers.md
update iex helpers version and change the word for doing more clear sentence
=> [pt] update iex helpers version

pt/lessons/advanced/concurrency.md
- add parentheses
- define underscore prefix in some assigned variables are don't use
- update Task example
=> [pt] fix minor details

fr/index.md
Hello! Just fixing a few typos I spotted in `index.md`.
Issue - https://github.com/elixirschool/elixirschool/issues/2257
=> [FR] Update index.md

pt/lessons/specifics/mnesia.md
=> forget the do on case

ja/lessons/basics/documentation.md, ja/lessons/ecto/basics.md
Cf. https://github.com/elixirschool/elixirschool/pull/2287
=> [JA] Update syntax highlighting for consistency

es/lessons/basics/collections.md
Updated the basics/collections lesson to match the english 1.3.1 version.
=> [es] Updated basics/collections lesson.

es/lessons/basics/date-time.md
Updated basics/date-time lesson to match english version 1.1.0
=> [ES] Updated basics/date-time.

pt/lessons/basics/documentation.md
- bump version.
- add information on how can compile your module on IEx console.
- add a note about load the entire mix project on IEx console.
=> [pt] update documentation lesson

pt/lessons/advanced/gen-stage.md
- update the gen_stage version
- add a _initial variable on start_link function examples
- change the children list itens format
=> [pt] bump GenStage version

zh-hant/lessons/libraries/distillery.md
- Translation of [libraries/distillery](https://elixirschool.com/en/lessons/libraries/distillery/)
=> [zh-hant] Translate libraries/Distillery

zh-hant/lessons/libraries/stream-data.md
- Translation of libraries/stream-data
=> [zh-hant] Translate libraries/stream-data

en/lessons/libraries/distillery.md
=> Fixes for Distillery chapter

pt/lessons/basics/documentation.md
The word "since", in the context that it has been included, is better translated as "considerando" instead of "desde".
=> Adjust Portuguese translation

ja/lessons/basics/mix-tasks.md
I translated `lessons/basics/mix-tasks` section.
refs:
https://github.com/elixirschool/elixirschool/commit/86b4f4ed8b1229ea3d5f2988bfacd640a77c89f0
https://github.com/elixirschool/elixirschool/commit/f4d62f0ef9ef555e6ec85fdbae0a27e410d7d716#diff-ce81ef91d95296ee6fc601cb0c462f42
=> [JA] Translate mix-tasks 1.1.0

ja/lessons/ecto/associations.md
Try to merge #2349 
I'm not sure, but it seems travis CI do not trigger build with author who don't have write permission?
cc @doomspork
=> [JA] Fix method name in association.md

fr/lessons/basics/documentation.md
a new french traduction for lessons/basics/documentation.md taking into account the changes brought by the 1.1.0 version (the current french traduction is based on the version 1.0.3)
=> feat : fr_basics_documentation

.typo-ci.yml
=> Add portuguese dictionary to typo-ci

pt/lessons/advanced/erlang.md
=> [PT] Update Advanced/Erlang to 1.0.2

en/lessons/ecto/querying.md
I notice some incorrect things like the arity of the functions which they are using the number of arguments don't match. So I change.
And I propose some things..
I quit the  `alias Friends.Movie`and ` alias Friends.Repo` because we put in the beginning.
I added the `alias Friends.Character`when needs to use.
The part of using the macro with pipe I put the sample for using with the character `\`for line break.
And when uses the function first and last the correct name of the sample is "Tyler Sheridan" and not "Bob".
=> Updating some errors.

pt/lessons/basics/mix-tasks.md
=> [PT] Update Basic/Mix tasks

en/lessons/advanced/otp-distribution.md
Hi all 👋 
Just fixing a typo in the OTP distribution lesson 😊
=> [en] Fix typo in the OTP distribution lesson

pt/lessons/ecto/querying.md
Hi all 👋  
Following the instruction from [Issue #2395](https://github.com/elixirschool/elixirschool/issues/2395), I updated the Ecto Querying lesson in Portuguese.
Please, let me know if there're expressions or words that we normally don't translate. 
I added a suggestion with the English term for some cases (e.g. for bindings and bindingless).
Thank you all for your contribution and effort to maintain these lessons 💜
=> [pt] Updating Ecto/Querying lesson in Portuguese

pt/lessons/specifics/debugging.md
=> [pt] Update Debugging to 1.1.2

es/lessons/basics/collections.md
Correcciones de palabras incompletas y gramaticales (tildes).
=> [es] Update collections.md

ja/lessons/basics/mix.md
I translated `lessons/basics/mix` section.
Maybe, forgot bump version up.
refs:
https://github.com/elixirschool/elixirschool/commit/84706363c7e207997c4c442a16f4070b7f20a62a#diff-9a7600c780427e1cf724d5901498690e
https://github.com/elixirschool/elixirschool/commit/63565226e0ddda381088a9284b1762c8f1c560f8#diff-7f823f1e598cc2280e73fe1901ba6cbe
=> [JA] Translate mix 1.1.1

ja/lessons/ecto/querying.md
I translated `lessons/ecto/querying` section.
refs:
https://github.com/elixirschool/elixirschool/commit/94297cdc4036003a0f531d88b7743fb3a24d5430#diff-42858e1c36d5073e0f1f6c9b1b86d979
https://github.com/elixirschool/elixirschool/commit/ef3779b7d979e3519d51f7d9294f0106a82590a8#diff-42858e1c36d5073e0f1f6c9b1b86d979
https://github.com/elixirschool/elixirschool/commit/171a5df6aa039f0e2653563bb55dbb5eb1db1140#diff-42858e1c36d5073e0f1f6c9b1b86d979
https://github.com/elixirschool/elixirschool/commit/136eeead89c15deeb729d6a933926e1ffa6d113b#diff-42858e1c36d5073e0f1f6c9b1b86d979
https://github.com/elixirschool/elixirschool/commit/5ae47f0c1507165a4b4ec9efcaec9a7ef2aef493#diff-42858e1c36d5073e0f1f6c9b1b86d979
=> [JA] Translate querying 1.2.0

pt/lessons/ecto/associations.md
#2394 
Updates Ecto Associations to 1.2.1 :)
=>  [PT] Update lesson: Ecto Associations

gr/lessons/basics/iex-helpers.md
Bump iex-helpers.md to latest version.
=> [gr] Update iex-helpers.md

en/lessons/specifics/nerves.md
* Update output text to match what you currently seen when making a new
Nerves project
* Update networking configuration and links to refer to `vintage_net`.
The `vintage_net` library replaced `nerves_networking` earlier this
year.
* Update `nerves_init_gadget` references and links to `nerves_pack`
which is used by default now
* Link to the `vintage_net` cookbook for additional help with network
configuration.
* Update reference to `nerves_firmware_ssh` to `ssh_subsystem_fwup`
which replaced `nerves_firmware_ssh` as the default
=> Update Nerves section to reflect recent updates

pl/lessons/basics/enum.md
EN version: `1.6.1`
PL version: `1.3.0 ~> 1.6.1`
=> [PL] chore: Basic > Enum translation update based on EN language

_data/locales/pl.yml
**Changes**
* Added missing `interlang` config in `pl` language
=> [PL] fix: Add missing interlang in PL language

pl/lessons/basics/basics.md
EN version: `1.2.1`
PL version: `1.0.0 ~> 1.2.1`
=> [PL] chore: Basic > Basic translation update based on EN language

pl/lessons/basics/collections.md
EN version: `1.3.1`
PL version: `1.0.0 ~> 1.3.1`
=> [PL] chore: Basic > Collections translation update based on EN language

it/index.md
Fixes a few typos inside the italian language index.
=> [IT] fixes Italian language typos

en/lessons/specifics/nerves.md
=> line breaks

vi/index.md
Hello,
this is my first contribution to the repo.
I'm Vietnamese and have loved Elixir for quite a long time. Even not using it professionally, I always find its usage in my side / hobby project.
Hope I could help to bring this awesome project to more Vietnamese Alchemists..
=> [VI] Update index to 2.0

th/lessons/basics/sigils.md
Thai language version of **Basics** > **Sigils** lesson
=> [TH] New Translation: Sigils

pt/lessons/basics/enum.md
Updated lesson: Enum #2396.
Updated the version of the lesson from 1.5.0 to 1.6.1 in Portuguese.
=> [pt] updated enum lesson

pt/lessons/advanced/otp-distribution.md
Hi all 👋  - I finished the translation of the OTP distribution lesson to Portuguese. 
Please, let me know if there're some better terms or translations 💜 
This PR solves the [issue #2390](https://github.com/elixirschool/elixirschool/issues/2390)
=> [pt] Create a translation in Portuguese to OTP distribution lesson

pt/lessons/specifics/nerves.md
=> [PT] New translation: Nerves

_data/contributors.yml, en/lessons/libraries/nimble-publisher.md, es/lessons/libraries/nimble-publisher.md
I've made minor corrections in the NimblePublisher lesson, and translated it to Spanish.
=> [ES] Nimble publisher Spanish translation

zh-hans/lessons/basics/enum.md
add translation about capture operator(&)
=> update zh-hans basic enum.md to 1.6

ja/lessons/specifics/nerves.md
Hi!, it's nice to meet you.
I translated ja/lessons/specifics/nerves.md section.
=> [JA] Translate nerves 1.1.2

_posts/2019-05-06-live-view-with-presence.md
Thanks for the great post! 
I noticed a small issue in one of the examples showing what the data would look like after being transformed in `handle_info`.
=> Fixes example data in LiveView with Presence post

zh-hans/lessons/basics/enum.md
=>  [zh-hans] Update basic enum.md to 1.6.1

pt/lessons/advanced/otp-supervisors.md
🔧 Fix typo to pt/lessons/advanced/otp-supervisors.md
=> [PT] Fix typo: OTP Supervisors

zh-hans/lessons/advanced/otp-concurrency.md
update otp-concurrency context
=> [zh-hans] Update advanced otp-concurrency.md to 1.1.3

pt/lessons/libraries/mox.md
Closes #2391 
I'm Portuguese from Portugal and I did my best to translate it according to the rest of the website which seems, mostly, Portuguese from Brazil.
Some words I didn't translate because it didn't make sense to me to translate stuff like `third-party` or even the word `mocks`.
Let me know if something needs to be changed 😄 And thank you for letting me be part of this 💪
=> [PT] New translation: Mox

pt/lessons/advanced/otp-distribution.md, pt/lessons/basics/date-time.md, pt/lessons/basics/enum.md, pt/lessons/libraries/distillery.md, pt/lessons/libraries/guardian.md, pt/lessons/specifics/debugging.md
Some small updates to bring portugues lessons to latest version.
Updates based on the following diffs:
```shell
git diff 82bca01f0c775c6cb53ed8745233a542edf46bd8 HEAD en/lessons/basics/enum.md
git diff 80fb9dde4e17a84f0fcaabcba2cc14c0fa47e4b3 HEAD en/lessons/basics/date-time.md
git diff f19b9cc8c111ef32a7e87f13ef4c486df3988602 HEAD en/lessons/advanced/otp-distribution.md
git diff d98cddcc529549ac2b486c8989c1d608340c5e8c HEAD en/lessons/libraries/distillery.md
git diff a1cdedc1d38cb1f1d849a2a5372b7e852d940cd9 HEAD en/lessons/libraries/guardian.md
git diff 6535b6bc6ac57ffdbd0a52a52309545cd4ab1183 HEAD en/lessons/specifics/debugging.md
```
=> [PT] Update translation to new version

pt/lessons/libraries/nimble-publisher.md
- Adding translation of Nimble Publisher lesson to Portuguese: [#2540](https://github.com/elixirschool/elixirschool/issues/2540)
=> [PT] Adding translation of Nimble Publisher lesson to Portuguese

ja/lessons/basics/date-time.md
I translated `lessons/basics/date-time` section.
refs:
https://github.com/elixirschool/elixirschool/commit/ff6ca0303753a5aa54d20a27db13d00feacb72cb
=> [JA] Translate date-time 1.1.1

ja/lessons/advanced/erlang.md
I translated `lessons/advanced/erlang` section.
refs:
https://github.com/elixirschool/elixirschool/commit/4a49d927670511424ecbec9da6b48aff34c83c67#diff-6563092aac08167b8d1a812e2f9ef2d9b5f0da18530214a5690e47fcacc9b83d
=> [JA] Translate erlang 1.0.2

ja/lessons/basics/enum.md
I translated `lessons/basics/enum` section.
refs:
https://github.com/elixirschool/elixirschool/commit/fcce49992926918fe6d66a704e64fb8b686f6f08#diff-d68744d600065f29b5fcd00743e0eb2e51e24a4add88928191a7b136c5f9a3b5
https://github.com/elixirschool/elixirschool/commit/a0ee115aaa37a96c3f861b38ddc9cc6f63baa6c2#diff-d68744d600065f29b5fcd00743e0eb2e51e24a4add88928191a7b136c5f9a3b5
=> [JA] Translate enum 1.7.0

bg/lessons/basics/functions.md, bn/lessons/basics/functions.md, de/lessons/basics/functions.md, en/lessons/basics/functions.md, es/lessons/basics/functions.md, fr/lessons/basics/functions.md, gr/lessons/basics/functions.md, id/lessons/basics/functions.md, it/lessons/basics/functions.md, ja/lessons/basics/functions.md, ko/lessons/basics/functions.md, ms/lessons/basics/functions.md, pl/lessons/basics/functions.md, pt/lessons/basics/functions.md, ru/lessons/basics/functions.md, sk/lessons/basics/functions.md, ta/lessons/basics/functions.md, th/lessons/basics/functions.md, tr/lessons/basics/functions.md, uk/lessons/basics/functions.md, zh-hans/lessons/basics/functions.md, zh-hant/lessons/basics/functions.md
When I was running the commands in the "Functions" document, there was no return value listed.
So we fixed it.
https://elixirschool.com/en/lessons/basics/functions/
```
iex> some_result = 1
iex> handle_result.({:ok, some_result})
Handling result...
iex> hand
```
=> Add text of　returns the value （Functions)

en/lessons/libraries/poolboy.md
No longer the case, see https://github.com/elixir-ecto/db_connection/commit/98b23398afc6f8af8e21d598c9b31741ac9b8e6d
=> Remove reference to postgrex using poolboy

pt/lessons/ecto/basics.md
in this moment, default number is 0 and not 11
=> change default 11 to 0

pl/lessons/basics/functions.md
Updated Polish translation of lesson "Functions", including full translation of section "Functions and Pattern Matching".
=> [pl] Updated translation of lesson "Functions"

id/lessons/basics/enum.md
some sentences is not correct in bahasa
=> [id] correctness the sentences

zh-hans/lessons/ecto/basics.md
Otherwise it will not compile.
=> [zh-hans] Add the correct dependencie

pt/lessons/basics/basics.md
Closes https://github.com/elixirschool/elixirschool/issues/2596
=> [PT] Update lesson Basics/Basics -> 1.3.0

pt/lessons/ecto/associations.md
Closes https://github.com/elixirschool/elixirschool/issues/2598
=> [PT] Update lesson Ecto/Associations -> 1.2.2

ko/lessons/basics/documentation.md
```
git diff 5e1922748b64f77ebf82a87e8a70cf4e6e1ed7c7..235b2bb78dba48b4d901f4e1c7cc09c0ee8d3187  -- en/lessons/basics/documentation.md
```
https://github.com/elixirschool/elixirschool/compare/5e1922748b64f77ebf82a87e8a70cf4e6e1ed7c7...235b2bb78dba48b4d901f4e1c7cc09c0ee8d3187
(file changed -> en/lessons/basics/documentation.md)
=> [KO] Update translation: basics/documentation to 1.1.0

ko/lessons/basics/basics.md
👋 It's been a while.
```
git diff 1abd22e116ba3d6b16565637889011257e86658c..235b2bb78dba48b4d901f4e1c7cc09c0ee8d3187 en/lessons/basics/basics.md
```
https://github.com/elixirschool/elixirschool/compare/1abd22e116ba3d6b16565637889011257e86658c...235b2bb78dba48b4d901f4e1c7cc09c0ee8d3187
(file changed -> en/lessons/basics/basics.md)
=> [KO] Update translation: basics to 1.3.0

pt/lessons/specifics/nerves.md
Closes https://github.com/elixirschool/elixirschool/issues/2600
=> [PT] Update lesson Specifics/Nerves -> 1.1.2

fr/lessons/basics/mix.md
Closes https://github.com/elixirschool/elixirschool/issues/2592
=> [FR] Update lesson Basics/Mix

fr/lessons/basics/enum.md
Closes https://github.com/elixirschool/elixirschool/issues/2594
=> [FR] Update lesson Basics/Enum

conferences/2020-09-03-elixir-conf.md, conferences/2020-10-07-elixirconf-eu.md, conferences/2020-11-19-elixir-club.md, conferences/2020-11-28-elixir-brasil.md, conferences/2021-05-07-elixirconf-africa-2021.md, conferences/2021-05-28-alchemy-conf.md, conferences/2021-06-16-elixir-wizards.md, conferences/2021-09-09-elixirconf-eu-2021.md, conferences/2021-10-12-elixirconf-austin.md
Added an initial set of conferences to use on then school_house [`/conferences`](https://beta.elixirschool.com/conferences) page.
=> Add Initial Set of Conferences

.github/workflows/deploy_content.yml
See https://github.community/t/triggering-by-other-repository/16163 and https://github.com/elixirschool/school_house/pull/61
=> Trigger a deploy of the School House repo

pt/lessons/basics/documentation.md
I was reading a lesson and found a few weird phrases in the portuguese version of the Documentation lesson
=> [PT] Minor spelling and phrasing fixes

_posts/2021-07-14-elixir-book-club.md
Adds blog post announcing and describing the Elixir Book Club.
=> Blog: Elixir Book Club

en/lessons/basics/strings.md
`Pretty straight, right?` to ` Pretty straightforward, right?`.
=> Change a minor grammatical error.

pl/lessons/basics/mix-tasks.md
1. Updated Polish translation of lesson "Custom Mix Tasks".
2. Grammar and punctuation fixes.
=> [PL] Update translation of lesson "Custom Mix Tasks"

lessons/ko/basics/basics.md
Removed a merge conflict from this particular lesson file.
Affected page: https://beta.elixirschool.com/ko/basics/basics
=> Fix Merge Conflict in Lesson

pt/lessons/libraries/mox.md
I was reading and found this detail
=> Fixing a typo

es/lessons/specifics/mnesia.md
Fixes a bad anchor ID in content, detected by [Rocket Validator](https://rocketvalidator.com/s/6e6cb6ea-7db8-46a0-8392-5a9adcdbcee2/p/4724927/i?search=Bad+value+%E2%80%9C%23inicializaci%C3%B3n+de+datos+y+migraci%C3%B3n%E2%80%9D+for+attribute+%E2%80%9Chref%E2%80%9D+on+element+%E2%80%9Ca%E2%80%9D%3A+Illegal+character+in+fragment%3A+space+is+not+allowed.&non_doc=false)
=> Fix anchor ID link

zh-hans/lessons/basics/control-structures.md
add `with` expression  translation
=> [zh-hans] Add missing translation

_posts/2021-09-02-rocket-validator.md
It looks like missing indentation was causing trouble buiding the blog post.
=> Fix post metadata in latest blog post

en/lessons/libraries/benchee.md, pt/lessons/libraries/benchee.md
The benchee.md file headers are incorrectly sized.
=> [EN][PT] Fixed headers in benchee.md file 

lessons/pl/basics/comprehensions.md
Polish translation of lesson "Comprehensions" has been updated to match the newest English version.
=> [PL] Update translation: "Comprehensions"

lessons/es/misc/benchee.md
Translated the Benchee lesson to Spanish.
=> [ES] Miscellaneous Benchee

fr/lessons/basics/strings.md
Hello,
Translation for the strings lesson, in French. First time doing this so do not retain from asking me to modify things.
=> FR translation for basics/strings

.github/CODEOWNERS
Add the Bengali translation team as code owners for BN content
=> Add Bengali codeowners

GLOSSARY.md
Since multiple people are contributing to the Bengali translation of Elixir School contents, having a glossary would help in maintaining consistency.
=> [bn] glossary proposal

posts/2021-11-18-til-cleaner-queries-with-ecto-map.md, posts/2021-11-22-til-cleaner-queries-with-ecto-map.md
Hello there!
Sharing a TIL based on a discussion we had during a mentorship meeting.
Please advise of any needed changes.
=> Post: TIL Cleaner queries with Ecto map

lessons/zh-hans/basics/functions.md
=> [zh-hans] Remove an extra curly brace

posts/2021-11-09-now-with-more-elixir.md, posts/2021-12-01-now-with-more-elixir.md
Long overdue post about the new School House project powering the site today.
=> Post about the new Elixir based site

lessons/pt/testing/stream_data.md
Adds translation for StreamData lesson in brazilian portuguese :)
=> [PT] Add translation for lesson StreamData

lessons/pl/ecto/basics.md
Polish translation of lesson "Ecto: Basics" has been actually completely rewritten, previous version was totally outdated.
=> [PL] Update translation of lesson "Ecto: Basics"

lessons/ja/misc/nimble_publisher.md
Translated the nimble_publisher lessen into Japanese.
nimble_publisherのdocumentを日本語訳しました。
=> [JA] translate nimble_publisher v1.0.2

lessons/ja/testing/mox.md
=> [JA] add testing/mox v1.0.1

lessons/ja/misc/benchee.md
Added Japanese Benchee lesson.
=> [JA] add misc/benchee v2.0.0

lessons/de/basics/pipe_operator.md
=> Fix expression

lessons/es/basics/basics.md
Updated Spanish version of basics/basics.md to version 1.3.0
=> [ES] add basics/basics.md v1.3.0

lessons/es/basics/enum.md
Updated Spanish version of basics/enum.md to version 1.8.0
=> [ES] add basics/enum.md v1.8.0

lessons/es/basics/functions.md
Updated Spanish version of basics/functions.md to version 1.3.0
=> [ES] Update basics/functions.md to v1.3.0

lessons/en/ecto/associations.md
The data structure being passed in is a map not an `Actor` struct
=> Identification of data type error

lessons/en/basics/basics.md
I have just added "Sean" as the return on iex to:
iex> name = "Sean"
=> Pattern Matching should always return something on iex

lessons/en/advanced/otp_supervisors.md
=> fix capitalization typo

lessons/bg/basics/functions.md, lessons/bn/basics/functions.md, lessons/de/basics/functions.md, lessons/el/basics/functions.md, lessons/es/basics/functions.md, lessons/fr/basics/functions.md, lessons/id/basics/functions.md, lessons/it/basics/functions.md, lessons/ja/basics/functions.md, lessons/ko/basics/functions.md, lessons/ms/basics/functions.md, lessons/pl/basics/functions.md, lessons/pt/basics/functions.md, lessons/ru/basics/functions.md, lessons/sk/basics/functions.md, lessons/ta/basics/functions.md, lessons/th/basics/functions.md, lessons/tr/basics/functions.md, lessons/uk/basics/functions.md, lessons/vi/basics/functions.md, lessons/zh-hans/basics/functions.md, lessons/zh-hant/basics/functions.md
As commented at #2799, update examples in other languages.
@doomspork :)
=> Remove pipe operator before its intruduced

lessons/ko/advanced/otp_supervisors.md
=> [ko] update a translation of OTP Supervisor

lessons/zh-hans/testing/mox.md, lessons/zh-hant/basics/modules.md
Signed-off-by: cutecutecat <starkind1997@gmail.com>
=> [zh-hans] Add a translation for lesson Testing:Mox

lessons/en/advanced/otp_supervisors.md
=> OTP Supervisors: Make correction mentioning 0 as a valid time out + Fix Lists Indentation

lessons/pl/storage/ets.md
Updated Polish translation of lesson "Erlang Term Storage".
=> [PL] Update translation of "ETS"

lessons/pl/basics/functions.md
Polish translation of lesson "Functions" has been updated to reflect the changes from #2704.
=> [PL] Update translation of lesson "Functions"

lessons/pl/intermediate/mix_tasks.md
Title and excerpt of lesson "Mix tasks" have been updated to respect rules of the Polish language.
=> [PL] Update title & excerpt in "Mix tasks" lesson

lessons/pt/basics/enum.md
_Update Portuguese Enum Lesson with English translation version_
Based on: 
- https://github.com/elixirschool/elixirschool/pull/2766 - v1.9.0
- https://github.com/elixirschool/elixirschool/pull/2828 - v1.9.1
- https://github.com/elixirschool/elixirschool/pull/2764
=> [PT] Improve Heirarchy of Headings in Enum Lesson

lessons/pt/advanced/otp_supervisors.md
_Update Portuguese Supervisors with English translation version_
- Based on:
- https://github.com/elixirschool/elixirschool/pull/2798
=> [PT] Update translation for lesson Supervisors and Bump version to 1.1.2

lessons/pt/intermediate/mix_tasks.md
Update Portuguese Mix Tasks Lesson with English translation version
-  Custom Tasks
- https://github.com/elixirschool/elixirschool/pull/2838
=> [PT] Update translation for lesson Mix Tasks and Bump version to 1.3.0

lessons/pt/basics/date_time.md
_Update Portuguese Date and time Lesson with English translation version_
- Based on:
- https://github.com/elixirschool/elixirschool/pull/2736
- https://github.com/elixirschool/elixirschool/pull/2774
=> [PT] Update translation for lesson DateTime and Bump version to 1.2.0

lessons/pt/basics/functions.md
*Update Portuguese Functions Lesson with English translation version*
- Based on:
- https://github.com/elixirschool/elixirschool/pull/2704
=> [PT] Update functions.md and Bump version to 1.3.0

lessons/pt/advanced/otp_distribution.md
Added the changes from the English lesson version 1.1.0 and some minor changes to previous translation just to remove typos, improve accuracy and facilitate understanding for Portuguese speakers.
=> [PT] Update OTP Distribution to v1.1.0

lessons/pt/testing/basics.md
Added the latest updates from English lesson version 1.2.1 plus fixed some typos and formatting. Also included some minor improvements to the previous translation to make it easier for Portuguese-only speakers.
=> [PT] Update Testing Basics to v1.2.1

lessons/ko/misc/poolboy.md
associated with https://github.com/elixirschool/elixirschool/pull/2746
en 버전과 코드가 약간 달라서 수정했습니다. (try-catch 구문 및 주석 추가)
=> [KO] Update poolboy.md to 1.2.1

lessons/id/basics/iex_helpers.md
Added missing Indonesian translation for `iex_helpers` lesson.
=> [ID] iex_helpers to v1.0.2

lessons/id/basics/basics.md, lessons/id/basics/collections.md
Changes I did:
- Bump `basics.md` version to 1.3.0
- Bump `collections.md` version to 1.3.1
I also updated some sentences and words to what I think is more fit to the contexts.
If I misunderstood something and made errors, please let me know.
=> [id] Update some basics courses version and some minor changes.

lessons/ko/basics/control_structures.md
lesson - control_structures 
fix minor typo
=> [KO] fix typo 

lessons/en/data_processing/genstage.md
Fixup stylistic error, add comma and bump version
=> [EN] data_processing.genstage -> 1.1.2

lessons/fr/basics/strings.md
Translation of the Basics/Strings lesson to French. Don't hesitate if you see mistakes!
=> [FR] Translate basics/strings

lessons/fr/testing/mox.md
Translation of the Testing/Mox lesson to French. Don't hesitate if you see mistakes!
=> [FR] Translate mox lesson

lessons/fr/basics/iex_helpers.md
Translation of the Basics/IEx Helpers lesson to French. Don't hesitate if you see mistakes!
=> [FR] Translate IEx Helpers lesson

posts/2021-09-02-rocket-validator.md
Hi there,
We're reviewing coupon codes for this year, here goes an update to the blog post with the updated coupon code.
=> update offer on RV post

lessons/pt/testing/bypass.md
Just like in this [PR](https://github.com/elixirschool/elixirschool/pull/2959), the differences found between the English and Portuguese versions are not relevant enough to justify a difference in the versions number
=> [PT] update Bypass lesson

lessons/pt/ecto/changesets.md
- Update snippet example
- Paraphrase an explanatory text
=> [PT] Update Changeset lesson

lessons/ja/advanced/umbrella_projects.md
Correcting the execution result of Datasets.hello.
The results were before the code modification.
=> [JA] Fix minor errors in execution results

lessons/id/basics/enum.md, lessons/id/basics/pattern_matching.md
Improve and update translations to the latest version for these pages:
* `lessons/id/basics/enum.md` to version 1.9.1
* `lessons/id/basics/pattern-matching.md` to version 1.0.2
=> [id] Update translations for Enum & Pattern Matching pages

lessons/fr/intermediate/concurrency.md, lessons/fr/intermediate/escripts.md
Hi, 
A new pull request for the french version of these two lessons : intermediate/concurrency.md and intermediate/escripts.md.
Additionally, I have one question: what is the frequency of update on the website?
Thank you. :-)
=> Add french version for intermediate/concurrency and intermediate/escripts

lessons/en/basics/collections.md
update on the special characteristics of keyword-lists. Had to make it crystal clear as per the documentation.
=> Changes on the keyword-list characteristics .Update collections.md

lessons/es/ecto/basics.md
changing nombre to name to keep consistency with the schema part
=> Fixing atom name for consistency 

lessons/en/basics/control_structures.md
I found this wording to be a bit confusing - I couldn't figure out whether "it" was referring to `case` or `else`. Tried to clarify a bit
=> fix: clarify wording in control structures lesson

lessons/ru/misc/nimble_publisher.md
Hello, @doomspork !
Review this translation, please!
I liked `nimble_publisher` very much while translating this lesson. 😄 
Best regards!
=> [ru] Add translation for nimble publisher lesson

lessons/fr/basics/comprehensions.md, lessons/fr/basics/date_time.md, lessons/fr/basics/modules.md, lessons/fr/basics/sigils.md, lessons/fr/basics/strings.md, lessons/fr/intermediate/concurrency.md
Some text updates to fix typos, syntax and grammar errors, in french version.
=> Fr grammar syntax

lessons/en/misc/lua.md
I want to move some things our and trim a bit, this lesson ended up much longer than our other lessons.
=> feat: Refine Lua lesson

lessons/en/basics/functions.md
I believe this will clear some confusion to what's happening here.
=> Clear confusion.
