- README.md
Just saw that the links weren't working
> Add correct links to LICENSE and CONTRIBUTING

- lessons/collections.md
This is from Keyword help module:
A keyword may have duplicated keys so it is not strictly a dictionary. However
most of the functions in this module behave exactly as a dictionary and mimic
the API defined by the Dict behaviour.
> Fix: a keyword may have duplicated keys so it is not strictly a dict

- lessons/basics/basics.md
Hi, the order of 'table of contents' in `basics/basics.md` is not the same as its contents.
> Fix TOC of basics/basics.md

- lessons/basics/basics.md
- lessons/basics/collections.md
Fixed grammar at the end of basic chapter and typo at the beginning of collections chapter.
> Fix typos in intro lesson

- lessons/basics/mix.md
Don't know if it was a typo, or it was wanted to say that `Mix is a smart build tool...`. Just removed the `a` for brevity, but if you prefer the later, I'll update the PR :)
> fix small typo

- lessons/advanced/erlang.md
Thanks again @viktorot.  How does this sound to you now?
Closes #67
> Correct string interop section

- cn/lessons/advanced/otp-concurrency.md
- jp/lessons/advanced/otp-concurrency.md
- lessons/advanced/otp-concurrency.md
Hi guys! I was going through 'Elixir School' lessons. Great introduction to Elixir. Thanks for putting this up.
However, I noticed a small typo in code on this page http://elixirschool.com/lessons/advanced/otp-concurrency/ under 'Synchronous Functions' section. Following line was missing from code example:
```
def queue, do: GenServer.call(__MODULE__, :queue)
```
So, I updated the code. Let me know, if I'm wrong or anything like that.
> Add missing code for 'SimpleQueue' module - Synchronous Functions on OTP Concurrency page

- vi/lessons/basics/collections.md
There are many English terms that could not be 1:1 translated to Vietnamese. Most of the cases, translated terms make no senses whatsoever. Because most of Vietnamese developer uses English terms in their conversations, I don't see why we have to introduce awkward translated Vietnamese terms. I'd like to propose to keep the English word but introducing Vietnamese explanation clauses.
> Enhance Colletion page [vi]

- es/lessons/specifics/eex.md
- es/lessons/specifics/ets.md
- vi/lessons/specifics/eex.md
- vi/lessons/specifics/ets.md
There were only two languages that needed updated (en & vi) regarding the specifics lessons. The other languages are yet to add any content to this section.
> Fixed 'specifics' numbering to reflect 'en' lesson changes

- index.md
- pt/index.md
* Removing Extra pt Link from `en` index.
* Updating `pt` index and following the `en` index format.
Related to #89
> Updating Index of Portuguese(Brazil)

- pt/lessons/basics/composition.md
> Add Composition to Portuguese(Brazil)

- _assets/stylesheets/custom.scss
> add mobile styles to nav

- _includes/sidebar.html
Right now there is a very confusing behaviour when running the project locally - when you change language via link in the sidebar, you are redirected to the https://elixirschool.com instead of your local version of the site.
This PR should not change anything in production, but will simplify usability for translators a bit.
> Changed sidebar language links to be relative.

- pt/lessons/advanced/otp-concurrency.md
Related to #122 
Note: I couldn't find a good translation for `callback`, so I leave as it is but in *italic*.
Note 2: The word `handler` is not easy to translate, so I used the word "processador" which is something similar.
> Add translation for OTP concurrency - Portuguese

- lessons/basics/collections.md
Just to make it explicit it uses strict comparison when matching values to subtract
> Added note to list subtraction

- lessons/basics/mix.md
Moved 'interaction' section before the 'compilation'.
Removed reference to project compilation requirement to use iex.
Current wording is a bit confusing. ( _With our application compiled we can start a new `iex` session:		_ ) From this one might tell that this is caused by the fact app is compiled, while really it's working without compilation too.
Also, I've moved the 'iex' part before the compilation, because it's very widely used.
> Mix lesson changes

- _assets/stylesheets/custom.scss
- _config.yml
This PR fixes the missing baseurl in the _config.yml file and defaults it to /. While browsing the site, I found it incredibly hard to see links in the content body. I've added an underline to all content body links. 
The only place I've noticed "odd" behavior is when the link contains code block, in which I question whether a code tag should even be in a link.
Issue Reference: #281
> Design feedback

- pt/lessons/advanced/error-handling.md
- pt/lessons/advanced/metaprogramming.md
- pt/lessons/advanced/otp-supervisors.md
- pt/lessons/basics/basics.md
- pt/lessons/basics/collections.md
- pt/lessons/basics/composition.md
- pt/lessons/basics/documentation.md
- pt/lessons/basics/enum.md
- pt/lessons/basics/functions.md
- pt/lessons/basics/mix.md
- pt/lessons/basics/sigils.md
- pt/lessons/basics/testing.md
- pt/lessons/specifics/eex.md
- pt/lessons/specifics/ets.md
- pt/lessons/specifics/mnesia.md
- pt/lessons/specifics/plug.md
Some words on the summaries has special characters like `ç`, `õ`, `ã`
that Jekyll skips when compiling the markdown and making the anchors.
It prevented the Summary on pages that have headers with these
characters to work and a custom `<a name=""></a>` was necessary to
make the Summary work again.
I also fixed some typos on the summary that also prevented the summary
to work.
> [PT-BR] Fix typos and anchors on summaries

- lessons/basics/sigils.md
Every noun of the sigils list besides `strings` was singular.
I also think that it might be useful to point that `~W` and  `~w` sigils generate word lists but not character lists or anything else. It should look more clearly this way.
> Make a general view for sigils list

- _config.yml
- no/index.md
- no/lessons/basics/basics.md
Changed from "basis" to "grunnleggende" in config file,
fixed minor typo in frontpage index.md
translated basic 01 to norwegian
> Translation of basic/01

- lessons/basics/strings.md
@doomspork @pjhampton What do you think guys?
I didn't go full in-depth tho, but I think the content is enough to understand better Strings in Elixir :+1: :shipit:
> Adds a new lesson Strings in the basics section

- _config.yml
- cn/lessons/basics/basics.md
- es/lessons/basics/basics.md
- fr/lessons/basics/basics.md
- it/lessons/basics/basics.md
- jp/lessons/basics/basics.md
- lessons/advanced/umbrella-projects.md
- lessons/basics/basics.md
- lessons/specifics/mnesia.md
- my/lessons/basics/basics.md
- pl/lessons/basics/basics.md
- pt/lessons/advanced/umbrella-projects.md
- pt/lessons/basics/basics.md
- pt/lessons/specifics/mnesia.md
- ru/lessons/basics/basics.md
- sk/lessons/basics/basics.md
- vi/lessons/basics/basics.md
I just made another key in Jekyll's config so it will be easy to update Elixir version later. For now, I've set it to 1.2.3.
Changes were made in every existing translation of the following lessons:
- lessons/advanced/umbrella-projects.md;
- lessons/basics/basics.md;
- lessons/specifics/mnesia.md.
I also think we should note the use of  `{{site.elixir.version}}` in CONTRIBUTING.md or somewhere else.
> Bump Elixir version in examples (#275)

- _assets/javascripts/app.js
- _includes/sidebar.html
Earlier sidebar sections were toggled via JS: onload the `click` event was manually triggered on `advanced` and `specifics`.
Now we do not use any JS to set the sections' initial state when the page loads: appropriate CSS is applied in Liquid depending on the current page category. If the page has no category (e.g., we've just visited the index when we heard about Elixir School first time), `basics` is open by default.
> Open only current section in the sidebar (#314)

- _includes/social.html
It seems like the old id was just copied from the `basics` lesson.
The new correct id may also become useful for generation of the TOC (#336).
> Set a proper id for the header of social links block

- lessons/basics/strings.md
Fix issue #344 
Fixes:
- Resolved links from String lesson.
- Add link to `Split` function
> Fix links from String lesson

- README.md
Previous commit [e2de72d33bad2b60240b8b0dcaaf28c2287008e](https://github.com/doomspork/elixir-school/commit/de2de72d33bad2b60240b8b0dcaaf28c2287008e) fixed CONTRIBUTING.md filename but left README.md link broken.
> Fix link to Contributing guidelines

- lessons/specifics/ecto.md
In scope of #366. Added description of `count/1`, and information about `count/2` function. 
@doomspork
> Add description to count function

- cn/lessons/advanced/erlang.md
- es/lessons/advanced/erlang.md
- jp/lessons/advanced/erlang.md
- lessons/advanced/erlang.md
- my/lessons/advanced/erlang.md
- pl/lessons/advanced/erlang.md
- pt/lessons/advanced/erlang.md
- ru/lessons/advanced/erlang.md
- vi/lessons/advanced/erlang.md
This is a minor fix in the [Advanced -> Erlang Interoperability](https://elixirschool.com/lessons/advanced/erlang#erlang-packages) section.
> Fix minor typo with Map declaration

- jp/lessons/basics/sigils.md
- jp/lessons/basics/strings.md
Translated Strings session into Japanese.
This time, I just translated as same as the original, however I think multibyte character languages including Japanese should have additional description / examples / notes for the native users.
For example (Japanese small kana):
```elixir
iex> string = "\uFF76\uFF9E"
"ｶﾞ"
iex> String.codepoints string
["ｶ", "ﾞ"]
iex> String.graphemes string
["ｶﾞ"]
iex> String.length string
1
```
(note: I suspect that there is still no de facto standard of Japanese small kana's graphemes/codepoints translations, but Elixir just do it in this way)
> Japanese translation 1

- id/lessons/basics/comprehensions.md
Applied #430 to Indosenian. I actually have no clue how could I miss this one.
> [ID] Replace `rem(x, 2)` with `is_even(x)`

- _includes/social.html
Earlier when you shared the index page the title would look like `ElixirSchool: ElixirSchool` or `Check out "ElixirSchool" on ElixirSchool`.
> Fix the title for the index page when sharing

- es/lessons/specifics/eex.md
- id/lessons/specifics/eex.md
- ko/lessons/specifics/eex.md
- lessons/specifics/eex.md
- pl/lessons/specifics/eex.md
- pt/lessons/specifics/eex.md
- vi/lessons/specifics/eex.md
Right now we have arity in all function mentions. This PR adds arity to function names in EEx lesson.
> Add arity to functions in EEx lesson

- _assets/stylesheets/hyde.css
- _assets/stylesheets/social.scss
- _layouts/default.html
Printer button on the social media section should work properly.
Hided a sidebar, social media sharing section and "Fork me at Github" ribbon on the printed paper.
> Refined stylesheets for printing pages

- _includes/head.html
- _layouts/default.html
Changing `og:url` value to URL of each page will help showing information in Open Graph correctly. (Currently if we share any page to Facebook, we will see same previews because `og:url` points only the main page.)
And changed `description` and `og:description` to show translated description of Elixir School.
We can set `description`s which make summary for each page to make sneak-peeking easy.
> Changing header metadata to show correct information with sharing.

- jp/lessons/advanced/metaprogramming.md
* Fix wrong translation
* strip unnecessary comments
* Make some expressions more natural
> [JP] Improve translation in metaprogramming lesson

- lessons/basics/enum.md
This is in response to [Issue 478](https://github.com/doomspork/elixir-school/issues/478)
Chunk by beings a new list section when the return value of the function supplied changes. This newer format explains this and provides an example that shows this in a way that is more predictable.
Any thoughts on the language @doomspork? It could go into more detail but that doesnt really match the flow of the other examples.
> Clarify the functionality of Enum.chunk_by/2

- CONTRIBUTING.md
There is currently no documented preference on how best to handle making sure the translations all stay in sync with the main english version. This note gives the example of a simple PR I did [here](https://github.com/doomspork/elixir-school/issues/529) and shows a process I just mimicked from @doomspork. This hopefully will allow us to keep better track of the state of all guides.
> Add note to `CONTRIBUTING.md` about handling addtions' translations

- lessons/basics/enum.md
This is RE @nscyclone 's comment in [this thread](https://github.com/doomspork/elixir-school/issues/529#issuecomment-233766599) discussing the specific elaboration on Enum.chunk/1. In other areas it has been conventional to reference arity and it was not done here. This clarifies this and removes ambiguity as to whether it could be Enum.chunk_by/3.
I have also updated the issue for translation to note this as well [here](https://github.com/doomspork/elixir-school/issues/529).
> Add arity to the chunk_by description in basics Enum guide

- ko/lessons/basics/enum.md
Related: #201 and #529
I translated `enumerable` into `열거할 수 있는 컬렉션` and I wonder whether this translation is proper.
Feel free to give any suggestons about this. :smile_cat:
cc/ @Dalgona, @malkoG, @riseshia
> [KO] Clarify the functionality of Enum.chunk_by/2

- bg/lessons/basics/modules.md
- es/lessons/basics/modules.md
- gr/lessons/basics/modules.md
- id/lessons/basics/modules.md
- it/lessons/basics/modules.md
- jp/lessons/basics/modules.md
- ko/lessons/basics/modules.md
- lessons/basics/modules.md
- my/lessons/basics/modules.md
- pl/lessons/basics/modules.md
- pt/lessons/basics/modules.md
- ru/lessons/basics/modules.md
- sk/lessons/basics/modules.md
- vi/lessons/basics/modules.md
The `Saying` module is undefined and inconsistent with the rest of the snippets in the lesson. This updates the snippet to use the `Sayings` module as defined earlier in the lesson.
> Corrected typo in Module lesson code snippet

- sk/lessons/basics/basics.md
For some reason, those examples are a bit corrupted - iex output is not present there.
> [SK] Fix snippets in basics lesson

- lessons/basics/strings.md
Existing statement that Unicode characters "may be represented by one or two bytes" was factually incorrect.
```elixir
iex> Kernel.byte_size "a"   
1
iex> Kernel.byte_size "á"  # Western European
2
iex> Kernel.byte_size "ğ"  # Turkish
2
iex> Kernel.byte_size "ම" # Sinhala 
3
iex> Kernel.byte_size "😀" # emoji
4
```
> Fix description of UTF-8 encoding. Will need translation.

- GLOSSARY.md
In Elixir we only have public and private functiona, no protected ones here. :)
Also, I've removed '(function)' modifiers in glossary. FYI @pragmaticivan
> Remove obsolete term from glossary (protected function)

- lessons/basics/collections.md
`|` is not a pipe operator, but cons operator. We're discussing this in #600 .
If we merge this - we'll need to update all translations.
> Use proper term in 'collections' lesson

- pl/lessons/basics/collections.md
In context of #608 add information about `|` is cons not pipe.
> Add information about cons operator

- lessons/basics/collections.md
This tidbit might get people with Ruby background baffled. I'm quite sure other backgrounds might result in similar expectations. Seeing how it's a basic operation, it's better to be aware of this before you start building your knowledge on top of it.
Ruby behaviour:
```ruby
2.2.1 :002 > [1,1,2,3] - [1]
=> [2, 3]
```
Elixir behaviour:
```elixir
iex> [1,1,2,3] -- [1]
[1, 2, 3]
```
> Added an example demonstrating handling of duplicates in list substraction

- cn/lessons/basics/basics.md
The correct translation of "Interpolation" should be "插值". Fix the typo.
> [cn] Fix typo

- lessons/basics/testing.md
I saw that there is nothing on assert_receive yet. I am not sure how much this is actually used when writing tests for Elixir applications, but if it is I think it is worth mentioning since it is different from other language's xUnit toolkit.
> Add assert_receive, capture_io and capture_log to testing

- jp/lessons/advanced/typespec.md
Even `ja` is [right shorthand for Japanese(as a language, 日本語)](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes), All other lessons are using `jp` to indicate Japanese document.
Typespec lessons used `lang: ja` and this made it not visible from other Japanese lessons
and there is no other Japanese lessons in Typespec lesson as well.
Instead of changing all `jp`s into `ja`, I'd like to make small changes to Elixir school in Japanese and let this issue for Japanese contributors.
> [JP] Fixed typespec lesson from being hidden for other lessons.

- lessons/advanced/otp-supervisors.md
Current strategy description is not in line with real strategy functionality. It implies that child can be only one, which is wrong.
I've clarified this and added a note about dynamic use case.
> Clarify simple_one_for_one strategy description in OTP supervisors lesson

- lessons/specifics/mnesia.md
Extended the Mnesia page as a result of using it to understand how to use Mnesia in Elixir. The changes include:
- A short note on what the call to `Mnesia.create_table/2` returns when the table already exists,
- A short note on how to update existing data entries in the `Transactions` section,
- A new section on indices and how to use them,
- A new section on `Mnesia.match_object/1` and `Mnesia.select/2` to explain how to perform complex queries, in particular attempting to explain the special atoms used by those two functions,
- A new section on data initialisation and migration.
> Mnesia guide extensions

- lessons/basics/enum.md
This includes:
- several additions to examine functions and enumerate over them
- a dive into built in documentation with some helpers
The reasoning here originally started when I wanted to double-check the
accuracy of the count of functions that was listed.
Running
```
Enum.__info___(:functions) |> Enum.count
```
yields `82`, which is less than 100, so I clarified the language.
But then I realized some of the other tidbits I could do now that I had
a list of functions and their arity via the `__info__` call, which led to
the changes seen.
> Improve Enum basics section

- pt/lessons/basics/collections.md
Related to #608 
I took the chance and also added a missing reference to pattern matching, as seen in the original english version.
> [PT] Use proper term in collections (cons instead of pipe)

- Gemfile
> Use pessimistic versioning to allow 2.3.x versions of ruby.

- lessons/advanced/concurrency.md
The first line in the Concurrency paragraph reads:
```
One the selling points of Elixir is its support for concurrency. Thanks to the Erlang 
```
Instead of
```
One of the selling points of Elixir is its support for concurrency. Thanks to the Erlang 
```
> Fix typo in first concurrency paragraph

- lessons/basics/sigils.md
http://elixir-lang.org/docs/stable/elixir/NaiveDateTime.html
> Add ~N sigil

- bg/index.md
- index.md
- uk/index.md
Right now when using local site you may unintentionally get to https://elixirschool.com/ via those links.
That's a minor inconvenience, but this fix may be helpful to save some time on debugging. 
Also, looks like we have those links on only two translations - other translations just don't have this block. Any ideas whether it's intentional?
> Use relative URLs in index translation links

- _config.yml
`1.3.4` is the [latest](https://github.com/elixir-lang/elixir/releases/tag/v1.3.4) release.
> Bump Elixir version

- bg/lessons/basics/basics.md
- gr/lessons/basics/basics.md
- jp/lessons/basics/basics.md
- ru/lessons/basics/basics.md
- uk/lessons/basics/basics.md
These spaces break markup on website pages.
e.g:
I checked all `lessons/basics/basics.md` files and if it's necessary I can check all.
> Remove unnecessary spaces.

- lessons/advanced/behaviours.md
Self-explanatory. It was not listing with a capitalized title like the rest of the Advanced lessons in its section.
> Capitalize `behaviours` lesson in listing

- lessons/advanced/gen-stage.md
The new `GenStage` tutorial is great! But it promises to find the primes up to who knows how high of a number, and the sample code checks for even numbers.
In lieu of a good solution to reverse-engineer primes - unless I have misunderstood the description of course - I changed the introduction text to match the example code.
I can submit a more computationally expensive function than checking for even integers if necessary, but this seemed like a good stopgap so that the code isn't misleading.
Thanks!
> update GenStage lesson introduction

- cn/lessons/advanced/escripts.md
- de/lessons/advanced/escripts.md
- es/lessons/advanced/escripts.md
- gr/lessons/advanced/escripts.md
- id/lessons/advanced/escripts.md
- jp/lessons/advanced/escripts.md
- ko/lessons/advanced/escripts.md
- lessons/advanced/escripts.md
- lessons/advanced/gen-stage.md
- pl/lessons/advanced/escripts.md
- pt/lessons/advanced/escripts.md
- ru/lessons/advanced/escripts.md
- vi/lessons/advanced/escripts.md
Compiling 1 file (.ex)
warning: the variable "word" is unsafe as it has been set inside a case/cond/receive/if/&&/||. Please explicitly return the variable value instead. For example:
case int do
1 -> atom = :one
2 -> atom = :two
end
should be written as
atom =
case int do
1 -> :one
2 -> :two
end
Unsafe variable found at:
lib/build_basics.ex:19
> Remove compiler warning

- pl/lessons/basics/collections.md
Text updated from:
*Od wersji 1.2 Elixir zmienne mogą być użyte jako klucz:*
to:
*Od wersji 1.2 Elixir**a** zmienne mogą być użyte jako klucz:*
> [PL] Collections - Minor typo

- fr/lessons/basics/functions.md
- id/lessons/basics/functions.md
- id/lessons/basics/pipe-operator.md
The French translation had two seventh lessons in `basics`. In the Indonesian translation the sixth and the seventh lessons were swapped.
> Fix the incorrect lesson order in translations

- pt/lessons/basics/enum.md
- Little typo in atoms ```Enum.sort``` example.
> [PT] Fix a little typo in pt version

- CONTRIBUTING.md
When responding to [this issue](https://github.com/doomspork/elixir-school/issues/828) I realized the style guide I suggested to consult was not linked to in CONTRIBUTING.md, and figured this was a no-brainer to help new contributors get started and not have minor issues that slow the merge flow.
> Link to style guide in CONTRIBUTING.md

- lessons/specifics/ecto.md
password_incorrect_error and password_mismatch_error are called in opposite order of where they should have been called in the get_change case.  This fix reorders them correctly.
> Fix password error function order in validate_password_confirmation (ref #826)

- pl/lessons/advanced/typespec.md
The current sidebar on the site includes the Polish specs and types link.
> fix: mislabeled lang in pl specs

- lessons/libraries/poolboy.md
It is confusing to see the toc including the `Why use Poolboy?` when you have just read it.
> Change location of toc

- lessons/basics/control-structures.md
Right now our tutorials are missing this useful part of `case` operator.
This PR fixes this problem.
> Add else example for case operator

- lessons/advanced/gen-stage.md
> Fixing formatting in one sentence

- pl/lessons/specifics/eex.md
@Koziolek, could you check this one, please?
> [PL] Fix a typo in the `specifics/eex` lesson translation

- lessons/advanced/otp-concurrency.md
This removes all reference to GenEvent. From my grepping, it was contained to this single lesson. If anyone else has spotted any other instances, feel free to let me know and I will update.
I would have just done the PR's to remove it all from the languages that have the lesson for translations too but it requires changing the first reference from singular to plural so I would fail that pretty hard I imagine.
I know issue #944 goes into versioning and keeping things up, @nscyclone @brain-geek @devleoper @Koziolek @gemantzu or anyone else feel free to handle the translation side of tracking this, or if you just want to go the typical issue route I have opened one [here](link) but will close it if a new setup is desired.
> Remove References to GenEvent

- vi/lessons/libraries/guardian.md
Applying fix from #912 to the last translation not yet affected by this change.
> Fix JWT name error in VI translation

- lessons/advanced/protocols.md
This is a first run at a lesson on Protocols for the advanced section from what I started with and finished with @doomspork's feedback.
> New Lesson: Protocols

- lessons/basics/pipe-operator.md
I believe that the author meant to use 'parentheses' instead of 'brackets' in the pipe operator lesson. Just a small change to avoid confusion.
> Fix small vocab mistake

- gr/lessons/advanced/gen-stage.md
- ko/lessons/advanced/gen-stage.md
- lessons/advanced/gen-stage.md
- pl/lessons/advanced/gen-stage.md
- ru/lessons/advanced/gen-stage.md
- vi/lessons/advanced/gen-stage.md
This PR updates the examples in the GenStage advanced lesson. It includes a version bump for GenStage and removal of invalid code in the examples.
> Update the GenStage examples for v0.11

- bg/lessons/basics/control-structures.md
- bn/lessons/basics/control-structures.md
- de/lessons/basics/control-structures.md
- gr/lessons/basics/control-structures.md
- id/lessons/basics/control-structures.md
- jp/lessons/basics/control-structures.md
- ko/lessons/basics/control-structures.md
- lessons/basics/control-structures.md
- no/lessons/basics/control-structures.md
- pl/lessons/basics/control-structures.md
- ru/lessons/basics/control-structures.md
- vi/lessons/basics/control-structures.md
The first match clause must be on the same line with `with` keyword. [Docs](https://hexdocs.pm/elixir/master/Kernel.SpecialForms.html#with/1)
Otherwise compiler throws `SyntaxError: unexpectedly reached end of line. The current expression is invalid or incomplete`
> Fix with syntax in control structures lesson

- index.md
Italiano is more correct than: L'Italiano
> Fix typo on selection language menu

- gr/lessons/specifics/mnesia.md
- id/lessons/specifics/mnesia.md
- ko/lessons/specifics/mnesia.md
- lessons/specifics/mnesia.md
- pl/lessons/specifics/mnesia.md
- pt/lessons/specifics/mnesia.md
- ru/lessons/specifics/mnesia.md
- vi/lessons/specifics/mnesia.md
This simple update to the example code will remove the following warning:
Instead of
```
iex> Mnesia.create_schema([node])
warning: variable "node" does not exist and is being expanded to "node()", please use parentheses to remove the ambiguity or change the variable name
:ok
```
this works better:
```
iex> Mnesia.create_schema([node()])
:ok
```
> Update 'mnesia/create_schema' example to remove warning

- _assets/javascripts/app.js
- _assets/javascripts/toc.js
- _assets/stylesheets/custom.scss
- ko/lessons/basics/basics.md
This PR turns the headers into anchors and adds the `back-to-top` icons next to them. 
In order to achieve this it includes the latest version of the [TOC script](https://github.com/ghiculescu/jekyll-table-of-contents) with locally added ability to customize the `back-to-top` icon classes and several relevant SCSS changes.
> Improve headers usability

- bg/lessons/basics/functions.md
- bn/lessons/basics/functions.md
- cn/lessons/basics/functions.md
- de/lessons/basics/functions.md
- es/lessons/basics/functions.md
- fr/lessons/basics/functions.md
- gr/lessons/basics/functions.md
- id/lessons/basics/functions.md
- it/lessons/basics/functions.md
- jp/lessons/basics/functions.md
- ko/lessons/basics/functions.md
- lessons/basics/functions.md
- my/lessons/basics/functions.md
- pl/lessons/basics/functions.md
- pt/lessons/basics/functions.md
- ru/lessons/basics/functions.md
- sk/lessons/basics/functions.md
- vi/lessons/basics/functions.md
Fixes the following warning shown when executing this example in IEx:
```
warning: variable "phrase" does not exist and is being expanded to "phrase()", please use parentheses to remove the ambiguity or change the variable name
```
Follows Elixir Style Guide [here](https://github.com/christopheradams/elixir_style_guide#parentheses), recommending that functions without arguments should not have parentheses. Instead, use parentheses in function invocation.
Fixes #985
References #986
> Fix syntax warning for Greeter module under 'Guards' section in Basics/Functions lesson

- ko/lessons/advanced/concurrency.md
- ko/lessons/advanced/erlang.md
- ko/lessons/advanced/error-handling.md
- ko/lessons/advanced/escripts.md
- ko/lessons/advanced/metaprogramming.md
- ko/lessons/advanced/otp-concurrency.md
- ko/lessons/advanced/otp-supervisors.md
- ko/lessons/advanced/umbrella-projects.md
- ko/lessons/basics/basics.md
- ko/lessons/basics/collections.md
- ko/lessons/basics/comprehensions.md
- ko/lessons/basics/control-structures.md
- ko/lessons/basics/documentation.md
- ko/lessons/basics/enum.md
- ko/lessons/basics/functions.md
- ko/lessons/basics/mix-tasks.md
- ko/lessons/basics/mix.md
- ko/lessons/basics/modules.md
- ko/lessons/basics/pattern-matching.md
- ko/lessons/basics/pipe-operator.md
- ko/lessons/basics/sigils.md
- ko/lessons/basics/strings.md
- ko/lessons/basics/testing.md
- ko/lessons/libraries/guardian.md
- ko/lessons/libraries/poolboy.md
- ko/lessons/specifics/ecto.md
- ko/lessons/specifics/eex.md
- ko/lessons/specifics/ets.md
- ko/lessons/specifics/mnesia.md
- ko/lessons/specifics/plug.md
Changed:
- bump up version
- Use `Plug` instead of `플러그` via all translations
Remained work:
Totally not translated below.
- iex-helpers.md
- protocols.md
- debugging.md
I will translate these until next week... or is there someone to help?
@Dalgona, @malkoG, @devleoper, @marocchino  review please.
used diff: `git diff 65e4a61..dc9ab42 --word-diff -- lessons/`
related: #1043
> [KO] Update translation on exist documents

- _config.yml
- id/lessons/advanced/umbrella-projects.md
- id/lessons/basics/basics.md
- id/lessons/specifics/mnesia.md
- no/lessons/basics/basics.md
There were some places where the Elixir version in `iex` examples was hardcoded.
Also [1.4.4](https://github.com/elixir-lang/elixir/releases) is the latest version now.
> Use the Elixir version placeholder where it was missing

- no/lessons/basics/mix-tasks.md
This is the only file that is missing the version,
the other one is pl/lessons/advanced/protocols.md but I think the file should be
removed because it has not been translated yet (therefore
https://github.com/doomspork/elixir-school/pull/1120 )
I can assume this is version 1.0.0 since the original file was last modified by
commit 90a6f631255516973b81c8164084e37f467aa101
Author: Oleksandr Rozumii <brain-geek@yandex.ua>
Date:   Sat Oct 8 23:43:43 2016 +0300
Minor improvements all over the basic lessons (#709)
and this Norwegian translation dates from
commit 3b04fdd380655619fab80a36ab7068076de965ba
Author: Robin Saleh-Jan <robinsjdotcom@users.noreply.github.com>
Date:   Tue Mar 21 23:19:47 2017 +0100
[NO]: Translate mix task lesson (#1022)
> Add missing version to no/lessons/basics/mix-tasks.md

- _config.yml
Recently we have updated Jekyll to resolve #1134. After the [latest major update](https://github.com/jekyll/jekyll/releases/tag/v3.5.0) Jekyll [started offering a replacement for the `gems` config key](https://github.com/jekyll/jekyll/pull/5130). So without this proposed change a deprecation warning would be displayed during every build:
>Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
> Rename the "gems" config key to "plugins"

- _config.yml
[1.5.0 was released yesterday](https://github.com/elixir-lang/elixir/releases/tag/v1.5.0).
> Bump Elixir and OTP versions

- bg/lessons/basics/functions.md
- bn/lessons/basics/functions.md
- cn/lessons/basics/functions.md
- de/lessons/basics/functions.md
- en/lessons/basics/functions.md
- es/lessons/basics/functions.md
- fr/lessons/basics/functions.md
- gr/lessons/basics/functions.md
- id/lessons/basics/functions.md
- it/lessons/basics/functions.md
- jp/lessons/basics/functions.md
- ko/lessons/basics/functions.md
- my/lessons/basics/functions.md
- pl/lessons/basics/functions.md
- pt/lessons/basics/functions.md
- ru/lessons/basics/functions.md
- sk/lessons/basics/functions.md
- vi/lessons/basics/functions.md
The example snippets reference the optional parameter "country" but
what it means seems to be `language` (as [many countries are
multilingual][1]).
[1]: https://en.wikipedia.org/wiki/List_of_multilingual_countries_and_regions
---
A bit of a pedantic change - I know -, but having dealt with l10n some years ago this mix-up was my most frequent headache. In real code I would probably use `language_code` instead, but I don't think we need to be _this_ precise (I'm happy to change it nonetheless, it's a `$ find -exec sed` away).
> Use "language" instead of "country"

- en/lessons/libraries/poolboy.md
The code example in Poolboy lesson is not up to date with changes in Elixir 1.4, and this PR addresses that issue. Issue number is #1148.
The PR contains two commits:
- First commit has minimal update to the code example so that it will be up to date with Elixir 1.4 and later.
- Second commit has edits to lesson text and restructuring of code example.
Notable changes in the second commit:
- Restructure `PoolboyApp.Test` module to make the code less dense.
- Replace `:poolboy.child_spec/3` with `:poolboy.child_spec/2` to omit details that are unnecessary for the lesson.
- Mention which file should be created or edited.
- Fill in missing steps like getting dependency and running the test code.
- Edit the lesson text with the goal of making it more precise. Most of the changes involved …
> Update Poolboy lesson for Elixir 1.4 and improve wording 

- .gitignore
- _data/contents.yml
- en/lessons/libraries/benchee.md
- en/lessons/specifics/benchmarking.md
This adds a lesson on benchmarking, which I felt went well with the
lesson on debugging, so I added it below that lesson in the sidebar.
Since the existing function for benchmarking in Erlang (`timer.tc`) is
super minimal and not entirely human friendly, I decided to go with
Benchee since it's currently the best library for benchmarking in
Elixir.
I'd be happy to hear feedback on this and if there are any further
changes that should be made to conform to any ElixirSchool
styles that aren't mentioned in the style guide. Also, @PragTob
may have some recommendations for possible changes, so it
would be nice to hear from him before merging 😄
> Add benchmarking lesson

- en/lessons/basics/enum.md
As stated, the live version is for `Enum.chunk` which doesn't exist in Elixir 1.5.1.
Alas, I'm not in a position to handle all the non-English translations.
> Update reference to Enum.chunk to modern Enum.chunk_every

- en/lessons/specifics/ecto.md
I think the convention used by Ecto team now days is not to use "model" to describe, well, schemas. The term "schema" is preferred.
This pull request changes the wording in a few places to reflect that.
> Update wording of the guide not to use "model"

- _assets/stylesheets/custom.scss
The scrollbar in the sidebar is present even if the content doesn't overflow its box. [Example.](https://elixirschool.com/uk/)
> Remove permanent scrollbar from the sidebar

- cn/lessons/advanced/erlang.md
- de/lessons/advanced/erlang.md
- en/lessons/advanced/erlang.md
- es/lessons/advanced/erlang.md
- gr/lessons/advanced/erlang.md
- id/lessons/advanced/erlang.md
- jp/lessons/advanced/erlang.md
- ko/lessons/advanced/erlang.md
- my/lessons/advanced/erlang.md
- pl/lessons/advanced/erlang.md
- pt/lessons/advanced/erlang.md
8 ms for just three multiplications? This must be slow as 🐌
> Fix Erlang timer.tc function returns time in microseconds not miliseconds

- _assets/javascripts/app.js
- _assets/javascripts/contributors.js
- _assets/stylesheets/app.scss
- _assets/stylesheets/contributors.scss
- _includes/contributors.html
- _layouts/page.html
Resolve #927
Using github api to query username from commit by file path.
There are 2 edge cases that haven't covered yet.
1. page can have only less than or equal 100 contributors due to github api per_page max is 100 or else need to fetch until next page is empty.
2. rate_limit for the api is 60 per hour so if we refresh page or navigate to new page more than that it  won't show contributors within 1 hour.
> Show contributors in each file by commit

- en/lessons/basics/testing.md
Changed by:
https://github.com/elixir-lang/elixir/blame/dd23bef088cd5014da54e2fc3459d782612640fc/lib/mix/lib/mix/tasks/new.ex#L404
https://github.com/elixir-lang/elixir/blame/master/lib/mix/lib/mix/tasks/new.ex#L451
I've added some paragraph too about that doctest was run from the generated file by mix.
> [EN] Update mix generated test file

- bn/lessons/basics/iex-helpers.md
- en/lessons/basics/iex-helpers.md
- gr/lessons/basics/iex-helpers.md
- ko/lessons/basics/iex-helpers.md
- no/lessons/basics/iex-helpers.md
- pl/lessons/basics/iex-helpers.md
- pt/lessons/basics/iex-helpers.md
- sk/lessons/basics/iex-helpers.md
In Map there are two methods not listed before: replace/3 and replace!/3.
I got to mention here that in Elixir 1.6 replace/3 will be deprecated: 
https://github.com/elixir-lang/elixir/commit/a81a17b3b09b267883383bdb8a00fe00ab2724a8#diff-6de3c4f6ae8d21f212a47e56ccdd4d77R18
> Added two new Map methods into autocomplete example

- bg/lessons/basics/control-structures.md
- bn/lessons/basics/control-structures.md
- de/lessons/basics/control-structures.md
- en/lessons/basics/control-structures.md
- gr/lessons/basics/control-structures.md
- id/lessons/basics/control-structures.md
- jp/lessons/basics/control-structures.md
- ko/lessons/basics/control-structures.md
- no/lessons/basics/control-structures.md
- pl/lessons/basics/control-structures.md
- ru/lessons/basics/control-structures.md
- sk/lessons/basics/control-structures.md
- tr/lessons/basics/control-structures.md
- vi/lessons/basics/control-structures.md
Fixes #1224.
I updated all the existing examples (14 occurrences). Hopefully, the PR is good :)
Languages affected:
* `bg`
* `bn`
* `de`
* `en`
* `gr`
* `id`
* `jp`
* `ko`
* `no`
* `pl`
* `ru`
* `sk`
* `tr`
* `vi`
> Fix with/1 refactoring example inconsistency between case/2 and with/1 versions

- en/lessons/basics/modules.md
It was brought to my attention by @p-buse that we're including a portion of someone else's blog post and that it was unattributed.  Since we avoid referencing and linking to third-party sites, we need to remove or update this section which this PR seeks to do.
I'd love some thoughts.
> Re-write the use section to remove unattributed examples

- en/lessons/advanced/behaviours.md
- en/lessons/advanced/concurrency.md
- en/lessons/advanced/erlang.md
- en/lessons/advanced/error-handling.md
- en/lessons/advanced/escripts.md
- en/lessons/advanced/gen-stage.md
- en/lessons/advanced/metaprogramming.md
- en/lessons/advanced/otp-concurrency.md
- en/lessons/advanced/otp-supervisors.md
- en/lessons/advanced/protocols.md
- en/lessons/advanced/typespec.md
- en/lessons/advanced/umbrella-projects.md
- en/lessons/basics/control-structures.md
- en/lessons/basics/documentation.md
- en/lessons/basics/functions.md
- en/lessons/basics/mix-tasks.md
- en/lessons/basics/mix.md
- en/lessons/basics/strings.md
- en/lessons/basics/testing.md
- en/lessons/libraries/benchee.md
- en/lessons/libraries/guardian.md
- en/lessons/libraries/poolboy.md
- en/lessons/specifics/debugging.md
- en/lessons/specifics/ecto.md
- en/lessons/specifics/eex.md
- en/lessons/specifics/ets.md
- en/lessons/specifics/plug.md
To celebrate the Elixir formatter I've gone through and formatted the code blocks. The example code will now reflect the formatted Elixir of the future!
I specifically ignored some of the examples because the format was important for teaching purposes and only formatted code blocks and config.
I also found a breaking syntax error in the [Guardian token response example](https://github.com/elixirschool/elixirschool/compare/master...SpyR1014:master#diff-905f78632ecd759996eb649fac036c65R245) where `{token: jwt}` needed to be changed to `%{token: jwt}`.
There was also a broken [ecto example](https://github.com/elixirschool/elixirschool/compare/master...SpyR1014:master#diff-4955bc2f9bc2a2d8f301f1425c2c34feR274) that was missing a comma.
Something very interesting the formatter did was add more …
> Formatting the code with the Elixir format tool

- bn/lessons/basics/control-structures.md
- en/lessons/basics/control-structures.md
- gr/lessons/basics/control-structures.md
- ko/lessons/basics/control-structures.md
- pl/lessons/basics/control-structures.md
- ru/lessons/basics/control-structures.md
- sk/lessons/basics/control-structures.md
- th/lessons/basics/control-structures.md
- tr/lessons/basics/control-structures.md
- vi/lessons/basics/control-structures.md
The example code block for using `else` with `with` throws a warning for importing `Integer` and not using it; fixed by removing `Integer.is_even` and just calling `is_even` directly.
> Fix warning in using `else` alongside `with` example code block.

- ko/lessons/basics/enum.md
1. Correct the unmatched arities with explanations.
... from `chunk_every/4` to `chunk_every` or `chunk_every/2`
2. Parenthesize the text of the link to the official documentation,
like English version of that, to show as a 'link', not a piece of code.
Signed-off-by: Hansuk Hong <flavono123@gmail.com>
> [KO] Fix arities of `Enum.chunk_every` section

- ko/lessons/basics/enum.md
I referenced this version: https://github.com/elixirschool/elixirschool/blob/4f596ce50f370029d3b14b56263c870c5b15ac24/en/lessons/basics/enum.md
Note that, due to the directory move, there may be missing parts because previous commits of 97da2a29188af59a3b635bb07bd5244684974560 can not refer.
> [KO] update enum to 1.3.0

- _assets/javascripts/app.js
Is there a better way than hardcoding the default language?
> Changes link to point correctly to en subfolder

- bg/lessons/basics/pipe-operator.md
- de/lessons/basics/pipe-operator.md
- en/lessons/basics/pipe-operator.md
- es/lessons/basics/pipe-operator.md
- fr/lessons/basics/pipe-operator.md
- ta/lessons/basics/pipe-operator.md
- th/lessons/basics/pipe-operator.md
English version of pipe-operator lesson wasn't formatted as others.
This commit fixes next error: There is an error in the version definition of this chapter.
[1, 0, 0] vs "1.0.1"
> Fix an error in the version definition of pipe-operator lesson

- _plugins/elixir_school.rb
Discussed in #1268. This PR disables the warning when the translation's patch version is higher than the original lesson's one.
> Suppress the patch version mismatch warning

- cn/lessons/advanced/escripts.md
- de/lessons/advanced/escripts.md
- en/lessons/advanced/escripts.md
- es/lessons/advanced/escripts.md
- gr/lessons/advanced/escripts.md
- id/lessons/advanced/escripts.md
- jp/lessons/advanced/escripts.md
- ko/lessons/advanced/escripts.md
- pl/lessons/advanced/escripts.md
- pt/lessons/advanced/escripts.md
- ru/lessons/advanced/escripts.md
- sk/lessons/advanced/escripts.md
- vi/lessons/advanced/escripts.md
Similar to how the deps are initialized in a fresh mix project, we should declare the escript argument using brackets (to signify that it is a function) and the function itself should be private (because it is never accessed outside of the module).
The following translations do not contain the relevant section.
- ar
- bg
- bn
- fr
- it
- my
- no
- ta
- th
- tr
- tw
- uk
> Escripts: Better practice in mixfile

- ko/lessons/advanced/concurrency.md
I've molded some sentences to clear explanation for `spawn linkage` on concurrency chapter and added a missing phrase for `process_flag`. #1284
> [KO] Molded some sentences to clear explanation for spawn linkage on concurrency chapter.

- Gemfile
Support for higher Ruby versions when `bundle install` is executed to avoid `_Your Ruby version is 2.x.x, but your Gemfile specified 2.3.1_` Log.
> Update Gemfile for ruby higher version support 

- vi/lessons/basics/control-structures.md
This is just a small typo, please review ヽ(＊>∇<)ﾉ
> [vi] Fix typo in control structures lesson

- pt/lessons/advanced/metaprogramming.md
- pt/lessons/libraries/bypass.md
Change `defmacro` to `defmacrop` on [Metaprogramming section > Private Macros](https://elixirschool.com/pt/lessons/advanced/metaprogramming/#macros-privados)
> [PT] Correcting the definition of private macro and some and orthography issues

- bg/index.md
- bn/index.md
- en/index.md
There is some missed codes not replaced from `jp`
Please review this @marocchino @doomspork
> Fix link for japanese

- en/lessons/specifics/ets.md
I'm not sure if this is the best place in the document to add this, but as soon as I read that `:public` access was possible, I wanted to know how race conditions could be prevented. After reading and experimenting, this is what I came up with.
> Add a section on race conditions with ETS tables

- en/lessons/libraries/bypass.md
- pt/lessons/basics/pattern-matching.md
- pt/lessons/libraries/bypass.md
Good catch @eksperimental, this should remove the redirect from the new lessons 👍
> Remove redirect from newer lessons

- en/lessons/basics/documentation.md
Slight typo here that could alternatively read "used to do static analysis of code." Let me know if you'd prefer that.
> static analysis of code -> statically analyze code

- bn/lessons/basics/iex-helpers.md
- de/lessons/basics/iex-helpers.md
- en/lessons/basics/iex-helpers.md
- gr/lessons/basics/iex-helpers.md
- ja/lessons/basics/iex-helpers.md
- ko/lessons/basics/iex-helpers.md
- no/lessons/basics/iex-helpers.md
- pl/lessons/basics/iex-helpers.md
- pt/lessons/basics/iex-helpers.md
- sk/lessons/basics/iex-helpers.md
- tw/lessons/basics/iex-helpers.md
Fixes #1358
As noted in #1358, the `s` helper has been removed from Elixir 1.6.0, as
the same information is available in output from the `h` helper.
> iex-helpers: Remove `s` section

- en/lessons/basics/pattern-matching.md
To show that the reassignment of the `greeting` variable is local to the
function and doesn't affect the outer scope.
> Add extra note to "function clause pinning" section

- en/lessons/basics/control-structures.md
Hi All,
I think I noticed something that might be considered as a small mistake. Since the phrase ` You can find their implementation` starts with upper Y it might be a good idea to replace semicolon with a dot.
Hope this helps.
Cheers,
Rafal
> [EN] Semicolon replaced with a dot

- cn/lessons/specifics/plug.md
- en/lessons/specifics/plug.md
- es/lessons/specifics/plug.md
- gr/lessons/specifics/plug.md
- id/lessons/specifics/plug.md
- ja/lessons/specifics/plug.md
- ko/lessons/specifics/plug.md
- pl/lessons/specifics/plug.md
- pt/lessons/specifics/plug.md
- ru/lessons/specifics/plug.md
- vi/lessons/specifics/plug.md
Without `use Plug.ErrorHandler` every raised exception would default to
a status code of 500. This resolves that. The example could probably
also include the overwriting of the `handle_errors/2` callback but it
may not be necessary especially considering that it looks like Plug is
(thankfully) trying to get people to not use exceptions for regular
control flow. The example will fallback to body text of "Something went
wrong", however.
> Allow plug ex. to set plug_status on exception

- bg/lessons/basics/control-structures.md
- bn/lessons/basics/control-structures.md
- cn/lessons/basics/control-structures.md
- de/lessons/basics/control-structures.md
- en/lessons/basics/control-structures.md
- es/lessons/basics/control-structures.md
- fr/lessons/basics/control-structures.md
- gr/lessons/basics/control-structures.md
- id/lessons/basics/control-structures.md
- it/lessons/basics/control-structures.md
- ja/lessons/basics/control-structures.md
- ko/lessons/basics/control-structures.md
- ms/lessons/basics/control-structures.md
- no/lessons/basics/control-structures.md
- pl/lessons/basics/control-structures.md
- pt/lessons/basics/control-structures.md
- ru/lessons/basics/control-structures.md
- sk/lessons/basics/control-structures.md
- ta/lessons/basics/control-structures.md
- th/lessons/basics/control-structures.md
- tr/lessons/basics/control-structures.md
- tw/lessons/basics/control-structures.md
- uk/lessons/basics/control-structures.md
- vi/lessons/basics/control-structures.md
Noticed that this URL was out of date and found the URL.
> fixes out-dated URL for "Expressions allowed in guard clauses"

- pl/lessons/basics/enum.md
Now we have `Enum` without `filter/2`
> [PL] Update Enum lesson to 1.3.0

- en/lessons/basics/functions.md
I'm getting this error when running the example:
```
warning: variable "phrase" does not exist and is being expanded to "phrase()", please use parentheses to remove the ambiguity or change the variable name
```
I'm pretty new to Elixir so feel free to judge :)
> add parens to function call

- en/lessons/advanced/otp-supervisors.md
- en/lessons/specifics/ecto.md
Addresses #1029 
The Ecto section was easy enough to update, but I expanded a lot on the OTP Supervisors page.  I added a more complete tutorial using the SimpleQueue module to show that the module is automatically started.  I also tried to summarize the new DynamicSupervisor without just copying over the official docs.
Some questions:
1. The project's _config.yml file has the Elixir version set to 1.5.2.  Should that be updated to 1.6 since DynamicSupervisor was added in that version?  Or is that version kept for another reason?
2. I see that the markdown files themselves are versioned to track which files need translations.  I did not increment the version number, what should they be set to with these updates?
3. Any improvements or clarifications?
> Update supervisor examples to Elixir 1.6

- en/lessons/advanced/otp-supervisors.md
The examples for supervisors set the `opts` variable but never used. Instead passed another set of options when starting supervisors. This is clearly a mistake and I just corrected that.
> OTP Supervisors: Fix the examples to use opts variable

- _assets/stylesheets/main.scss
- _includes/report.html
<details>
<summary>Before:</summary>
</details>
<details>
<summary>After:</summary>
</details>
> Slightly improve versioning style of the translation report

- _includes/report.html
- _plugins/elixir_school/translation_report.rb
The original links use the title (which is wrong) to link to the original lesson.
> fixes bogus links to original lessons

- _data/contributors.yml
Hello guys.
This will fix issue on the contributors page. Not sure how to describe it, so here are the screenshots:
Before:
After:
It's related to weird YAML behavior with 'no' and 'yes' words. [Here are details.](https://coderwall.com/p/ex6tla/yes-and-no-in-yaml)
> Fix empty language name on contributors page

- ta/index.md
Actually, here we've had three problems:
- Missing link to `en` version, which looked like this:
- Wrong syntax in `tr` link, which led to link like this: `https://elixirschool.com/ta/tr`
- Missing comma after `English`
While I know nothing about the language, two first problem seems like this hasn't been proofread, so my assumption is the third one is also a mistake.
> Fix broken markdown in TA translation index page

- en/lessons/advanced/otp-concurrency.md
Okay, this may be discussable overall, but this may be improvement.
#487 is a source where I took the idea from, and it makes some sense.
Let's discuss if you think that it's a bad change. :)
> Improve GenServer definition to state that it's single process

- _assets/stylesheets/components/_list.scss
> Improve lists appearance

- _data/locales/ar.yml
- _data/locales/bg.yml
- _data/locales/bn.yml
- _data/locales/de.yml
- _data/locales/en.yml
- _data/locales/es.yml
- _data/locales/fr.yml
- _data/locales/gr.yml
- _data/locales/id.yml
- _data/locales/it.yml
- _data/locales/ja.yml
- _data/locales/ko.yml
- _data/locales/ms.yml
- _data/locales/no.yml
- _data/locales/pl.yml
- _data/locales/pt.yml
- _data/locales/ru.yml
- _data/locales/sk.yml
- _data/locales/ta.yml
- _data/locales/th.yml
- _data/locales/tr.yml
- _data/locales/uk.yml
- _data/locales/vi.yml
- _data/locales/zh-hans.yml
- _data/locales/zh-hant.yml
- _includes/report.html
- _plugins/elixir_school/translation_report.rb
This is based on the fact that english lesson has the version on second line. For example, en/index.md breaks it.
> last_commit as a link on report

- en/index.md
- en/lessons/basics/control-structures.md
- zh-hans/index.md
- zh-hans/lessons/basics/control-structures.md
- zh-hans/lessons/basics/pattern-matching.md
Follow ups of #1485
Changes:
1. Updated the pattern-matching lession
2. Updated the Elixir Home
3. Fix the translation links to include Simplified Chinese (zh-hans) and Traditional Chinese (zh-hant)
> More transtion updates of Simplified Chinese

- en/lessons/basics/documentation.md
The package versions used in the lesson result in errors when running `mix docs`
> Update earmark and ex_doc package versions

- ja/lessons/specifics/plug.md
> 手始めに、lib/plug/router.exというファイルを作り、以下をコピーしましょう:
When making router.ex, there is an instruction as above.
But originally should be /lib/example/router.ex
Otherwise there is a discrepancy with the description in lib / example.ex.
Please use this if you like.
> fix plug lesson, about the router

- _assets/stylesheets/main.scss
- _data/contributors.yml
- _includes/contributor-profile.html
- _includes/function-getArticle.html
- contributors.html
In the spirit of Hacktoberfest, I figured that I'd spruce up the contributors page. Feedback and suggestions are welcome.
- refactored contributors.yml - this change is meant to bundle contributions into individual contributor blocks for easier management.
- changed contributors.html - contributors are now displayed like a profile with links to contributions in most cases.
> Refactor contributors.yml

- _posts/2018-10-23-umbrellas-just-when-it-rains.md
Small change.  Realized running locally it does not care for the `:` in the title.
> Quote string to resolve warning

- _assets/stylesheets/dark.scss
The new dark mode has a small, assumingly inadvertent, inconsistency of adding a border-top to the first sidebar menu listing. (the regular theme [specifically has a rule removing this border](https://github.com/elixirschool/elixirschool/blob/master/_assets/stylesheets/layout/_menu.scss#L96-L100))
**Current light:**
**Current dark:**
**Dark with change:**
> fix dark mode sidebar border inconsistency

- _config.yml
Should we make a plugin to pull this automatically from somewhere or leave it on manual as it is?
> Bump elixir / erlang versions to latest stable

- _config.yml
This PR fixes #1564
Turns out we had an incorrect `baseurl` setting in `_config.yml`. I made the decision to just remove the setting because we are accepting Jekyll's default value (which is just an empty string).
> remove incorrect baseurl

- _assets/stylesheets/dark.scss
<details>
<summary>Table headers are invisible in dark theme:</summary>
</details>
> Fix table headers' text color in dark theme

- _includes/section-home-blog-posts.html
Right now, if a new visitor comes it reads 'Recent Posts`juxtaposed with the book content of the left side once opening the index.
It is clear this is reference material present and to be consumed, but what is the right side and lower?
We do not translate blog entries at this time, we do concentrate on the book-style-content for obvious reasons.
This makes the boundary more clear.
> Clarify frontpage language to note that right side entries are of the blog

- _includes/section-sidebar-menu.html
- _layouts/default.html
1. Changed "Elixir School" in the header to link to the respective localized home page (e.g. `href="/ja/`) instead of simply `href="/"`.
2. Adapted the "Menu" heading in the sidebar into an "Elixir School" link to the localized home page. (As the sidebar is a ToC, a homepage link should definitely be on there, but one is currently missing. The "Menu" heading, meanwhile, is entirely superfluous but also perfectly positioned and styled as a title / homepage link. 😄)
> add localized homepage links

- en/lessons/specifics/ecto.md
add 'a' to end of 
@required_fields ~w(username encrypted_password email)
and
@optional_fields ~w()
lines. Without it validate_required(@required_fields) throw error: " expects field names to be atoms, got: " string name of field.
> update ecto lesson

- en/lessons/specifics/ecto/changesets.md
Changesets chapter for #1519.
I mostly followed the topics outlined in #1519 ; I decided not to have dedicated section for `Changeset design approaches`,  but rather try to sneakily introduce this kind of thinking, alongside the other content. Not sure if it was successful, so I'd love to hear people's feedback 😆 
Any feedback is of course welcome 😄
> Ecto Changesets chapter

- en/lessons/basics/functions.md
This is a PR to add clarity on pattern matching within function parameters. 
I'd like particular feedback on the following:
One thing I've seen in a few blog posts is that there's an order to the way incoming parameters are matched against the function argument.
For example, if we have 
```elixir
def hello(%{name: name} = person)
```
an incoming map would first match against person, then move on to matching `person` against `%{name: name}`. From what I could tell, the two parts of the argument are independently matching against incoming parameters; the order doesn't matter because they aren't pattern matching against each other. I would love to hear any clarifying thoughts on this part and if I've misunderstood.
For reference, an excerpt from one of the blogs:
> Elixir is pattern matching …
> Add section on functions and pattern matching.

- _data/contents.yml
- en/lessons/specifics/ecto/associations.md
Draft of the Ecto Associations lesson requested by this issue: https://github.com/elixirschool/elixirschool/issues/1519
Looking for feedback on:
1. Structure of lesson:
a. Does it make sense to organize associations into these three types?
* belongs to/has many, belongs to/has one, many-to-many
b. Does it make sense to build out each type of relationship and only then get into inserting data and querying it? Or would it make sense to describe how to insert and query data for each type of relationship before moving on to the next one?
2. Direction of content: This post is more instructional, i.e. "this is how we do preload data". Not sure if that is preferred to a deeper dive in which we take a look at _how_ stuff works, i.e. "This is what is happening under the hood when we use …
> Ecto: Associations lesson

- en/lessons/advanced/typespec.md
The "Specifications and types" page compares Elixir's "specifications" to the concept of an "interface", suggesting that this might be a helpful analogy if you're familiar with Java or Ruby.
Ruby doesn't have a concept of interfaces in the language, so this seems like a bit of an odd thing to say. (Although the generic, abstract concept of an "interface", as in a "contract", is likely to be familiar to many programmers.)
This removes this reference to Ruby, just referring to Java instead.
> Don't suggest that the concept of an interface will be familiar to Ruby developers

- en/lessons/specifics/plug.md
At the moment, the "Plug" page is a bit confusing in that it tells you to add a `:plug_status` field to your custom exception when it won't work until much later in the guide.
This adds the `:plug_status` field much later, after we've set up the `Plug.ErrorHandler` plug, and explains how it works a bit better.
> Explain better the use of exceptions with a `:plug_status` field in the the "Plug" guide

- _layouts/post.html
Retrieve the information of the author of a blog post from `contributors.yml`
if the author's website is unknow we fallback on their github page.
> Retrieve all author's metadata from contributors.yml

- es/lessons/basics/collections.md
Update collections to latest Spanish version
> [es] update collections to v1.2.5

- pt/lessons/ecto/associations.md
Translating the associations to pt-BR
> [PT] Translation of Ecto associations lesson for Portuguese

- en/lessons/ecto/associations.md
I was confused a lot when tried to read this first few times, so decided to improve it.
Also, current version states `Unlike adding the `movie_id` column to our `characters` table, this macro _doesn't_ add anything to the database.` While this is true, as in schema definitions don't change anything in database, it implies that we don't have `movie_id` field in schema, which is not correct - it's [defined by default](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/schema.ex#L1797) by `belongs_to` macros.
Edit: After the initial PR creaton I found some other places which could be refactored.
It's OK to squash these.
> Reword confusing part in Associations lesson

- CONTRIBUTING.md
- README.md
Seems like after updating CONTRIBUTING guide README wasn't updated. Let's fix that.
Also, readability/spelling/grammar fixes. It's the root page of the repo, after all. 😄 
Moving some parts from README to contributing, removing duplicates.
> Update and sync CONTRIBUTING and README

- _includes/_sidebar.html
Adding `title` attribute to the `a` element.
This "Toggle Theme" will show in the form of a tooltip on mouse hover
> Update theme toggler

- _posts/2018-03-18-phoenix-live-view.md
The usage of this term is a little tricky, but after some discussion, @chrismccord concluded:
> the thing you build yourself is a “live view”. The feature itself is “LiveView”
See usage in https://github.com/phoenixframework/phoenix_live_view/commit/c572acf69473b29f4544aae9e196fccb068e85fc
> Change spelling of LiveView

- _posts/2018-03-18-phoenix-live-view.md
* fix live reloading path in example
* fix module name for GithubDeployView
> Fix path and module name in LiveView post

- _assets/stylesheets/layout/_main.scss
#main div stretches too much when very long strings without breaks are present, making the sidebar disappear out of view
Fixes #1751
> fix: #main div stretching too much

- _posts/2018-03-18-phoenix-live-view.md
Looks like the correct mix tasks for this is `phx.gen.secret`, not `phx.secret`. See https://hexdocs.pm/phoenix/phoenix_mix_tasks.html
> `phx.gen.secret` generates a secret, not `phx.secret`

- _assets/stylesheets/main.scss
- _posts/2018-03-18-phoenix-live-view.md
adding a css class to make iframes responsive and respect the viewport's witdth
this avoids the horizontal scrollbar on mobile
before:
after:
> fix unresponsive embeds

- _posts/2018-03-18-phoenix-live-view.md
A couple of missing `)`s in the code in the post.
Also added instructions to run `npm install` after adding `phoenix_live_view` as a dependency, otherwise Phoenix can't find it when running the application.
> Fix code snippets in Phoenix Live View post

- README.md
Right now README looks weird:
This PR fixes this problem
> Fix counters in README

- _posts/2019-02-21-supervisor-strategies.md
In a few places in the post the functionality of Counter.One and Counter.Three are accidentally swapped.  I've swapped them back.
I also updated the functionality of rest_for_one as I understand it but would appreciate someone correcting me on this one if I've gotten it backwards as the original post implied.
> Corrected the functionality of Counter.One and Counter.Three

- _includes/share-icons.html
As Google+ doesn't exist anymore, the link in social sharing list should be removed.
> Remove Google+ share icon

- _includes/report.html
| Before   | After    |
| -------- | -------- |
|![image](https://user-images.githubusercontent.com/4408379/55836235-a9f80780-5b26-11e9-9227-91bf6ad10237.png)|![image](https://user-images.githubusercontent.com/4408379/55836466-3b677980-5b27-11e9-9148-34945bbb2c66.png)|
Typo :)
> Fix icon class for last commit on Report page

- _includes/contributor-profile.html
- _includes/function-displayAuthor
- _includes/section-author.html
- _layouts/post.html
- Multiple blog authors are now supported via `authors` block in post's 
front matter 
ex: `authors: ['burden', 'Sean Callan']`
- Article’s header now displays authors in order of appearance.
- Footer also displays authors in order of appearance.
> Multiple blog authors

- en/lessons/specifics/plug.md
- zh-hans/lessons/specifics/plug.md
- zh-hant/lessons/specifics/plug.md
Small PR just to clean a few things in favor of readability:
1. Removed `( )` from the plug calls as this is not as common in the wild. The standard .formatter.exs for Plug exempts these calls as well.
1. Multi-lined all the routes for readability.  Single line and no spaces between definitions makes things run together.
> Refactor code snippets for readability

- en/lessons/specifics/mnesia.md
The article said "Mnesia support indices on non-key columns", but hadn't mentioned key columns yet.
> Define what the key is

- _assets/javascripts/main.js
- _assets/stylesheets/layout/_sidebar.scss
On mobile, the sidebar is shown for a moment on changing page.
This PR resolves the problem by hiding sidebar until `skel` detects screen width.
> Improve the page-shown moment: hide sidebar until skel detects screen size 

- en/lessons/advanced/otp-distribution.md
I think  not `Node.spawn_link/1`, but `Node.spawn_link/2` 🤔 
https://hexdocs.pm/elixir/Node.html#spawn_link/2
and `send/3`, not `send/2`.
> Fix wrong arity on otp-distribution and small miss

- en/lessons/basics/mix-tasks.md
- en/lessons/ecto/associations.md
- en/lessons/ecto/querying.md
- en/lessons/libraries/guardian.md
Some small spelling/consistency mistakes.
_About `mix-tasks.md`_
The example says:
```
@shortdoc "Simply runs the Hello.say/0 function"
```
And the output later shows:
```
mix hello             # Simply calls the Hello.say/0 function.
```
So I fixed the first one to look like the second one.
> Some spelling/consistency mistakes

- pt/lessons/basics/control-structures.md
Hi, everyone! It's my first contribution.
It's just a minor typo fixing. 
I'm considering the spelling in pt-BR, in which, the word `encadiar` is a typo (the correct spelling is `encadear`). I'm not sure if this word is correct in other variants from Portuguese. 
Thanks for your attention.
> [pt] Fix a Portuguese typo in the `basic/control-structures.md`

- _posts/2019-06-04-live-view-with-channels.md
Too many images back to back looks weird--you can't tell where one diagram starts and the other begins. Adding a divider between each.
> add divider between images

- en/lessons/basics/collections.md
Using the operator as in the example creates a new map and dont update the map itself.
> Clarification about the map update operator

- zh-hans/lessons/basics/modules.md
「在一个模块里只定义一个结构体是一种常用的手法。」稍有歧义，可能被理解为数量上的唯一，无法说明这么做的目的。
> [zh-hans] improve lessons/basics/modules.md

- pt/lessons/basics/control-structures.md
introduzinos should be introduzimos.
Anyway, utilizamos has a better semantic in this case.
> [PT-br] Fix miss spelling error

- pt/lessons/basics/basics.md
- excessão should be exceção: https://duvidas.dicio.com.br/excecao-ou-excessao/
> Fix issue in pt/lessons/basics/basics.md

- en/lessons/basics/documentation.md
_The example below_ reads more natural than _the below example_.
> The example below

- en/lessons/basics/sigils.md
The function is used or called, not implemented.
> Change implement using to use with

- en/lessons/basics/strings.md
Some small textual updates to the Strings chapter.
> Textual updates to Strings chapter

- en/lessons/basics/enum.md
`uniq/1` is simpler than `uniq_by/2`, though the latter is more flexible. I think simplicity wins for these guides. We can also mention both.
> Change uniq_by to simpler uniq

- en/lessons/basics/collections.md
Add a note and example that Map update operator only works to update an _existing_ key, and an example to use Map.put/3 for a new key instead.
> Specify that Map update operator syntax only works for existing keys

- it/lessons/basics/basics.md
Fixed a mistype in the it/basics/basics markdown file
```
virogla -> virgola
```
I also  updated the patch version as requested in contributing:
```
1.2.0 -> 1.2.1
```
> mistype in it/basics/basics

- ja/lessons/advanced/otp-supervisors.md
A new translation of ja/lesson/advanced/otp-supervisors.md from the latest English version.
I have changed much from the current translation v1.0.1 because of the much difference between the two original English documents. I have tried to write my translation to be natural Japanese.
This is my first challenge of a pull request, so if there is some wrong process please let me know.
According to the document of https://qiita.com/ma2ge/items/edb392ecadb6cfc3177e,
I append the name of the translation team: @elixirschool/japanese.
Regards, Yutaka.
> [JA] translation otp-supervisors.md v1.0.1 -> 1.1.1

- _posts/2019-04-11-live-view-with-pub-sub.md
I was following along with this tutorial and got a compilation warning because the my config referenced an application (`pair`) that was not available.
I assume the basis for this post was an app called "pair" and this was just leftover 😄 
(I also updated a reference in the example output just for completeness.)
Thanks for your work!
> Swap "pair" for "my_app"

- en/lessons/ecto/changesets.md
Example referenced change/2, but example was showing cast/4.
> Corrected example for change/2

- en/lessons/ecto/associations.md
It could make sense to include a unique index on :movie_id on the distributors table as there may only be one for each movie.
> Add a unique index for the one to many relation

- pt/lessons/basics/modules.md
Hi.
I was re-reading the module lesson, but this time in portuguese, and I noticed that it was missing the part that talks about instrospection, since it is hacktoberfest, I felt like it is a good time to updated it, so I've done.
I have also bumped the version of the lession from 1.3.0 > 1.4.0, since it is on pair with the english version now.
> [pt] Updates the module lesson, with instropection for structs

- en/lessons/ecto/querying.md
I was translating this article and noticed few issues with examples:
1. 
>We use the `Ecto.Query.select/3` function to specify the select statement portion of our query. If we want to select only certain fields, we can specify those fields as a list of atoms or by referencing the struct's keys. Let's take a look at the first approach
here we talk about a _function_ `Ecto.Query.select/3` and that we can pass a list of keywords... but in example it's actually a `from` macro with keyword query:
```
iex> query = from(Movie, select: [:title])
#Ecto.Query<from m in Example.Movie, select: [:title]>
```
2. 
>The following query will preload associated records in a _separate_ query.
>We can see that the above line of code ran _two_ database queries. One for all of the movies, and another for all …
> en/lessons/ecto/querying.md > fix few minor issues with code listings

- de/lessons/advanced/umbrella-projects.md
- en/lessons/advanced/umbrella-projects.md
- es/lessons/advanced/umbrella-projects.md
- id/lessons/advanced/umbrella-projects.md
- ja/lessons/advanced/umbrella-projects.md
- pl/lessons/advanced/umbrella-projects.md
- pt/lessons/advanced/umbrella-projects.md
- ru/lessons/advanced/umbrella-projects.md
- vi/lessons/advanced/umbrella-projects.md
- zh-hans/lessons/advanced/umbrella-projects.md
- zh-hant/lessons/advanced/umbrella-projects.md
The output of the command in the REPL seems to have changed:
```
$ machine_learning_toolkit> mix compile
==> datasets
Compiling 1 file (.ex)
Generated datasets app
==> utilities
Compiling 1 file (.ex)
Generated utilities app
$ machine_learning_toolkit> iex -S mix
Erlang/OTP 21 [erts-10.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Interactive Elixir (1.9.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Datasets.hello
:world
iex(2)> 
```
> Update output of `Datasets.hello`

- _posts/2019-05-06-live-view-with-presence.md
- _posts/2019-06-04-live-view-with-channels.md
- _posts/2019-08-23-til-ecto-select-merge.md
- _posts/2019-09-12-elixirconf-2019-review.md
- _posts/2019-09-15-releasing-an-umbrella-app-with-docker-and-mix-release.md
- _posts/2019-10-20-sorting-a-table-with-live-view-live-links.md
This resolves https://github.com/elixirschool/elixirschool/issues/2087
The main cause was that the category in the post does not exist inside of
https://github.com/elixirschool/elixirschool/blob/master/_data/blog-meta.yml#L1
which means that in 
https://github.com/elixirschool/elixirschool/blob/master/blog-archive-categories.html#L21
it tries to apply the blog metadata but it can't find it, so based on how
https://github.com/elixirschool/elixirschool/blob/master/_includes/function-getCategoryMeta#L1
works it will keep the metadata context of the previous item it looped over ( in this case it was til).
I dabbled a bit with defaulting a name if it does not exist, but because the loop is based on how the present keys whether it exists or not, I'd have to do a more significant overhaul of how …
> use the correct categories for posts

- en/lessons/ecto/basics.md
- es/lessons/ecto/basics.md
- Updates the Ecto/Basics ES lesson to 2.4.0
- Fixes bad spelling of `accompany` in the [EN] Ecto/Basics lesson
Closes #2090
> [ES] Update Ecto/basics

- en/lessons/basics/basics.md
One thing that really bothered me throughout learning is that the pipe operator wasn't mentioned during the first few chapters in the basics. Therefore I propose a change in order to make the lives of newcomers easier. This change introduces a reference to the pipe operator which should be enough to get newcomers to understand what's going on.
> Add a small reference to the pipe operator

- _includes/report.html
I only hide it for now, until we move the service to a server who can leverage this option.
> hides last commit option in report page for now

- .typo-ci.yml
Just following up on https://github.com/elixirschool/elixirschool/pull/2134#discussion_r347145976 
I ran the current `.typo-ci.yml` through a linter ( http://www.yamllint.com/ ) and it raised a validation error (starting a string with `*` was the issue),  converting the paths to strings fixes this.
Typo CI wise, this meant it would ignore the `yml` file as it was unable to parse it (Which I think silently failing isn't ideal). I'm going to update it on my end to make an invalid `.typo-ci.yml` more clear.
> Updating .typo-ci.yml to use strings for excluded files

- en/lessons/ecto/querying.md
Hello!
I've been translation ecto querying lesson and was confused by `from` and `select` part. It looks like keyword-based and macro-based queries subject somehow got mixed with bindingless and bindingful expressions. So I decided to make a step back and rework this part of the lesson to be more aligned with ecto documentation.
I am by no means proficient in English so please feel free to comment on grammar and wording or even take this PR over for further work.
> [EN] lessons/ecto/querying Rework part about keyword and query expressions

- _assets/stylesheets/layout/_sidebar.scss
This fixes a bug in Google Chrome (and other Chromium-based browsers) which causes the `text-indent` and `text-overflow` (and possibly by extension `overflow`) properties to behave differently in Chrome version 77.0.3865.75 and above.
As a result, the fallback text of "Toggle" is displaying behind the hamburger icon that toggles the display of the sidebar menu.
[This StackOverflow post](https://stackoverflow.com/questions/58035496/chrome-update-affects-css-text-overflow-in-relation-to-text-indent) seems to describe the issue.
I've tested these changes in Chrome and Firefox on Ubuntu 19.10.
> Fix text-indent bug in Google Chrome

- en/lessons/specifics/mnesia.md
The last code block when run, throws errors since a `do` is missing from the first line of the blcok
> Add missing `do` in the create_table case block

- en/lessons/advanced/gen-stage.md
Just fixing what appears to be a word-swap typo.
> "works of unit" -> "units of work" in gen-stage.md

- en/lessons/basics/sigils.md
Elixir 1.9.0 Added the `~U` sigil. I added a section to give an example of the `~U` DateTime sigil
We have an example for the user to define their own `~u` sigil which might be confusing later now that `~U` exists, so I've replaced it with the `~p` sigil.
> Update for Elixir 1.9.0 ~U sigil

- en/lessons/advanced/otp-supervisors.md
This commit adds missing commas to the map returned from `child_spec/1`.
> Add commas to returned map in otp-supervisors.md

- de/lessons/advanced/otp-supervisors.md
- es/lessons/advanced/otp-supervisors.md
- ja/lessons/advanced/otp-supervisors.md
- pt/lessons/advanced/otp-supervisors.md
- zh-hant/lessons/advanced/otp-supervisors.md
This commit adds commas to the maps returned by `child_spec/1` in the
OTP Supervisors lesson. A previous PR fixed this for the english
version. This commit fixes the issue for the following versions:
* de
* es
* ja
* pt
* zh-hant
Previous PR: #2188
> Add missing commas in otp-supervisors.md

- README.md
The [translation report (example for Portuguese)](https://https://elixirschool.com/pt/report/) lists the pages that need to have their content updated or that need to be translated from scratch.
Having the address for the report inside the README.md file along with the other translation instructions makes it easier for people new to the project to pick up a page and translate it, or update the contents of a translation in a given language. What do you think? :)
This is my first contribution to the project, thanks in advance! 😄
> Add translation report reference to README.md

- en/lessons/advanced/umbrella-projects.md
- en/lessons/basics/mix.md
Since `mix new` no longer generates the `config/` directory as of Elixir v1.9.0, the bash outputs for `mix new` occurring in `basics/mix.md` and `advanced/umbrella-projects.md` ought to be updated to reflect the new behaviour
> Updates to reflect current behaviour of `mix new`

- en/lessons/libraries/bypass.md
- es/lessons/libraries/bypass.md
- pt/lessons/libraries/bypass.md
- ru/lessons/libraries/bypass.md
- zh-hans/lessons/libraries/bypass.md
- zh-hant/lessons/libraries/bypass.md
This PR fixes a typo in the [lesson](https://elixirschool.com/en/lessons/libraries/bypass/) for [Bypass](https://github.com/PSPDFKit-labs/bypass/).
The test [here](https://github.com/elixirschool/elixirschool/blame/master/en/lessons/libraries/bypass.md#L215) passes in a `health_checks` option, but the receiving code actually requires `health_check` as seen [here](https://github.com/elixirschool/elixirschool/blame/master/en/lessons/libraries/bypass.md#L168):
```elixir
def init(opts) do
health_check = Keyword.get(opts, :health_check, HealthCheck)
end
```
> `Scheduler` module expects singular `health_check` option

- en/lessons/basics/documentation.md
`mix new example` doesn't generate  a `config` folder and `config/config.exs` anymore.
> Update what mix generates

- en/lessons/ecto/associations.md
Previous lesson is Friends, and no longer Example.   Changing all references to Example or example (other than in the context of the 'Netflix example') to either Friends or friends, respectively.
> Changing references to Friends from Example

- en/lessons/advanced/gen-stage.md
These changes:
1. Update gen_stage to latest version
2. Remove deprecated `worker()` and replaces with tuple style child_spec
> Update to tuple spec

- en/lessons/ecto/querying.md
Similar to my previous edit, I'm updating all the references to 'Friends' instead of 'Example' so that the student can continue on with the same example app created in the first section of the Ecto lessons.
> Updating to reference 'Friends' instead of 'Example'

- pt/lessons/advanced/umbrella-projects.md
The correct output message from Datasets.Hello is "Hello, I'm the datasets" and not the :hello.
Because the file was modified for show that message.
> [pt] The correct output message from Datasets.Hello

- pt/lessons/basics/mix.md
Fix a typo in the first paragraph of "Novos Projetos" section.
> [pt] Fix a typo

- en/lessons/advanced/erlang.md
In accordance with Elixir Style Guide - use parentheses when using the pipe operator
> update Erlang Interoperability - add parentheses

- en/lessons/ecto/changesets.md
I am using the Elixir 1.10.0.
And if I try the change like that it will get an ArgumentError:
> Ecto.Changeset.change(%Friends.Person{name: "Bob"}, %{"name" => ""})
** (ArgumentError) field names given to change/put_change must be atoms, got: `"name"`
(ecto 3.4.0) lib/ecto/changeset.ex:1200: Ecto.Changeset.put_change/7
(stdlib 3.10) maps.erl:232: :maps.fold_1/3
(ecto 3.4.0) lib/ecto/changeset.ex:391: Ecto.Changeset.change/2
So the correct is using atoms keys.
> the method change must be using the atom key

- pt/lessons/ecto/basics.md
It needs to put the match 'person' for after do the `person.name`.
> [pt] add missing assignment in ecto/basics.md

- _includes/_head.html
- _includes/share-icons.html
I wanted to subscribe to the blog and couldn't find the feed.
This PR:
* Adds a `<link>` tag to the RSS feed to make it discoverable to browsers (and users)
* Adds a link with icon to the share icons section of the header to make the feed more discoverable to users
I couldn't find whether the `feed.xml` was localised. I'm guessing the future it would be nice if the feed was localised and then we could link to the correct feed for each language.
> Make RSS feed more discoverable

- en/lessons/ecto/associations.md
The correct output when use the preload is this and not empty values.
And the correct Actor name for the ` Repo.update! movie_actors_changeset` is the `"Tyler Sheridan"` and not `"Bob"`.
> The correct output it's this values

- pt/lessons/ecto/associations.md
The correct values for the preload it's all of this preloaded [:distributor, :characters, :actors] models.
And the correct name when do the `Repo.update! movie_actors_changeset` is the `"Tyler Sheridan"` and not `"Bob"`.
> The correct values are these

- en/lessons/basics/documentation.md
This PR:
* Changes the `deps` line to remove Earmark and bump the version as per the current `ex_doc` version. Earmark is pulled in fine so it's not required explicitly. 
* Removes references to Pandoc and Hoedown and they are both no longer supported. Only Cmark remains as a supported alternative - removal of [Pandoc](https://github.com/elixir-lang/ex_doc/commit/62c774429592b0a84eac8bade58d518e046c49e7) and [Hoedown](https://github.com/elixir-lang/ex_doc/commit/5682997004627dfb140736a2e88215d2e76bf25e#diff-04c6e90faac2675aa89e2176d2eec7d8).
* Updates the link to the Cmark documentation as it was [re-organised here](https://github.com/elixir-lang/ex_doc/commit/060ef259e96bfc0e158c7d5e5d3a59b208c37e2b#diff-04c6e90faac2675aa89e2176d2eec7d8).
> Update ex_doc lesson

- _posts/2020-04-24-instrumenting-phoenix-with-live-dashboard.md
Link was broken due to malformed Markdown
> Fix broken link on the "Instrumenting Phoenix with Telemetry and LiveDashboard" blog post

- _posts/2020-04-22-instrumenting-phoenix-with-telemetry-part-one.md
I wasn't 100% sure if the added "up" in https://github.com/elixirschool/elixirschool/commit/b7083e867243a19f9ca8c5b5258be3dbebbae5b7 was necessary, so ignore it if not :)
The second commit https://github.com/elixirschool/elixirschool/commit/930515974d2b9eca72304f766ae33c202162d64e adds starting the `StatsdReporter` in `application.ex`. This [is _in_ the follow along code repo](https://github.com/elixirschool/telemetry-code-along/blob/part-1-solution/lib/quantum/application.ex#L9), but not in the article. I wasn't sure if that was on-purpose or not?
> Small improvements to Telemetry Part One

- en/lessons/basics/date-time.md
Word `Contrary` was missing a letter `r`
Issue -> https://github.com/elixirschool/elixirschool/issues/2300
> Fix typo in date-time.md

- en/lessons/specifics/debugging.md
The heading of the lesson content should starts with `h2`.
Before:
After:
> [en] Fix the heading levels of the debugging lesson

- _layouts/post.html
Closes #2316
We already have the `Edit this lesson` link. Would be nice to have the same thing for blog posts.
This PR adds the link with the same appearance as in the lessons, pointing to the blogposts on github.
> Add edit article link

- pt/lessons/advanced/concurrency.md
Hi all! 👋 
I found some small issues in the Portuguese translation for the Concurrency Lesson.
Part of them I had to adapt the phrase to be more clear in Portuguese - Brazil because terms like `to match messages` can be a little confusing if we don't refer to `pattern matching`. 
Let me know if I have to create an issue or adapt a term to Portuguese - Portugal.
Thanks for this amazing project ✨ 
The examples from Elixir School helped a lot to start to understand Elixir, including the advanced topics 🙂
> [PT] Improving the translation for concurrency lesson

- _assets/javascripts/main.js
- _layouts/default.html
Closes #2302
The problem was that the removal of the `is-loading` was happening inside a window load event. But the event listener was sometimes been added after the page was already loaded, causing it to never be triggered.
The proposed solution is to just call the setTimeout that remove the class right after, inside the window ready event listener to avoid the race conditions.
> Fix sidebar disappearing

- en/lessons/advanced/gen-stage.md
> Fixes for GenStage chapter

- en/lessons/advanced/otp-distribution.md
It seems like `use Mix.Config` line is missing in `config/config.exs` file [here](https://elixirschool.com/en/lessons/advanced/otp-distribution/#environment-specific-application-configuration).
> fix(otp-distribution): add use Mix.Config line

- en/lessons/basics/testing.md
- en/lessons/libraries/mox.md
The article regarding Mix had its metadata tag incorrectly written, and the reference to it was also broken (leads to [404](https://elixirschool.com/en/lessons/basics/libraries/mox)) in the testing article.
> Corrected reference to Mox article

- _posts/2020-05-06-instrumenting_phoenix_with_telemetry_part_three.md
On page "Instrumenting Phoenix with Telemetry part three" reference link to part four was broken.
> fix: next post ref link in telemetry part three page

- en/lessons/ecto/basics.md
Got a little stuck in the tutorial, turns out I didn't have a role called `postgres`. Thought it'd be nice to show how to fix that.
> Add sentence about DB Roles to Ecto Basics

- en/lessons/basics/enum.md
Adds instruction and examples on the use of the capture operator with the Enum module. This is a commonly used syntax and is not heavily referenced in ElixirSchool.
Many developers new to elixir have difficulty working with the capture operator and use ElixirSchool as their reference of choice. 
Thanks for any consideration, am happy to make any changes you'd like.
> Add capture operator usage to Enum.md

- _layouts/page.html
- _layouts/post.html
External links using `[target="_blank"]` must have `[rel="noopener"]` to deny access to `window.opener`. Only GitHub links were missing this attribute.
> Add [rel="noopener"] to GitHub links

- en/lessons/specifics/ets.md
It yields a warning.
```elixir
iex> :ets.match :testing, {:"$2", :"_"} 
#warning: found quoted atom "_" but the quotes are not required. Atoms made exclusively of Unicode letters, numbers, underscore, and @ do not require quotes
```
> change atoms from :"_" to :_

- ja/lessons/advanced/gen-stage.md
I translated `lessons/advanced/gen-stage` section.
refs:
https://github.com/elixirschool/elixirschool/commit/8a8f948636d464505a47856cd05728504fe30d78#diff-fcfcf0d77c8e505bfe6a27160fba7049
https://github.com/elixirschool/elixirschool/commit/09b28344300e5c395322e972ea085247cdcefbd4#diff-fcfcf0d77c8e505bfe6a27160fba7049
https://github.com/elixirschool/elixirschool/commit/9a37e0afb1ee8462ee203fdeca9e87a18a78c6d1#diff-fcfcf0d77c8e505bfe6a27160fba7049
> [JA] Translate gen-stage 1.1.1

- en/lessons/advanced/otp-distribution.md
- en/lessons/basics/date-time.md
- en/lessons/libraries/distillery.md
- en/lessons/libraries/nimble-publisher.md
- en/lessons/libraries/stream-data.md
- en/lessons/specifics/debugging.md
- en/lessons/specifics/nerves.md
There were some code blocks that missed language specification.
Since there is no default language set for Jekyll, those code blocks ended up not being highlighted.
> Add missing highlighting to code blocks

- en/lessons/advanced/umbrella-projects.md
"umbrella projects root" and "umbrella projects configuration" should include apostrophes.
> PATCH: fixed 2 typos in umbrella-projects.md

- bg/lessons/basics/pattern-matching.md
- bn/lessons/basics/pattern-matching.md
- de/lessons/basics/pattern-matching.md
- en/lessons/basics/pattern-matching.md
- es/lessons/basics/pattern-matching.md
- fr/lessons/basics/pattern-matching.md
- gr/lessons/basics/pattern-matching.md
- id/lessons/basics/pattern-matching.md
- it/lessons/basics/pattern-matching.md
- ja/lessons/basics/pattern-matching.md
- ko/lessons/basics/pattern-matching.md
- ms/lessons/basics/pattern-matching.md
- no/lessons/basics/pattern-matching.md
- pl/lessons/basics/pattern-matching.md
- pt/lessons/basics/pattern-matching.md
- ru/lessons/basics/pattern-matching.md
- sk/lessons/basics/pattern-matching.md
- ta/lessons/basics/pattern-matching.md
- th/lessons/basics/pattern-matching.md
- tr/lessons/basics/pattern-matching.md
- uk/lessons/basics/pattern-matching.md
- vi/lessons/basics/pattern-matching.md
- zh-hans/lessons/basics/pattern-matching.md
- zh-hant/lessons/basics/pattern-matching.md
Currently, the example using the "Pattern Matching" List does not have the standard output as shown below.
So we fixed it.
https://elixirschool.com/en/lessons/basics/pattern-matching/
```
iex> list = [1, 2, 3]
iex> [1, 2, 3] = list
[1, 2, 3]
...
```
> Add text of　returns the value of the equation

- pt/lessons/basics/sigils.md
The word "inclue" is incorrect. The correct term is "inclui".
> [PT] Spelling correction

- _data/contributors.yml
- en/lessons/libraries/guardian.md
- pl/lessons/libraries/guardian.md
Updated Polish translation of "Guardian" lesson:
- each sentence in separate line (as in English version),
- some punctuation and stylistic corrections.
Additionaly, in English and Polish version, note about adding Guardian to deps is fixed (`{:guardian, "~> x.x"}` instead of incorrect `{guardian: "~> x.x"}`).
> [pl] Updated translation of lesson about Guardian

- en/lessons/libraries/mox.md
- Simplify instructions, removing the step to start mox manually
- Add `async: true` to the final example, to make clear that the tests can be run async
> Update mox lesson

- pl/lessons/basics/pipe-operator.md
Updated Polish translation of "Pipe operator" lesson:
- Elixir scripts are Elixir scripts instead of Shell,
- each sentence in separate line (as in English version),
- few minor punctuation and stylistic corrections.
> [pl] Updated translation of "Pipe operator" lesson

- _posts/2020-10-06-server-side-svg-charts-with-contex-and-liveview.md
Changed `THe` -> `The` in the `Render the Chart SVG` section of the article
> Fix spelling mistake on Render the Chart SVG section

- en/lessons/basics/mix.md
- pl/lessons/basics/mix.md
1. Updated translation of lesson "Mix" to match the latest version of this lessons in English version.
2. Style/punctuation/formatting updates.
3. "Typo" fixed in English version: in almost all places English article uses "Mix" (written with a capital letter), but in one place it was "mix" (written with a lowercase letter), so this plase has been updated.
> [pl] Updated translation of lesson "Mix"

- en/lessons/ecto/associations.md
This specific Elixir code block inside the Ecto > Associations lesson was missing the `iex>` prompt to indicate statements.
This pull requests adds these prompt indicators to the example.
> [en] Add missing iex prompt to characters build_assoc code block example

- _posts/2019-05-06-live-view-with-presence.md
Issue: https://github.com/elixirschool/elixirschool/issues/2496
I change the order of the parameter to second. 
#2496
> Blog Live View With Presence: Usage of broadcast_from doesn't match signature in docs

- en/lessons/basics/enum.md
I had to look up how `Enum.chunk_by()` worked in a few other sources and wanted to move those findings back into the lesson.
> Explicitly describe how chunk_by separates items

- _posts/2019-05-06-live-view-with-presence.md
This PR should fix up the incorrect code style markup.
> Fixup codestyle markup

- en/lessons/basics/documentation.md
- pl/lessons/basics/documentation.md
1. Polish translation of lesson "Documentation" has been updated.
2. Few fixes to English version:
- `c("greeter.ex")` replaced with `c("greeter.ex", ".")` (`c("greeter.ex")` compiles file without documentation),
- `@spec` added to the rendered documentation – typespec is actually present in the generated documentation (and the lesson mentions it below one of the examples).
> [PL] Translation of lesson "Documentation" (+ minor fixes in EN version)

- _posts/2019-03-18-phoenix-live-view.md
- _posts/2019-04-11-live-view-with-pub-sub.md
- _posts/2019-10-20-sorting-a-table-with-live-view-live-links.md
- _posts/2019-12-29-live-view-live-component.md
The `frameborder` attribute is not a valid `iframe` attribute and it's not making a visual difference in the site (we could use CSS if needed), let's remove it.
Found in https://rocketvalidator.com/s/328d31c1-0a28-423f-88dc-64c5c0d97590/i/112975746
> removes invalid `frameborder` attribute on Youtube iframes.

- posts/2018-10-23-umbrellas-just-when-it-rains.md
RV caught an empty h1, due to an empty title in this post
https://rocketvalidator.com/s/624562a6-bdbe-4411-9c28-3652a4887982/p/4681104/i?search=Empty+heading.&non_doc=false
> Fix missing title in blog post

- posts/2019-06-06-elixir-conf-eu-2019-review.md
Fixes https://rocketvalidator.com/s/7bc5b3d4-f96c-4aa5-aeae-7c5fab2d6560/p/4684096/v?search=Links+must+have+discernible+text
Images should have a meaningful `alt` description.
> adds missing alt and improves description of other alt tags in blog post

- en/lessons/ecto/changesets.md
Adding the atom `:age` to the code example making it easier to follow that it's talking about the same changeset made above, not creating a second changeset for validation.
> Update changeset validation notes

- _posts/2021-07-14-elixir-book-club.md
It looks like the site is not configured for the `www.` URL.
> Fix link to elixirbookclub.com

- posts/2019-01-03-elixir-kaffe-codealong.md
- posts/2019-05-06-live-view-with-presence.md
- posts/2019-06-04-live-view-with-channels.md
- posts/2019-10-20-sorting-a-table-with-live-view-live-links.md
- posts/2019-12-29-live-view-live-component.md
- posts/2020-04-24-instrumenting-phoenix-with-live-dashboard.md
- posts/2020-10-06-server-side-svg-charts-with-contex-and-liveview.md
Closes https://github.com/elixirschool/school_house/issues/145 .
Some of the old jekyll template tags for images were leftover. This pr updates those links.
> Fix Image Template Links in Posts

- posts/2020-04-22-instrumenting-phoenix-with-telemetry-part-one.md
Removing duplicated word from this sentence: "Telemetry is an open source suite of libraries which aims to to unify and standardize how the libraries and applications on the BEAM are instrumented and monitored."
> Fix duplicated word

- posts/2021-07-14-elixir-book-club.md
Updated the author link URL in the Elixir Book Club blog post to use the GitHub profile rather than personal site so the author image loads successfully.
> Update Elixir Book Club Post Author Image

- posts/2018-10-23-umbrellas-just-when-it-rains.md
This should resolve https://github.com/elixirschool/elixirschool/issues/2712 and hopefully https://github.com/elixirschool/school_house/issues/77 as well!
It looks like the title of this blog post was lost in the content shuffle. [Here is a reference](https://github.com/elixirschool/elixirschool/blob/45b80cdc97b04f39770b7cc3ae51bf36e6c66053/_posts/2018-10-23-umbrellas-just-when-it-rains.md) to a previous version of the blog post where I grabbed the title from.
> Add Title Back to Umbrella Apps Blog Post

- .github/workflows/ci.yml
This action ensures the content is properly formatted by attempting to build the School House app. If it can't build, we need to identify the formatting issue and resolve it.
Closes #2695
> Update CI to build School House

- lessons/en/ecto/changesets.md
- lessons/pl/ecto/changesets.md
1. Added Polish translation of "Ecto Changesets" lesson.
2. Small double space error has been fixed in the English version.
> [PL] Add translation of lesson "Ecto Changesets"

- lessons/en/basics/enum.md
When reading the Enum lesson, this felt odd to me
> Remove inline code style for link to official documentation

- lessons/en/storage/ets.md
The `raw` and `endraw` tags are showing up in outputted HTML
Since none of the other examples include this escaping, I am assuming it's unnecessary.
> Remove unnecessary `raw` tags in ETS.md

- posts/2022-02-12-odbc-and-streams.md
- posts/2022-02-22-odbc-and-streams.md
Add a post on using `:odbc` to communicate with relevant databases. In our setup here, I used a snowflake instance from work, but any DB that meets the specification should work.
I can expand on this by adding a follow up post on using pagination with `Stream.resource/3` instead of the mapping setup we are using here, other databases may be more efficient if querying that way.
> Add post on streaming data using `:odbc`

- lessons/pt/basics/iex_helpers.md
This newline was causing "excerpt" to be showed in the lesson page.
Before:
After:
> [PT] Remove newline in IEx Helpers lesson

- lessons/en/basics/enum.md
This pr updates the structure of the headings used in the enum lesson to match the information hierarchy better. 
Instead of starting with a level heading that matches the name of the lesson, this structure uses an `# Overview` heading instead.
I also nested the functions into a common level one heading of `# Common Functions`.
Let me know if you have any suggestions for the section names.
> Improve Heirarchy of Headings in Enum Lesson

- lessons/en/ecto/querying_basics.md
- lessons/pl/ecto/querying_basics.md
1. Added Polish translation for lesson "Ecto: Querying"
2. Fixed a typo in English version of that lesson.
**IMPORTANT: #2751 has to be merged first.**
> [PL] Add a translation for lesson "Ecto: Querying"

- lessons/en/basics/functions.md
As mentioned in the #2788 the pipe operator is used in examples on the functions page before it's introduced by the next page.
Here, I create a simple introduction about pipe operator and a link to see about.
> Pipe operator used before it's introduced

- lessons/en/basics/collections.md
When talking about key value pairs the verb "accessing" generally means accessing the value with the key. It caused me some confusion when I read it. I have removed this word, to avoid this confusion, and replaced it with plain easy to read english.
> Updated collections.md to avoid confusing usage of verb "accessing"

- .github/workflows/ci.yml
Right now CI actions are failing because the [`school_house`](https://github.com/elixirschool/school_house) project uses version 1.13 of Elixir but CI is configured on this project to use 1.12. 
Example CI failure: https://github.com/elixirschool/elixirschool/runs/6740912572?check_suite_focus=true
> Fix Elixir Version Used in CI to Match School House

- .github/workflows/deploy_content.yml
The version of cURL found in the GitHub runner doesn't support `--fail-with-body` so we should use `--fail` instead.
> Fix options to match current cURL version

- lessons/en/basics/enum.md
- lessons/pl/basics/enum.md
1. Polish translation of lesson "Enum" has been updated to reflect the latest EN version (in particular changes from #2766).
2. Added missing newlines after two sub-chapters titles in EN version.
> [PL] Update translation of lesson "Enum" (+ minor change in EN)

- lessons/ko/advanced/otp_distribution.md
Updated the tutorial config files to use import Config and config_env() instead of use Mix.Config and Mix.env(), since Mix.Config is [deprecated](https://hexdocs.pm/mix/main/Mix.Config.html).
via. https://github.com/elixirschool/elixirschool/pull/2819
> [KO] Update advenced/otp_distribution to v1.1.0

- lessons/ko/misc/plug.md
Updated the tutorial config files to use `import Config` instead of `use Mix.Config`, since `Mix.Config` is [deprecated](https://hexdocs.pm/mix/main/Mix.Config.html).
> [KO] Update plug.md

- lessons/ja/testing/stream_data.md
Revert sentences in ja/testing/stream_data that was accidentally converted by #2835 from normal sentences to headers because they include `#1` and `#2`.
screenshot (https://elixirschool.com/ja/lessons/testing/stream_data):
> [JA] Revert accidentally converted sentences by automatic linter

- lessons/en/testing/stream_data.md
Corrected a type of `SreamData` -> `StreamData` in a link
> Corrected typo for StreamData

- lessons/en/basics/mix.md
In the opening paragraph of the English version of the mix.md file, there was a missing period.
> Add missing punctuation in mix.md

- lessons/en/ecto/associations.md
I was following this tutorial, but when trying to populate the associations I kept running into a postgresql error complaining about a `column id not null violation`
I didn't realize what was going on until I looked at the database, and the recommended migration adds an `id` column to the `movies_actors` table, which I was leaving null during the `put_assoc/3` call!
Easy fix here, as other n00bs might run into this.
> Update associations.md to use primary_key: false on migration

- lessons/bn/basics/date_time.md
- lessons/el/basics/date_time.md
- lessons/en/basics/date_time.md
- lessons/es/basics/date_time.md
- lessons/fr/basics/date_time.md
- lessons/id/basics/date_time.md
- lessons/ja/basics/date_time.md
- lessons/ko/basics/date_time.md
- lessons/pl/basics/date_time.md
- lessons/pt/basics/date_time.md
- lessons/ru/basics/date_time.md
- lessons/zh-hans/basics/date_time.md
- lessons/zh-hant/basics/date_time.md
In the NaiveDateTime example, the code snippet includes the input count for iex. This serves no purpose, and might be confusing.
> Remove input count from iex example

- lessons/pt/data_processing/genstage.md
The differences found between the English and Portuguese versions are not relevant enough to justify a difference in the versions, given that most of the adjustments are related to an alternative markdown syntax, not impacting the style/rendering of the text.
> obs: The adjustments from v1.1.2 in the English version were already in v1.1.1 of the Portuguese version
> [PT] Update GenStage lesson

- lessons/zh-hant/basics/functions.md
In the context, it did not define the Module `Greeter4`. So the code example should call `Greeter2.hello`, not `Greeter4.hello`. The error message also mention to `Greeter2.hello`.
Thank you.
> [zh_hant] fix lessons functions example typo

- lessons/en/ecto/querying_basics.md
Fix structural error and to improve sentence clarity:
```diff
- With this introduction provides you with the basic building blocks to start querying.
+ With this introduction, you are provided with the basic building blocks to start querying.
```
> Fix sentence in 'Ecto Querying' lesson

- lessons/en/ecto/changesets.md
Add missing "on" for clarity:
```diff
- You can find the full list with details how to use them
+ You can find the full list with details on how to use them
```
> Fix sentence in 'Ecto Changesets' lesson

- lessons/en/basics/modules.md
The proposed change drops an unneeded apostrophe to convert "let's" to the grammatically correct "lets"
> Fix typo in modules.md

- posts/2021-06-07-clean-control-flow-in-elixir-with-pattern-matching-and-immutability.md
Typo in  /post/clean-control-flow-in-elixir-with-pattern-matching-and-immutability.md
> chore: Fix typo 

- lessons/fr/basics/basics.md
Change the error message in "Opérations booléennes" section, as in original 1.4.0.
Also : 
* Fix some typos:
* In French, ";" and ":" are always preceded by a non-breaking space
* "NOTE" -> "Note"
* Italic for acronyms, english words, and URL
* Rephrase sentence, especially certain sentences with the verb "supporter", which is used in the original English version, but is a false friend in French
* Rename operations-related sections for clarity
> Update to 1.4.0 french version of lesson basics/basics.md

- lessons/en/advanced/protocols.md
Here you would want to use "its" (which is possessive) rather than the contraction of "it is".
> Correct a typo

- lessons/en/basics/collections.md
I had to read the text a couple times cause I thought there was a missing word. I find this a bit easier to understand but YMMV :)
> Tweak text for atom-maps special syntaxes

- lessons/el/misc/nerves.md
- lessons/en/misc/nerves.md
- lessons/ja/misc/nerves.md
- lessons/pt/misc/nerves.md
Hey, everyone!
`hello_leds` example is deprecated due to [this PR](https://github.com/nerves-project/nerves_examples/pull/251).
LInk is replaced with [new blinky link](https://github.com/nerves-project/nerves_examples/tree/main/blinky/config).
> Replace deprecated url for nerves lesson

- lessons/en/basics/control_structures.md
Added variable assignment before case/2 examples. As a first time Elixir learner, I was confused by the use of the tuple and introduction to _, as it was unclear to me that "case {value} do" was using the example value (i.e. {:ok, "Hello World"}, :even) to pattern match. I added a variable assignment before as this is generally as I see case being useful
> Update control_structures.md for better case/2 clarity

- lessons/en/basics/control_structures.md
Fixing a typo with a missing 'is' for the text describing with/1
> Update control_structures.md to fix typo
